### ISSUE TITLE
onRowSelectChange and onRowSelectAllChange not being fired

### ISSUE THREAD

**Issue by cyberdevnet** [KevinVandy/material-react-table#1]
using the example at https://www.material-react-table.dev/?path=/story/features-selection-examples--on-row-select-change

Onchange events of the checkboxes are not fired:

  <MaterialReactTable
    columns={columns}
    data={data}
    enableSelection
    onRowSelectChange={(event, rowState, selectedRows) => {
      console.log({ event, rowState, selectedRows });
    }}
  />

**Comment by KevinVandy** [comment]
I didn't even realize that none of that code was being triggered. Thanks. Will be fixed in the next update today, though there are a bunch of unstable issues with the select feature in general that still need to be developed.

Congrats on being this repos first issue. I'm curious to learn how dozens of people have suddenly found my (still in alpha) project in the past week. 

Join the discord if you are curious about the roadmap for this project as I develop it!

**Comment by KevinVandy** [comment]
all I needed to do was swap the order of the props

```jsx
        <Checkbox
          inputProps={{
            'aria-label': selectAll
              ? localization.toggleSelectAll
              : localization.toggleSelectRow,
          }}
          {...checkboxProps}
          onChange={onSelectChange}
          title={undefined}
        />
```

**Comment by KevinVandy** [comment]
This should now be resolved as of version 0.6.9. However, note that the `onRowSelectChange` prop name was changed to `onSelectChange`

**Comment by domi-glyph** [comment]
Is this now changed to `onRowSelectionChange`? how do i obtain the selected rows data
?

**Comment by KevinVandy** [comment]
@domi-glyph This prop no longer exists in MRT.

But the docs are very clear on how to manage the row selection state: https://www.material-react-table.com/docs/guides/row-selection#access-row-selection-state

And in general, how to either manage all of the state you need (like to store in redux or whatever): https://www.material-react-table.com/docs/guides/table-state-management#manage-individual-states-as-needed

**Comment by domi-glyph** [comment]
> @domi-glyph This prop no longer exists in MRT.
> 
> But the docs are very clear on how to manage the row selection state: https://www.material-react-table.com/docs/guides/row-selection#access-row-selection-state
> 
> And in general, how to either manage all of the state you need (like to store in redux or whatever): https://www.material-react-table.com/docs/guides/table-state-management#manage-individual-states-as-needed

this works, thanks!

**Comment by MumarAslam** [comment]
@KevinVandy  onRowSelectionChange is not being fired for me as i am following the 
 https://www.material-react-table.com/docs/guides/row-selection#access-row-selection-state

**Comment by maitedev** [comment]
Hi @domi-glyph I'm having the same problem and I'm having a hard time finding a solution. Here's my code. I'd appreciate any help. Thanks in advance. 
`   const [rowSelection, setRowSelection] = useState({}); 

    const handleRowSelectionChange = (updater) => {
        setRowSelection((prevSelected) => updater(prevSelected));
        console.log('Selected rows data:', rowSelection);
    };

  const table = useMaterialReactTable({
        ...
        enableRowSelection: props.enableRowSelection || true,
        enableSelectAll: props.enableSelectAll || true,
       onRowSelectionChange: handleRowSelectionChange,
      state: {
            ...
            rowSelection,
        },
`
