### ISSUE TITLE
Translations into Ukrainian language

### ISSUE THREAD

**Issue by MarekPatyna** [KevinVandy/material-react-table#1002]
### material-react-table version

v2.11.2

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Hi

I am working on a project where I am using material react table. I need the table to also support Ukrainian language. I created a translation that fully supports Ukrainian language. I would be grateful for adding this to MRT.

Greetings

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/mrt-ua-i18n-language-v6tgp9?file=%2Fua%2Findex.esm.d.ts

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/103312126/6b7a9493-b2ce-47ac-88cf-5f6935beacd1)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Yeah for sure, just make a PR in the same format as the current `uk` locale`.
https://github.com/KevinVandy/material-react-table/blob/v2/packages/material-react-table/src/locales/uk.ts

btw, what's the difference between `uk` and `ua`?

**Comment by MarekPatyna** [comment]
Thank you for your reply. Unfortunately but I did not see that Ukrainian was created because I was sure that "uk" corresponds to United Kingdom. In my opinion and from what I checked on the internet the ISO abbreviation for Ukrainian is UA or possibly UKR but not UK. 

https://www.andiamo.co.uk/resources/iso-language-codes/
https://laendercode.net/en/country/ua
https://www.iso.org/obp/ui/#iso:code:3166:UA
https://en.wikipedia.org/wiki/ISO_3166-2:UA

**Comment by KevinVandy** [comment]
@MarekPatyna It seems that the full locale name is `ukUA` from my understanding. That's what Material UI itself names their locale. And usually its fine to just refer to it by the first 2 letters, unless there are multiple dialects.

<img width="659" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/18e2ad3a-7cd1-4124-b68a-f1309dbaa037">

I always refer to this website when checking: https://saimana.com/list-of-country-locale-code/

<img width="824" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/7128910e-04ee-4fe9-9f05-5202b127ac17">

**Comment by KevinVandy** [comment]
@MarekPatyna Your translations seem to be a lot different than the current uk locale in MRT. Which one is more correct? The existing one or yours?

<img width="1169" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/ae7b2b89-ad88-40a8-afbf-b20777f9d70e">

**Comment by MarekPatyna** [comment]
I don't speak Ukrainian at b2/c1+ level, so I would personally suggest leaving the current translation. Thanks for the quick replies and good luck with MRT development!

**Comment by imnasnainaec** [comment]
> I always refer to this website when checking: https://saimana.com/list-of-country-locale-code/

And if a language isn't there, its more comprehensive source is https://iso639-3.sil.org/code_tables/639/data.

**Comment by imnasnainaec** [comment]
> Thank you for your reply. Unfortunately but I did not see that Ukrainian was created because I was sure that "uk" corresponds to United Kingdom. In my opinion and from what I checked on the internet the ISO abbreviation for Ukrainian is UA or possibly UKR but not UK.
> 
> https://www.andiamo.co.uk/resources/iso-language-codes/ 
> https://laendercode.net/en/country/ua 
> https://www.iso.org/obp/ui/#iso:code:3166:UA 
> https://en.wikipedia.org/wiki/ISO_3166-2:UA

@MarekPatyna To clarify, the ISO 3166-2 code you were seeing for Ukraine (UA) is the country code, not the language code: https://en.wikipedia.org/wiki/ISO_3166#Parts

**Comment by MarekPatyna** [comment]
Apologies for writing back so late but I completely forgot about this issue. Thank you again @imnasnainaec @KevinVandy  for your help. 

Best regards!
