### ISSUE TITLE
Mantine Filter Search Does Not Work Correctly and Highlight Words When Turkish Characters Are Used with Capslock On.

### ISSUE THREAD

**Issue by Meryemgezici** [KevinVandy/material-react-table#1030]
### material-react-table version

v1.3.4

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Turn on Capslock.
Choose Turkhish language.
Navigate to the global filter section or the ToggleFilters or GlobalFilter component.
Enter Turkish characters such as "İ" or "Ü" along with other text for filtering.
Notice that the search does not execute properly, and the text is not highlighted in yellow as expected.
Repeat the process with various Turkish characters to observe consistent issues with search functionality and text highlighting.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.mantine-react-table.com/docs/examples/advanced

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/60843396/76dbcf50-81ef-48bc-ac70-3e1b34390b36)
![image](https://github.com/KevinVandy/material-react-table/assets/60843396/045c836e-b09c-4d87-a640-6498fdbd9995)
![image](https://github.com/KevinVandy/material-react-table/assets/60843396/04c18881-1a82-413d-a8e6-2a0bb31af71b)
![image](https://github.com/KevinVandy/material-react-table/assets/60843396/778274f1-908a-447e-8103-b00c1c406097)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is the Material React Table repository.

**Comment by Meryemgezici** [comment]
I can't share my code with you because it's private information. Can you tell me what can I do?
