### ISSUE TITLE
Header title has been dissapear from v10 to v11

### ISSUE THREAD

**Issue by 11joselu** [KevinVandy/material-react-table#1042]
### material-react-table version

11.0

### react & react-dom versions

latest

### Describe the bug and the steps to reproduce it

Hello,

We start migrating from v10 to v11 and we catch that the header title was removed on v11

https://github.com/KevinVandy/material-react-table/commit/9b085d570b0f63dfb028cc861b08300087d9fc2d#diff-14511697e8813fa2b40be42ddb17235d138cf21c768924f3826bf98b15f3aebcL270

Is there any reason?

### Minimal, Reproducible Example - (Optional, but Recommended)

You cant view it in the basic table example on https://www.material-react-table.com/

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
because I got so many complaints that it was there. You can easily add it back in `muiTableHeadCellProps.title`
