### ISSUE TITLE
[BUG] - Sub Row Selection not working correctly

### ISSUE THREAD

**Issue by apandey00** [KevinVandy/material-react-table#1046]
### material-react-table version

2.12.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

After clicking the group header to select all sub-rows, 
individually unselecting the sub-rows results in the group header being left as checked ☑️ instead of unchecked 🔳.

### Minimal, Reproducible Example - (Optional, but Recommended)

You can repro in the live storybook:
https://www.material-react-table.dev/?path=/story/features-sub-row-tree-examples--sub-row-tree-with-selection

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/55708699/158b1646-cc95-47a1-af35-ccf186185db3

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
To me, this is the expected behavior. If you check a row, that row goes into the row selection state.
