### ISSUE TITLE
Tooltip on FullScreenButton not showing on focus

### ISSUE THREAD

**Issue by dirkjf** [KevinVandy/material-react-table#1076]
### material-react-table version

v2.12.1

### react & react-dom versions

v18.0.0

### Describe the bug and the steps to reproduce it

All buttons show their tooltips when focused (using the keyboard - not the mouse), but this does not work for the full screen button. 

Working:
![image](https://github.com/KevinVandy/material-react-table/assets/34198573/611b9e41-3a8d-43cf-a71a-ee0002aa94b5)

Not working:
![image](https://github.com/KevinVandy/material-react-table/assets/34198573/1bd7de77-b9f4-4935-be79-c79b88450138)

### Minimal, Reproducible Example - (Optional, but Recommended)

See https://www.material-react-table.com/docs/examples/basic and use your keyboard to focus the buttons. 

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/34198573/48b56f05-b8e6-4054-9aad-c4ca82c3b460)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by dirkjf** [comment]
ps. It would also be nice to close the full screen view when a user presses the escape button.

**Comment by fredericbahr** [comment]
@dirkjf this issue should be resolved when updating to v3 as the current example page shows (https://www.material-react-table.com/docs/examples/basic).

Please consider closing this issue
