### ISSUE TITLE
Getting Error while loading TS.tsx

### ISSUE THREAD

**Issue by nagarajuPathuri** [KevinVandy/material-react-table#1077]
### material-react-table version

2.12.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

We have used added all required packages in package.json and copied TS.tsx.
when we load the page we are getting below error in browser console.

Uncaught Error: Element type is invalid: expected string(for build in components) or a class/function(for composite components) but got :object

check the render method of 'MRT_ToggleRowActionMentButton'
at createFiberFromTypeandPropss (index.js:22412:25)

### Minimal, Reproducible Example - (Optional, but Recommended)

We have used code mentioned in [https://stackblitz.com/github/KevinVandy/material-react-table/tree/v2/apps/material-react-table-docs/examples/editing-crud-table/sandbox?file=src%2FTS.tsx]
Used files: TS.tsx, package.json and imported TS.tsx in to our component. 

### Do you intend to try to help solve this bug with your own PR?

Yes, I am also opening a PR that solves the problem along side this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by nagarajuPathuri** [comment]
![Error](https://github.com/KevinVandy/material-react-table/assets/23380795/a2150683-78c3-4d96-9fc3-cbefbc287124)

**Comment by KevinVandy** [comment]
This error is telling you that you are trying to render something invalid. Share code if you actually want help.
