### ISSUE TITLE
onSortingChange getting called twice on first render

### ISSUE THREAD

**Issue by Linos2508** [KevinVandy/material-react-table#1079]
### material-react-table version

v2.12.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When creating a simple table and use the onSortingChange prop the callback is getting fired twice.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/magical-paper-82vtph?file=%2Fsrc%2FTS.tsx%3A8%2C1

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Xavier9922** [comment]
Hi team, can we get a response on a plan for this fix?

**Comment by KevinVandy** [comment]
This code is kind of misusing the `onSortingChange` table option. Only use it to hoist state, and then properly add side effects like this: https://www.material-react-table.com/docs/guides/state-management#add-side-effects-in-set-state-callbacks

**Comment by Linos2508** [comment]
Hi @KevinVandy I updated the sandbox and I'm still getting called twice the sorting callback
