### ISSUE TITLE
positionCreatingRow is been ignored

### ISSUE THREAD

**Issue by jjwallaby** [KevinVandy/material-react-table#1080]
### material-react-table version

2.8.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

**positionCreatingRow: 'top'  ** is been ignored.  Always go to bottom of the last page.
Even when you use a button to create row.

  renderTopToolbarCustomActions: ({ table }) => (
      <Button
        variant="contained"
        onClick={() => {
          table.setCreatingRow(true); //simplest way to open the create row modal with no default values
          //or you can pass in a row object to set default values with the `createRow` helper function
          // table.setCreatingRow(
          //   createRow(table, {
          //     //optionally pass in default values for the new row, useful for nested data or other complex scenarios
          //   }),
          // );
        }}
      >
        Create New User
      </Button>
    ),

BTW how do  get the current row a user is on.  or last row... use was on.

Even if you use the example.  
https://www.material-react-table.com/docs/examples/editing-crud
set  positionCreatingRow: 'top'  it is ignored and always add new row to the bottom of the last page.

### Minimal, Reproducible Example - (Optional, but Recommended)

  renderTopToolbarCustomActions: ({ table }) => (
      <Button
        variant="contained"
        onClick={() => {
          table.setCreatingRow(true); //simplest way to open the create row modal with no default values
          //or you can pass in a row object to set default values with the `createRow` helper function
          // table.setCreatingRow(
          //   createRow(table, {
          //     //optionally pass in default values for the new row, useful for nested data or other complex scenarios
          //   }),
          // );
        }}
      >
        Create New User
      </Button>
    ),

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I think you are misunderstanding what the `positionCreatingRow` table option is for. It determines where the blank temporary row will show up in the table. After the row has been created/saved, it is up to your logic to splice it into wherever in the `data` you want.

If you are not misunderstanding the table option, then I don't know what you are running into. My test here is working fine: http://localhost:6006/?path=/story/features-creating-examples--create-row-index-top
