### ISSUE TITLE
Total Row count gets lost when grouping

### ISSUE THREAD

**Issue by luisphdsolutions** [KevinVandy/material-react-table#1088]
### material-react-table version

2.11.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Use this example to see the bug:
https://www.material-react-table.com/docs/examples/advanced
Select at least 1 row to display the count data at the bottom. It'll display x of 128 row(s) selected.
Now choose any column and group by it.
Check the bottom again to see the total rows...

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/examples/advanced

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by fredericbahr** [comment]
I can not reproduce this issue with current version 3.
When selecting a row and grouping afterwards, the selection states: `1 of 384 row(s) selected`.

![image](https://github.com/user-attachments/assets/5545b215-478f-41f2-b793-7bba3f05f676)


Could you please verify again and if not reproducable for you close this issue.

**Comment by luisphdsolutions** [comment]
Oh yeah, it's fixed now. Thank you!
