### ISSUE TITLE
How to make checkbox position fix?

### ISSUE THREAD

**Issue by sanjeev666** [KevinVandy/material-react-table#1096]
### material-react-table version

^2.12.1

### react & react-dom versions

^18.2.0 & ^18.2.0

### Describe the bug and the steps to reproduce it

Here I tried with your example(https://www.material-react-table.com/docs/examples/column-pinning) and its not working as aspected here facing issue with checkbox position when scrolling horizontal towards right then checkbox position fixed but when we move towards right to left then not fixed this is happening when enableColumnVirtualization is true  if we put enableColumnVirtualization as false then checkbox performance is slow i mean when we select any row it take some time so we can say its performance issue. Can you provide the checkbox position fix solution with enableColumnVirtualization is true or without decreasing checkbox performance issue.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/examples/column-pinning

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/52299248/23e4fd8f-aa03-4984-b345-96e41aafec35

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sanjeev666** [comment]
@KevinVandy can you look into it.

**Comment by KevinVandy** [comment]
If you are changing the cell/row background colors without all the complicated :before and :after styles required for pinned columns, you're going to run into this.

**Comment by KevinVandy** [comment]
You'll have to get familiar with how all the complex :before and :after styles work to solve this problem: https://github.com/KevinVandy/material-react-table/blob/v2/packages/material-react-table/src/utils/style.utils.ts
