### ISSUE TITLE
Infinite Scrolling - Infinite Loop of loading and stop scrolling after set maxPages in useInfiniteQuery

### ISSUE THREAD

**Issue by lod911** [KevinVandy/material-react-table#1111]
### material-react-table version

v2.13.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Hello

Because I have a lot of Data (>100'000 rows) I started implementing the infinite scrolling. 

After Adding the Parameter 
`maxPages`
to the useInfiniteQuery, the data keeps loading but only the size * maxPages gets loaded and displayed. Not more. When you scroll up, the loading stops.

I think its not related to MRT and not to TanStack Query. The query does, what its should do

Can anybody please help? 

Regards

### Minimal, Reproducible Example - (Optional, but Recommended)

open
https://github.com/KevinVandy/material-react-table/blob/85b98f9aaa038df48aa1dd35123560abce78ee58/apps/material-react-table-docs/examples/infinite-scrolling/sandbox/src/TS.tsx#L102

add new Line with the Parameter
`maxPages: 4`

![image](https://github.com/KevinVandy/material-react-table/assets/38237424/053d7a27-10d8-4b37-b92f-bd28e0d98de0)

run and scroll down in the table. When you reach 100 Fetches, the issue starts.

### Screenshots or Videos (Optional)

[Video 20.04.2024, 00:12:41.webm](https://github.com/KevinVandy/material-react-table/assets/38237424/7889a9bc-2c48-4fb1-9b16-d0e197357daa)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by lod911** [comment]
Yes, commit [400907c](https://github.com/crypticbeing/material-react-table/commit/400907c42433fabaf2aa8da4180c692a3ccb5736) did it. Thank you!

**Comment by KevinVandy** [comment]
This is not a bug with MRT at all, but a bug with how you were trying to use react-query. See #1116 if you want a solution.
