### ISSUE TITLE
MUI style breaking in UI

### ISSUE THREAD

**Issue by nazcoder** [KevinVandy/material-react-table#1120]
### material-react-table version

2.13.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

I am running with react version 17.0.2. 
The dependencies versions are:
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "@material-ui/core": "^4.12.4",
    "@material-ui/lab": "^4.0.0-alpha.61",
    "@mui/icons-material": "^5.15.15",
    "@mui/material": "^5.15.15",
    "@mui/x-date-pickers": "^7.2.0",
    
    The style of filterModeOption, pagination style, table body style etc are breaking. I am not able to get it the causes behind it.
    Anyone could you please help me to find out?
    
    thanks

### Minimal, Reproducible Example - (Optional, but Recommended)

dependencies version :
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "@material-ui/core": "^4.12.4",
    "@material-ui/lab": "^4.0.0-alpha.61",
    "@mui/icons-material": "^5.15.15",
    "@mui/material": "^5.15.15",
    "@mui/x-date-pickers": "^7.2.0",
        "material-react-table": "^2.13.0",
        
            muiPaginationProps: {
      color: "secondary",
      rowsPerPageOptions: [5,10, 20, 30],
      shape: "rounded",
      variant: "outlined",
    },
but shape is changing in the UI

### Screenshots or Videos (Optional)

![mrt1](https://github.com/KevinVandy/material-react-table/assets/39713259/758fc100-b46f-4069-a988-afae8c65ec5a)
![mrt2](https://github.com/KevinVandy/material-react-table/assets/39713259/d494d294-5622-45d9-bf92-f039180cf536)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Having both MUI v4 and MUI v5 installed at the same time is going to yield weird results. MUI does not recommend doing that at all.
