### ISSUE TITLE
Column editSelectOptions array with label and value do not select label in edit mode

### ISSUE THREAD

**Issue by SanjayKumarRahul** [KevinVandy/material-react-table#1121]
### material-react-table version

2.13.0

### react & react-dom versions

18.2.0 & 18.2.0

### Describe the bug and the steps to reproduce it

Define a array with label and value:
`export const usStates = [
 {label:'Ohio', value:'OH'},
 {label:'Rhode Island', value:'RI'},
];`

Use this array into column:
`{
        accessorKey: 'state',
        header: 'State',
        editVariant: 'select',
        editSelectOptions: usStates,
        muiEditTextFieldProps: {
          select: true,
          error: !!validationErrors?.state,
          helperText: validationErrors?.state,
        },`

Table data:

![image](https://github.com/KevinVandy/material-react-table/assets/151399627/74a04f32-6a0c-4292-9c5a-9d8a23695a53)

When in edit mode:

**The problem is label is not selected from dropdown option.**

![image](https://github.com/KevinVandy/material-react-table/assets/151399627/322f978d-4a99-44e3-8297-17fdb73027b0)

When dropdown is clicked the label is shown as it should:
![image](https://github.com/KevinVandy/material-react-table/assets/151399627/1e5d4d49-ef65-4884-9e98-4cfdde61ad49)

### Minimal, Reproducible Example - (Optional, but Recommended)

Code Sand Box Example

https://codesandbox.io/p/devbox/upbeat-lamarr-nwfmp8

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Interscope19** [comment]
did you figure out how to solve it?

**Comment by KevinVandy** [comment]
The value has to match the values in your data or else this will happen.
