### ISSUE TITLE
muiPaginationProps does not include rowsPerPage

### ISSUE THREAD

**Issue by aaron-parisi-turngate** [KevinVandy/material-react-table#1124]
### material-react-table version

v2.13.0

### react & react-dom versions

v16.8.0

### Describe the bug and the steps to reproduce it

I am trying to set the number of rows per page via a prop and am unable to set `rowsPerPage` on `muiPaginationProps` even though [MUI Table Pagination docs](https://mui.com/material-ui/api/table-pagination/) show `rowsPerPage`.  I can set `rowsPerPageOptions` but that's not what I'm trying to do.

![image](https://github.com/KevinVandy/material-react-table/assets/145590154/c9ff8d52-7ff8-4a17-87bb-6f866ce5d2af)

### Minimal, Reproducible Example - (Optional, but Recommended)

```
	muiPaginationProps={{
		rowsPerPageOptions: [...]
		rowsPerPage: 5 // type error
	}}
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by aaron-parisi-turngate** [comment]
I see that I can use `initialState.pagination` to control rows per page.

https://www.material-react-table.com/docs/guides/state-management#populate-initial-state

**Comment by KevinVandy** [comment]
This is by design to force you to use the proper way through state
