### ISSUE TITLE
Min, Max and Median functions not working properly on dataset with null values

### ISSUE THREAD

**Issue by yaras-phoenix** [KevinVandy/material-react-table#1138]
### material-react-table version

2.11.3

### react & react-dom versions

17.0.1

### Describe the bug and the steps to reproduce it

I have a test data array containing 87 values. Most of them are null values in DB represented as a string "-". Here is what I get using aggregation functions ['count', 'min', 'max', 'mean', 'median', 'sum']:
![image](https://github.com/KevinVandy/material-react-table/assets/37367584/6ced7845-4045-4a1e-aa77-21c05520abff)
Median is undefined, min and max are both "-".

### Minimal, Reproducible Example - (Optional, but Recommended)

[dataset.txt](https://github.com/KevinVandy/material-react-table/files/15378500/dataset.txt)

### Do you intend to try to help solve this bug with your own PR?

Not much skill here

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Use accessorFns to fallback to non null/default values. Otherwise, provide your own aggregationFns that handle the data how you want. Or this could be fixed upstream in TanStack Table.
