### ISSUE TITLE
sort on null value

### ISSUE THREAD

**Issue by Grummfy** [KevinVandy/material-react-table#1139]
### material-react-table version

2.12.1

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

* value null (from accessorFn)
* sort manual (server side)

The sort indicator move in two state and not three (ascending,  no sort, instead of ascending, descending, no sort)

### Minimal, Reproducible Example - (Optional, but Recommended)

-

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You're looking for `sortUndefined`? Although, if you are using `manualSorting`, that's up to you to implement the correct sorting logic on your back-end APIs.

https://tanstack.com/table/latest/docs/guide/sorting#sort-undefined-values

**Comment by Grummfy** [comment]
The problem is that manual sorting or not, it change nothing since the value are not properly defined in the sort state. And the sort state is what is send to the back

**Comment by KevinVandy** [comment]
I don't think I follow
