### ISSUE TITLE
how to access staticRowIndex inside AggregatedCell

### ISSUE THREAD

**Issue by tmax22** [KevinVandy/material-react-table#1149]
### material-react-table version

"material-react-table": "^2.13.0"

### react & react-dom versions

18

### Describe the bug and the steps to reproduce it

`staticRowIndex` is exported from `Cell` but not from `AggregatedCell`

```tsx
        Cell: ({ column, cell, row,staticRowIndex }) => <Checkbox checked={row.original.cp} />, //works
        
        AggregatedCell: ({ cell, table, row, staticRowIndex }) => (  //error
       ...

```

inspecting the row in react devtools shows that the row holds the prop `staticRowIndex`. is there is a specific reason why it does not exported in AggregatedCell? how to access it otherwise?

its probably just adding these missing props here: 
https://github.com/KevinVandy/material-react-table/blob/92c40b05035fbf0254931b5f8389ca9f9952b23b/packages/material-react-table/src/components/body/MRT_TableBodyCellValue.tsx#L41

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by tmax22** [comment]
i needed to use it, so i fixed it in a fork

**Comment by KevinVandy** [comment]
Just PR it. No one has ever needed it before

**Comment by Eliav2** [comment]
> Just PR it.

So I did😀

> No one has ever needed it before

Possibly, but I wouldn't be so sure

**Comment by tmax22** [comment]
> Just PR it.

So I did😀

> No one has ever needed it before

Possibly, but I wouldn't be so sure
