### ISSUE TITLE
Global filter doesnt work on material react table with sub rows

### ISSUE THREAD

**Issue by SaiPreethiAsuri** [KevinVandy/material-react-table#1163]
### material-react-table version

v2. 0.4

### react & react-dom versions

v18. 2.0

### Describe the bug and the steps to reproduce it

When a global filter is used on a material react table with sub rows, the filter doesn't perform a perfect search for the first three characters. For the first three characters the rows which don't match the search value are also shown. 

### Minimal, Reproducible Example - (Optional, but Recommended)

NA

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
think this is just wrong. And no repro, no investigation
