### ISSUE TITLE
Row virtualization is significantly slower in Chrome compared to Firefox

### ISSUE THREAD

**Issue by ipko1996** [KevinVandy/material-react-table#1170]
### material-react-table version

v2.13

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Link: [Enable Row Virtualization](https://www.material-react-table.com/docs/guides/virtualization#enable-row-virtualization)

Check this link in chrome and firefox. Chrome is so laggy

### Minimal, Reproducible Example - (Optional, but Recommended)

Repro: [Enable Row Virtualization](https://www.material-react-table.com/docs/guides/virtualization#enable-row-virtualization)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ipko1996** [comment]
I was cured all right ⚙️🍊

**Comment by testfailed** [comment]
I'm having exactly same issue on Google Chrome with Windows 10/11.
It seems Google Chrome on macOS or Android is okay though.
