### ISSUE TITLE
Multiple api calls on column filter change in manual mode while using UseEffect hook

### ISSUE THREAD

**Issue by jemish-virani** [KevinVandy/material-react-table#1195]
### material-react-table version

v2.13.0

### react & react-dom versions

v18.3.1

### Describe the bug and the steps to reproduce it

Does anybody knows a solution or faced a issue of api getting called multiple times while column filter is changed. This is causing Table fetching state to render twice and show a loader twice. I am using a manual mode with UseEffect hook.

Please check a below video which demonstrate a issue itself from the code examples.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/examples/remote

### Screenshots or Videos (Optional)

https://github.com/user-attachments/assets/016ecdca-901e-487a-ac6a-92fb5c1170b5

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Probably just a symptom of react strict mode. Else, any debouncing logic could fix
