### ISSUE TITLE
2 elements in DOM with non unique id #mrt-rows-per-page

### ISSUE THREAD

**Issue by milindagashe** [KevinVandy/material-react-table#1211]
### material-react-table version

2.13.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When 2 instances of material react table are placed inside one webpage (one DOM), it gives DOM warning:
[DOM] Found 2 elements with non-unique id #mrt-rows-per-page

As you can see there are two input tags below with same id, which is not accepted by the DOM.

<input aria-invalid="false" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" id="mrt-rows-per-page" value="20">
<input aria-invalid="false" aria-hidden="true" tabindex="-1" class="MuiSelect-nativeInput css-1k3x8v3" id="mrt-rows-per-page" value="20">

### Minimal, Reproducible Example - (Optional, but Recommended)

Just have 2 elements of material react table on the same page and you will be able to reproduce this.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This will be solved in the v3 release
