### ISSUE TITLE
Do not trim header when column width is too small

### ISSUE THREAD

**Issue by noobCode-69** [KevinVandy/material-react-table#1216]
### material-react-table version

2.0.5

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Hello Team ,
Thanks for this amazing library 

What i want is when the column width is too small the header text gets trimmed and and the icons for resizing is visible , what would be a much better approach is that the icons should be not be visible with header not being trimmed and when i hover it should become visible 

### Minimal, Reproducible Example - (Optional, but Recommended)

Resize the columns so much that the header get's trimmed

### Screenshots or Videos (Optional)

<img width="174" alt="image" src="https://github.com/user-attachments/assets/f9a16c02-ca58-46c7-a0e1-d8c20eca113f">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Just override the css

**Comment by KevinVandy** [comment]
or give a minWidth to the header
