### ISSUE TITLE
onSortingChange getting called twice on first render (reopened)

### ISSUE THREAD

**Issue by Xavier9922** [KevinVandy/material-react-table#1219]
### material-react-table version

v2.13.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When creating a simple table and use the onSortingChange prop the callback is getting fired twice.
This was mentioned at https://github.com/KevinVandy/material-react-table/issues/1079 
We followed recommendation, but the issue persists

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/tender-sea-89wm26?workspaceId=ca490667-ce10-4765-a608-13d7885b0840

### Screenshots or Videos (Optional)

https://github.com/user-attachments/assets/f25b68bf-b54d-4add-b5e4-233eecf3c863

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
It's literally just React Strict Mode. I commented it out and it only ran once. What's happening here is 100% expected React behavior.

<img width="310" alt="image" src="https://github.com/user-attachments/assets/c2c6d2f1-cecd-4ce7-b131-6412087c0c1d">
