### ISSUE TITLE
The sx property in the muiTableHeadCellsProps in the column definitions overwrites the same property in the table instance

### ISSUE THREAD

**Issue by ADPopov** [KevinVandy/material-react-table#1220]
### material-react-table version

v2.13.0

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

When customizing a table through instances in the muiTableHeadCellsProps sx property and subsequently adding sx for certain cells already in the column definition, the styles are not supplemented, but overwritten.

### Minimal, Reproducible Example - (Optional, but Recommended)

[codesandbox](https://codesandbox.io/p/devbox/dark-framework-p3sfpq)

In the example, the first column should have red text.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is intended. In fact, I'll probably be removing the all muiProp table options that can be defined on individual columns or the default column to remove this ambiguity a bit.
