### ISSUE TITLE
Support Material UI v6

### ISSUE THREAD

**Issue by oliviertassinari** [KevinVandy/material-react-table#1231]
### material-react-table version

v2.13.1

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

https://x.com/XCSme/status/1829522518517956996

### Minimal, Reproducible Example - (Optional, but Recommended)

https://github.com/KevinVandy/material-react-table/blob/7c23a21f365fef38d1819db015a5f5a56c3438d5/packages/material-react-table/package.json#L111

You can look at https://github.com/mui/mui-x/pull/14142 for pointers on how to.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
release v3.0.0-alpha.0 last night. Pretty safe to use as its mostly just a peerDep bump for the mui packages. I might ship it as stable as soon as this weekend or Monday.

**Comment by KevinVandy** [comment]
MRT V3 with support for Material UI V6 was released
