### ISSUE TITLE
Vitest stopped working after v3

### ISSUE THREAD

**Issue by adiliqbl** [KevinVandy/material-react-table#1236]
### material-react-table version

3.0.0

### react & react-dom versions

v18.3.1

### Describe the bug and the steps to reproduce it

Hi. Thank you for releasing the v3. After migrating successfully, I am getting this error when running Vitest but it works great in browser. It used to work great before the upgrade.

Any idea on what's going on here. ? I would really appreciate the help. Thanks

```
SyntaxError: Cannot use import statement outside a module

../node_modules/@mui/material/Unstable_TrapFocus/FocusTrap.js:4
import * as React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1279:20)
    at Module._compile (node:internal/modules/cjs/loader:1331:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (../node_modules/material-react-table/dist/index.js:57:17)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)

Module /node_modules/@mui/material/Unstable_TrapFocus/FocusTrap.js:4 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "@mui/material" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.
```

### Minimal, Reproducible Example - (Optional, but Recommended)

Will try to replicate it elsewhere. Meanwhile, I only importing these from material-react-table:

```
import {
	MaterialReactTable,
	MRT_ExpandAllButton,
	MRT_ExpandButton,
	MRT_ShowHideColumnsButton,
	MRT_ToggleFiltersButton,
	MRT_ToggleFullScreenButton,
	MRT_ToggleGlobalFilterButton
} from 'material-react-table';
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Hmmm, wish someone had caught this earlier. Guess MUI is not exporting their new focus trap component correctly

**Comment by KevinVandy** [comment]
try v3.0.1

**Comment by bahadryalcn** [comment]
Thanks so much for the quick fix. I can confirm the issue is resolved.

**Comment by adiliqbl** [comment]
Thanks a lot for the quick fix, the issue is now resolved. Unblocked me on migration process. 👍 

Should this issue be raised with [material-ui](https://github.com/mui/material-ui) since it's caused by v6?
