### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading `type`)

### ISSUE THREAD

**Issue by arung-agamani** [KevinVandy/material-react-table#1267]
### material-react-table version

v3.0.1

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Got the following error when installing MRT in new project.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at decomposeColor (chunk-KUSDY7BL.js?v=dc0b842a:2321:14)
    at lighten (chunk-KUSDY7BL.js?v=dc0b842a:2459:12)
    at getMRTTheme (material-react-table.js?t=1728915685365&v=dc0b842a:52677:260)
    at material-react-table.js?t=1728915685365&v=dc0b842a:53182:47
    at mountMemo (chunk-NBPPSPXM.js?v=dc0b842a:12817:27)
    at Object.useMemo (chunk-NBPPSPXM.js?v=dc0b842a:13141:24)
    at useMemo (chunk-WZ4PHDOT.js?v=dc0b842a:1094:29)
    at useMRT_TableOptions (material-react-table.js?t=1728915685365&v=dc0b842a:53182:40)
    at useMaterialReactTable (material-react-table.js?t=1728915685365&v=dc0b842a:53510:68)
```

My project uses Vite (v5.2.0) and PNPM (v.8.1.0)

### Minimal, Reproducible Example - (Optional, but Recommended)

Considering this is fresh install, my setup is only a simple setup for setting MRT skeleton first, but it failed.
```tsx
import {
    MaterialReactTable,
    useMaterialReactTable,
} from "material-react-table";
import type { MRT_ColumnDef } from "material-react-table";
import { useMemo } from "react";

type LostItems = {
    id: number;
    name: string;
    description: string;
};

const data: LostItems[] = [
    {
        id: 1,
        name: "Phone",
        description: "Lost phone in the park",
    },
];

function LostItemsPage() {
    const columns = useMemo<MRT_ColumnDef<LostItems>[]>(
        () => [
            {
                header: "Name",
                accessorKey: "name",
            },
            {
                header: "Description",
                accessorKey: "description",
            },
        ],
        []
    );

    const table = useMaterialReactTable({
        columns,
        data,
    });

    return (
        <div>
            <MaterialReactTable table={table} />
        </div>
    );
}

export default LostItemsPage;

```
This snippet should be reproducible in any react project.

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Follow the install instructions

**Comment by arung-agamani** [comment]
Found the problem.
As I'm also using Joy UI from material `@mui/joy`, apparently the theme setup is conflicting with those that uses MUI components.
After following [this guide](https://mui.com/joy-ui/integrations/material-ui/), it resolved the problem

Closing this issue as the described problem above is solved.
Will probably make MR to add notes on the docs just to be cautious when working with other UI libraries that uses/shares the same theme system with MUI
