### ISSUE TITLE
Row selection causes the entire table to re-render

### ISSUE THREAD

**Issue by LICF01** [KevinVandy/material-react-table#1281]
### material-react-table version

2.12.1

### react & react-dom versions

18.3.1

### Describe the bug and the steps to reproduce it

Hi there!, thanks for the amazing work with the table. Is there a way to prevent the entire table from re-rendering on row selection?, I'm saving the row ID inside a zustand store if that detail is important, thought that my implementation was bad but noticed that the [example](https://www.material-react-table.com/docs/guides/row-selection#manual-row-selection-without-checkboxes), has the same behavior, is ok for a default table, but it starts to lag more and more depending on how much customizations are being done for the rows and cells.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/guides/row-selection#manual-row-selection-without-checkboxes

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
No

**Comment by KevinVandy** [comment]
This is just how the state management of TanStack Table works. In the future, TanStack Table may move to signal based state/rendering.
