### ISSUE TITLE
The `manualGrouping` doesn't work

### ISSUE THREAD

**Issue by rohmanhm** [KevinVandy/material-react-table#129]
### material-react-table version

v1.2.0

### Describe the bug and the steps to reproduce it

When enable manual grouping seems to be doesn't work.

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

Here's the codesandbox:
https://codesandbox.io/s/mrt-manual-grouping-issue-r8r5cn?file=/src/TS.tsx

Just toggle the commented field `manualGrouping`.

### With `manualGrouping` true
<img width="924" alt="Rohmanshot 2022-09-29 at 14 14 11@2x" src="https://user-images.githubusercontent.com/7524911/192964779-b63b721b-9c93-4fd3-8e20-95c9771e7176.png">

### With `manualGrouping` false
<img width="1173" alt="Rohmanshot 2022-09-29 at 14 14 55@2x" src="https://user-images.githubusercontent.com/7524911/192964936-0b585aed-ec9d-4af2-aa82-252d6b5bb2a6.png">

### Do you intend to try to help solve this bug with your own PR?

No, because I don't have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
In what way are you trying to use the manualGrouping prop? How are you then grouping you're data manually? The `manualGrouping` is supposed to turn off the built-in grouping functions, so this is working as intended.

From the TanStack docs:

> Enables manual grouping. If this option is set to `true`, the table will not automatically group rows using getGroupedRowModel() and instead will expect you to manually group the rows before passing them to the table. This is useful if you are doing server-side grouping and aggregation.

**Comment by rohmanhm** [comment]
Hi @KevinVandy, Sorry I'm new to react-table.
I've found that the manual grouping is quite difficult to implement.
Do you have any example of that?

I've found an example from react-table documentation regarding grouping but it doesn't give me any idea how I can implement it into the material-react-table.

**Comment by vinit-poojary** [comment]
Hello, @rohmanhm , have you successfully addressed the issue of manual grouping in Material-UI's React Table? I've been searching for documentation on this in Tanstack's resources and the Material React Table (MRT) library, but haven't found any.

@KevinVandy , would you be able to provide an example of how to implement manual grouping when making API calls with pagination?
