### ISSUE TITLE
Cannot access pagination styling

### ISSUE THREAD

**Issue by markedwards** [KevinVandy/material-react-table#1291]
### material-react-table version

v3.0.1

### react & react-dom versions

v18.3.1

### Describe the bug and the steps to reproduce it

I would like to make adjustments to the pagination styling (for instance font sizes), but setting `muiPaginationProps.sx` does not seem to have any effect.

### Minimal, Reproducible Example - (Optional, but Recommended)

Can add if necessary.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by MylesWardell** [comment]
Had the same question, looked at the source code. Looks like pagination is part of `muiBottomToolbarProps`. Which you can restyle their using SX.

In saying that the access is limited with no unique classNames on areas that you would want to restyle. I would appreciate more classNames here.

**Comment by markedwards** [comment]
It's super hacky to style the pagination, this really needs to be improved.  It should be addressable via the MUI theme.

**Comment by markedwards** [comment]
I ended up with:
```typescript
muiBottomToolbarProps: {
  sx: {
    minHeight: 45,
    ".MuiTablePagination-root": {
      height: 45,
      py: 0,
      ".MuiInputLabel-root, .MuiTypography-root": {
        fontSize: 14,
      },
    },
  },
},
```

**Comment by FutureKode** [comment]
I want to put the pagination on the left side, is there an easy way to do that?

**Comment by KevinVandy** [comment]
> I want to put the pagination on the left side, is there an easy way to do that?

I think that there are plenty of examples showing you how to import MRT sub-components and put them where you want. Or how to just pass in custom flex order styles. https://www.material-react-table.com/docs/examples/custom-headless
