### ISSUE TITLE
DropDown goes under next row

### ISSUE THREAD

**Issue by murali6441** [KevinVandy/material-react-table#1300]
### material-react-table version

2.13.0

### react & react-dom versions

17.0

### Describe the bug and the steps to reproduce it

1. add a group data 
2. one column containing buttons by clicking the button dropdown should open.
3. The dropdown items are going under the next row

### Minimal, Reproducible Example - (Optional, but Recommended)

1. Render a popper component. 
2. make sure to open the dropdown

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Use a portal or set the zIndex higher

**Comment by murali6441** [comment]
For Popper Component zindex is not working.
