### ISSUE TITLE
defaultColumn > muiTableBodyCellProps not working

### ISSUE THREAD

**Issue by PeterSchulzNL** [KevinVandy/material-react-table#1318]
### material-react-table version

v3.0.1

### react & react-dom versions

v18.3.1

### Describe the bug and the steps to reproduce it

This worked in V2

muiTableBodyCellProps: (
	(tableOptions) => ({
		sx: {
			color: getColor(tableOptions.row.id, tableOptions.cell.column.id),
			backgroundColor: getBackgroundColor(tableOptions.row.id, tableOptions.cell.column.id),
		},
	})
),

Followed the V3 recommendations to move it to defaultColumn, with no luck.

### Minimal, Reproducible Example - (Optional, but Recommended)

This does not work in V3

defaultColumn: {
	muiTableBodyCellProps: (
		(tableOptions) => ({
			sx: {
				color: getColor(tableOptions.row.id, tableOptions.cell.column.id),
				backgroundColor: getBackgroundColor(tableOptions.row.id, tableOptions.cell.column.id),
			},
		})
	),
},

It doesn't give any errors, but it doesn't give any results as well.

BTW, migration from V2 to V3 was super easy. The V2 code mentioned above continues to work normally.

Keep up the good work! 👍

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by evitalv** [comment]
This is the same bug, I think: https://github.com/KevinVandy/material-react-table/issues/1295

**Comment by KevinVandy** [comment]
I'm considering undepracating these since people were expecting them to merge values in the same way.

**Comment by KevinVandy** [comment]
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/90dfbff6-5044-4d80-a3d2-c352a23af754" />
