### ISSUE TITLE
Easy way to remember last selected filters 😢

### ISSUE THREAD

**Issue by drmax24** [KevinVandy/material-react-table#1319]
### material-react-table version

2.13.3

### react & react-dom versions

17

### Describe the bug and the steps to reproduce it

I've used MRT in relatively advanced ways.
I wrote a code for my MRT to remember configuration for each table. But my implementation is very ugly.
So the requirement is to remember filters, visible columns, column order, page number + couple more things like that.
I use a combination of Zustand + Local storage for this at the moment.
But I would rank my code to be 3/10 elegance-wise. Can you give a best practice example?

### Minimal, Reproducible Example - (Optional, but Recommended)

See this. onColumnFiltersChange, onSortingChange

```
    const table = useDataGridWithServerData({
        ...getDefaultUserMRTOptions(router),
        columns,
        data: usersList,
        rowCount: totalCount,
        onColumnFiltersChange: (updater: MRT_Updater<any>) => {
            setColumnFilters(
                updater instanceof Function
                    ? updater(state.columnFilters)
                    : updater
            );
        },
        onSortingChange: (updater: MRT_Updater<MRT_SortingState>) => {
            setSorting(
                updater instanceof Function
                    ? updater(state.sorting as MRT_SortingState)
                    : updater
            );
        },
        onPaginationChange: (updater: MRT_Updater<MRT_PaginationState>) => {
            setPagination(
                updater instanceof Function
                    ? updater(state.pagination!)
                    : updater
            );
        },
        onColumnVisibilityChange: (
            updater: MRT_Updater<MRT_VisibilityState>
        ) => {
            setColumnVisibility(
                updater instanceof Function
                    ? updater(state.columnVisibility as MRT_VisibilityState)
                    : updater
            );
        },
```

Above code invokes these functions. Of my zustand store. Too much boilerplate... Help plz!
```
interface TableStateType<T extends MRT_RowData> extends TableStateProps<T> {
    setSorting: (sorting: MRT_SortingState) => void;
    setColumnFilters: (columnFilters: MRT_ColumnFiltersState) => void;
    setPagination: (pagination: MRT_PaginationState) => void;
    setColumnVisibility: (columnVisibility: MRT_VisibilityState) => void;
    setColumnPinning: (columnVisibility: MRT_ColumnPinningState) => void;
    setShowColumnFilters: (showColumnFilters: any) => void;
}

....

        setColumnFilters: (columnFilters: MRT_ColumnFiltersState) => {
            const newState = {
                ...getState().state,
                columnFilters,
            };
            saveStateToLocalStorage(newState, tableId);
            set({ state: newState });
        },

        setPagination: (pagination: MRT_PaginationState) => {
            const newState = {
                ...getState().state,
                pagination,
            };
            saveStateToLocalStorage(newState, tableId);
            set({ state: newState });
        },
```

i can not just do onColumnFiltersChange: setColumnFilters
because interfaces do not match. 
But may be there is a better, completely different way to achieve my goal:
To remember the user-set table configuration after I leave the table page

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Use any kind of usePrevious hook or logic that is floating around out there.

The above code is pretty much how I'd persist state to zustand/local storage.

**Comment by drmax24** [comment]
> Use any kind of usePrevious hook or logic that is floating around out there.

I need to restore the state after the window was closed.
 
> The above code is pretty much how I'd persist state to zustand/local storage.
But if i just used the state i mrt config could be much more simple.
May be signature of the MRT can be changed so it can be compatible with the zustand

i would like to have just
onPaginationChange: setPagination

where setPagination is the hook i expose from zustand

**Comment by drmax24** [comment]
@KevinVandy KevinVandy
