### ISSUE TITLE
Values are reset when changing column filter mode for multi-select

### ISSUE THREAD

**Issue by jmraz98** [KevinVandy/material-react-table#1325]
### material-react-table version

2.13.0 (but observed on 3.0.2 as well)

### react & react-dom versions

18.3.1

### Describe the bug and the steps to reproduce it

For columns with multi-select option and column filter modes enabled when switching between filter modes filter values are lost. For all other options. (date, text, etc) it works fine

 (Is it possible to keep them in case that is intentional ?)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-wkrdvqk6?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

https://github.com/user-attachments/assets/e00a33ba-7a6e-44ee-b9af-fa38eb0ddeb9

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
In this particular case, it is by design if switching between filter modes of different types. Like here, switching between array filter modes vs basic comparisons.
