### ISSUE TITLE
Dependency conflict date-fns version 4.x in @mui/x-date-pickers and material-react-table

### ISSUE THREAD

**Issue by GabbereX** [KevinVandy/material-react-table#1345]
### material-react-table version

v3.0.3

### react & react-dom versions

18.3.1/18.3.1

### Describe the bug and the steps to reproduce it

While using material-react-table@3.0.3 (which depends on @mui/x-date-pickers@7.16.0), I encountered a compatibility issue when installing date-fns version 4.x.

The peerDependencies of @mui/x-date-pickers specify the following version range for date-fns:
^2.25.0 || ^3.2.0.

When I try to install date-fns@4.x, I receive the following warning:

```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: project@0.0.0
npm warn Found: date-fns@3.6.0
npm warn node_modules/date-fns
npm warn   peerOptional date-fns@"^2.25.0 || ^3.2.0" from @mui/x-date-pickers@7.16.0
npm warn   node_modules/@mui/x-date-pickers
npm warn     peer @mui/x-date-pickers@">=7.15" from material-react-table@3.0.3
npm warn     node_modules/material-react-table
npm warn   1 more (the root project)
npm warn
npm warn Could not resolve dependency:
npm warn peerOptional date-fns@"^2.25.0 || ^3.2.0" from @mui/x-date-pickers@7.16.0
npm warn node_modules/@mui/x-date-pickers
npm warn   peer @mui/x-date-pickers@">=7.15" from material-react-table@3.0.3
npm warn   node_modules/material-react-table
```

However, everything works correctly with date-fns version 3.6.0.

Questions:

Is there any plan to add support for date-fns version 4.x in upcoming releases?
What are the recommended steps to resolve this warning?

### Minimal, Reproducible Example - (Optional, but Recommended)

Current version date-fns 3.6.0 -> npm i  date-fns@latest

### Do you intend to try to help solve this bug with your own PR?

Yes, I am also opening a PR that solves the problem along side this issue

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Looks like all you got to do is upgrade to Mui X date-pickers v7.18.0+. See [here](https://github.com/mui/mui-x/releases/tag/v7.18.0). I recommend upgrading mui packages all together at the same time to their latest version.

MRT does not depend on an exact `@mui/x-date-pickers` version. It's a peer dep. You just need to keep it in sync with the date-fns package in your own package.json

**Comment by GabbereX** [comment]
Thanks for the answer! However, the problem has not been solved. I have latest version installed @mui/material 6.3.0 and material-react-table 3.1.0. When trying to migrate date-fns 3.6.0 -> 4.1.0 same warning as before. [I tried to contact MUI directly issue](https://github.com/mui/mui-x/issues/15987), they sent me to read the documentation. 
I don't have a package @mui/x-date-pickers installed directly on project. Warning refers to your library: 

> Found: date-fns@3.6.0
> npm warn node_modules/date-fns
> npm warn   peerOptional date-fns@"^2.25.0 || ^3.2.0" from @mui/x-date-pickers@7.16.0
> npm warn   node_modules/@mui/x-date-pickers
> npm warn     peer @mui/x-date-pickers@">=7.15" from material-react-table@3.1.0
> npm warn     node_modules/material-react-table

**Comment by KevinVandy** [comment]
If you don't have the mui x date pickers installed, then MRT should error out and not work at all. It has been a required peer dependency since v2.

**Comment by GabbereX** [comment]
> If you don't have the mui x date pickers installed, then MRT should error out and not work at all. It has been a required peer dependency since v2.

Meaning I need to add to project dependency @mui/x-date-pickers ?

**Comment by KevinVandy** [comment]
Yes, please read the install instructions 
https://www.material-react-table.com/docs/getting-started/install

**Comment by GabbereX** [comment]
> Yes, please read the install instructions https://www.material-react-table.com/docs/getting-started/install

Thank you very much) Please forgive me, I missed this moment.
