### ISSUE TITLE
Docs - Pin (Freeze) Columns By Default 

### ISSUE THREAD

**Issue by mightym** [KevinVandy/material-react-table#142]
### material-react-table version

v1.2.6

### Describe the bug and the steps to reproduce it

Not sure if this is a legacy feature/state. But I can't find any type/property for `pinning` and I wonder if the docs are outdated. 
https://www.material-react-table.com/docs/guides/column-pinning#pin-(freeze)-columns-by-default

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://www.material-react-table.com/docs/guides/column-pinning#pin-(freeze)-columns-by-default

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
It looks like that one code snippet is missing `enablePinning` in that example, but what do you mean missing? The feature appears to be functional

**Comment by KevinVandy** [comment]
and just saw it should be called `columnPinning` in that snippet too. Looks like a bunch of typos

**Comment by KevinVandy** [comment]
currently deploying a fix
