### ISSUE TITLE
Columns not in columns prop at first render are pushed to end of table

### ISSUE THREAD

**Issue by PeretEtienne** [KevinVandy/material-react-table#143]
### material-react-table version

1.2.6

### Describe the bug and the steps to reproduce it

If the array passed in "colums" props have more columns than previously, added columns are pushed at the end of the table

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://codesandbox.io/s/thirsty-bohr-2y5wom?file=/src/App.js

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
That will happen, because the column order is managed internally based on the initial column order.

To fix, you will need to manage the `columnOrder` state yourself

See [this guide in the docs](https://www.material-react-table.com/docs/guides/column-ordering-dnd#change-the-default-column-order)

Though you will probably need to pass it as fully managed `state`, rather than `initialState`

**Comment by KevinVandy** [comment]
Code sandbox showing how you can fix it: 
https://codesandbox.io/s/hopeful-danilo-m3gy29

```jsx
export default function App() {
  const [condition, setCondition] = useState(false);

  const cols = useMemo(
    () =>
      [
        {
          header: "Name",
          accessorKey: "name"
        },
        condition && {
          header: "Address",
          accessorKey: "address"
        },
        {
          header: "Lastname",
          accessorKey: "lastname"
        }
      ].filter(Boolean),
    [condition]
  );

  const columnOrder = useMemo(() => cols.map((col) => col.accessorKey), [cols]);

  return (
    <>
      <button onClick={() => setCondition(!condition)}>Toggle condition</button>
      <MRTable columns={cols} data={data} state={{ columnOrder }} />
    </>
  );
}
```
