### ISSUE TITLE
Allow "auto" for size (NaN error)

### ISSUE THREAD

**Issue by Tekpakma** [KevinVandy/material-react-table#145]
### material-react-table version

1.2.7

### Describe the bug and the steps to reproduce it

I use defaultColumn={{ size: "auto" }} for my Table, which is a working option to fixate some columns, but probably since you defined size as type Number, produces a Console Error: 

Warning: `NaN` is an invalid value for the `width` css style property. 

(Size gets used for Tanstack Table width.)

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

Set defaultColumn={{ size: "auto" }} and size a column with a simple size.

Check https://github.com/TanStack/table/discussions/3192 for reference.

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Just leave size undefined if you want the default size. The width number is used for calculations internally if provided. That is why it is required as a number type.
