### ISSUE TITLE
fix RTL issue with MUI Pagination Back and Left Icons

### ISSUE THREAD

**Issue by mm0hammadi** [KevinVandy/material-react-table#149]
### material-react-table version

 "material-react-table": "1.2.8"

### Describe the bug and the steps to reproduce it

hi ,

When using the table in persian  lang(RTL theme) , the  arrow icons are displayed in reverse

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

fix icons in RTL mode

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by mm0hammadi** [comment]
![This is an image](https://i.postimg.cc/NM7Thcn3/Screenshot-from-2022-10-11-15-24-31.png)

**Comment by mm0hammadi** [comment]
yes , i did ,localization is okay .but i want to change  Arrow Right Icon and Arrow Left Icon  in pagination next and back page ? 
How can  do it ?

**Comment by KevinVandy** [comment]
@mm0hammadi Would you be interested in contributing your persian lang locale translations? I'd like to debug this, but also we can add Persian as a built-in language for this library.

**Comment by KevinVandy** [comment]
@mm0hammadi If you ever have time and see this, would you be able to tell me how a right to left table should look like?

On my docs site, it looks like this

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/28243511/200184079-9fdfa878-921f-4b97-8cde-366b566e17b0.png">

But would you expect the columns to be in the opposite direction? Are the headers and their buttons supposed to be reversed?

I can eventually make all these fixes in the library.

**Comment by mm0hammadi** [comment]
**thats okay but there are some style issue :**
- The placeholder text must be center or right.
- generally, the texts should be from right to left, for example, the text of columns  ,headers and rows and the text of filters.
- The actions column can be on the right side.
- I can change the  of all icons except pagination icons.i could not do it .

thank you

**Comment by mm0hammadi** [comment]
![Screenshot from 2022-11-07 10-06-01](https://user-images.githubusercontent.com/48970605/200243149-567bd6d8-78e0-4374-aae6-c9016f12f8f2.png)

**Comment by KevinVandy** [comment]
> ![Screenshot from 2022-11-07 10-06-01](https://user-images.githubusercontent.com/48970605/200243149-567bd6d8-78e0-4374-aae6-c9016f12f8f2.png)

Did you add in your own styles to accomplish that? Or did the MaterialReactTable just work like that in your app?

**Comment by KevinVandy** [comment]
@mm0hammadi  Did you add in your own styles to accomplish that? Or did the MaterialReactTable just work like that in your app?

**Comment by mm0hammadi** [comment]
yes, i added some style like this :

```
    muiTableContainerProps={{
          sx: {
            backgroundColor: background,
            borderRadius: '15px'
          }
        }}
        muiBottomToolbarProps={{
          sx: {
            height: '50px',
            backgroundColor: background,
            borderRadius: '15px'
          }
        }}
```

**Comment by KevinVandy** [comment]
@mm0hammadi I guess I meant to ask whether or not you were adding in `flex-reverse` on your own or not to make everything right to left like in your screenshots, or if that was happening automatically for you.

**Comment by mm0hammadi** [comment]
no ,it was happening automatically for me

**Comment by KevinVandy** [comment]
This is a solution:

```jsx
<MaterialReactTable
    columns={columns}
    data={data}
    muiTablePaginationProps={{
      backIconButtonProps: {
        style: { transform: 'rotate(180deg)' },
      },
      nextIconButtonProps: {
        style: { transform: 'rotate(180deg)' },
      },
    }}
  />
```

It may get added to the library internally, though this seems more to be a bug with Mui's own TablePagination component.
