### ISSUE TITLE
Initial column pinning on header group does not work

### ISSUE THREAD

**Issue by PeretEtienne** [KevinVandy/material-react-table#154]
### material-react-table version

1.2.9

### Describe the bug and the steps to reproduce it

Pinning header group work once the table has rendered from pinning button but not if set from initialState.columnPinning

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://codesandbox.io/s/thirsty-orla-zygm3n?file=/src/App.js

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
It is actually working as intended. Parent rows cannot be pinned by their own `id`. Instead, when they get pinned, their child columns all get pinned by their ids. See the modified example here and pay attention to the console logs https://codesandbox.io/s/nostalgic-neumann-4xxmp1?file=/src/App.js

**Comment by PeretEtienne** [comment]
I suspected this behavior but wasn't sure. Thx again 👍
