### ISSUE TITLE
onColumnOrder not working properly

### ISSUE THREAD

**Issue by carvalhodanielg** [KevinVandy/material-react-table#158]
### material-react-table version

v1.2.9

### Describe the bug and the steps to reproduce it

Hello! First off all, congrats on the amazing project, it's impressive!

My issue is abou a bug, or a bad use of my part. I'm trying to use the prop onColumnOrder, Im doing it the exact same way it appears in the docs, but when I reorder the columns, its state doesn't change.

I aways get [undefined] or [null] values.

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

` onColumnOrderChange={setColumnOrder}`
` state={{
        columnOrder: columnOrder,
      }}`

`  const [columnOrder, setColumnOrder] = React.useState<ColumnOrderState>([ ]);`

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by carvalhodanielg** [comment]
An examplo of how Im doing it on codesandbox

https://codesandbox.io/s/strange-elbakyan-b2qf2w?file=/src/TS.tsx

**Comment by carvalhodanielg** [comment]
Another question, is it possible to style the show/hide columns menu? I need to change the size of text and icons, but I couldn't find the way to do it.

Thanks again!!!

![image](https://user-images.githubusercontent.com/100332887/196794593-9db27de6-91ae-4b70-8b07-4cb656dccbf5.png)

**Comment by KevinVandy** [comment]
Sorry, you ran into that. I need to document this somewhere. When you manage the column order state yourself, you also need to initialize the columnOrder state correctly. See it working correctly here: https://codesandbox.io/s/blissful-pascal-6rb24y?file=/src/TS.tsx

It can simply be solved by creating your state like this:

```ts
const [columnOrder, setColumnOrder] = React.useState<ColumnOrderState>(
    columns.map((c) => c.accessorKey as string)
  );
```

**Comment by KevinVandy** [comment]
If you start managing the columnOrder state manually, those positionColulmn props become ineffective.

If you see the [column ordering guide docs](https://www.material-react-table.com/docs/guides/column-ordering-dnd#change-the-default-column-order), you'll see a section dedicated to setting the column order exactly, including with the display column ids such as `"mrt-expand-row"` column. Also see the [display column docs](https://www.material-react-table.com/docs/guides/display-columns) to learn more about the auto generated columns.

I suspect you actually need something like this

```ts
const [columnOrder, setColumnOrder] = React.useState<ColumnOrderState>(
  [ 'mrt-row-expand', ...columns.map((c) => c.accessorKey as string) ]
);
```

**Comment by carvalhodanielg** [comment]
Thank you very very much! It worked for me, I remember seeing this somewhere but wasn't finding it. 

Again, thank you very much. Amazing work with the library!!
