### ISSUE TITLE
EditTextField enable in group row

### ISSUE THREAD

**Issue by charlie2610** [KevinVandy/material-react-table#164]
### material-react-table version

1.2.7

### Describe the bug and the steps to reproduce it

enableGrouping = true
enableEditing = true 
editingMode="table"

When I group a column that has editing disabled, the EditTextField appears in the column that has editing enabled, in the row that corresponds to grouping
[https://web.uds.edu.py/intranet/archivos/Material-React-table-issue.png](url) 
In the url is a print screen of the problem, in the 2 grouping row show the EditTextField 
Thanks..

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://codesandbox.io/s/nostalgic-payne-ucizp8?file=/src/App.js

### Screenshots or Videos (Optional)

![Material-React-table-issue](https://user-images.githubusercontent.com/73958154/197611030-1a70619e-a213-4d12-bdf6-6bd90813bebf.png)

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This will be fixed in the next release

**Comment by KevinVandy** [comment]
fixed in `v1.3.0`
