### ISSUE TITLE
Column resizing rendering performance

### ISSUE THREAD

**Issue by ArtemyB** [KevinVandy/material-react-table#168]
### material-react-table version

1.2.10

### Describe the bug and the steps to reproduce it

Rendering of the column's resize handle movement is visibly lagging. Reproducible even on a regular scenario, when `MaterialReactTable`'s `enableColumnResizing` prop is set to `true`.

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

Lags are observable even on [the official CodeSandbox-hosted sample](https://codesandbox.io/s/github/KevinVandy/material-react-table/tree/main/material-react-table-docs/examples/enable-column-resizing/sandbox?file=/src/TS.tsx) (with only 5 rows in it). It is not so visible right in the documentation site I suppose because of higher available computing power. However it seems to me this scenario is quite simple and ordinary usage to be so computationally-demanding.

### Screenshots or Videos (Optional)

Here is a demo GIF that was captured on the production build of the app: ![Lagging behavior demo-GIF](https://i.imgur.com/ugmZ1FM.gif)

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ArtemyB** [comment]
My guess, could the issue be caused by the `sx`-prop usage e.g. on the [`MRT_TableHeadCellResizeHandle` component](https://github.com/KevinVandy/material-react-table/blob/86b7838e268c329f8296631f1b0c7f0fbde9ea82/src/head/MRT_TableHeadCellResizeHandle.tsx)? As I understood from [the MUI doc](https://mui.com/system/getting-started/usage/#performance-tradeoffs) the sx-prop imposes some performance overhead, though the provided benchmark results doesn't seem dramatic.
However I'm not very experienced in JS/TS development and haven't looked into the `material-react-table`'s code closely enough yet to assume any other possible reasons of the problem.

> P.S.: By the way, big thanks for the library. In particular, for its detailed and intuitive API design with lots of customization capabilities and for the impressively informative documentation. 👍

**Comment by KevinVandy** [comment]
I've been looking at replacing the column widths styles with CSS specifically. Haven't got it working all the way yet, but hopefully we'll have something better down the line

**Comment by ArtemyB** [comment]
@KevinVandy that's good news anyway :) Have you achieved any signs of performance improvement? Asking even just out of curiosity -- to understand how much of performance impact MUI's sx-prop could do in practice. For example, the [TanStack column resizing example](https://tanstack.com/table/v8/docs/examples/react/column-sizing) column resizing works perfectly smooth.

**Comment by mjsantoni** [comment]
Hi! This seems to be happening to me as well. I think it happens when there's many columns like in the example provided by Artemy. I have my table set up with 18 columns, 10 rows with pagination and columnSizing state handled manually and I've been having the same problem.
It's also happening when I select rows (also done manually with rowSelection) because there's like some sort of delay between the click and the selection highlight.

**Comment by kuket15** [comment]
Hello and thanks for such a great library!
Just here to say I'm facing the same issue.
It seems like setting `enableColumnResizing` to `true` affects, in general, all the table rendering.
Filters animation, e.g. becomes quite laggy.

**Comment by KevinVandy** [comment]
@kuket15 @mjsantoni @ArtemyB  MRT v1.7.0 has released a bunch of new optimizations for the column resizing feature. CSS variables are now used and the table body is memoized during a column resize. I see noticeable improvements.

**Comment by ArtemyB** [comment]
@KevinVandy that's great, thank you 👍 Indeed it is working smoothly (very much better than before) in [the Storybook's example](https://www.material-react-table.dev/?path=/story/features-column-resizing-examples--column-resizing-disabled-some-columns) even with 50+ rows. It remains only to try it out in some project personally.
