### ISSUE TITLE
onPaginationChange does not include  column filter mode

### ISSUE THREAD

**Issue by mboujaha** [KevinVandy/material-react-table#169]
### material-react-table version

1.2.10

### Describe the bug and the steps to reproduce it

When calling the onColumnFiltersChange event,  the data you get back includes only the id and value.

In case the enableColumnFilterModes is enabled, the onColumnFiltersChange should also include the selected mode.

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

[Sandbox example](https://codesandbox.io/s/github/KevinVandy/material-react-table/tree/main/material-react-table-docs/examples/remote/sandbox?file=/src/TS.tsx)

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
No actually there is a separate `columnFilterFns` state just for that. Also see `onFilterFnsChange`, though I'm probably going to rename that to `onColumnFilterFnsChange` in v1.3 soon
