### ISSUE TITLE
[Sticky Header] The sticky header is not work

### ISSUE THREAD

**Issue by josecao** [KevinVandy/material-react-table#18]
### material-react-table version

0.18.1

### Describe the bug and the steps to reproduce it

The sticky header row was default. When i  set props

======
columns={cloneColumns} 
data={data} 
enableColumnOrdering 
enablePagination={false} 
enablePinning 
enableDensityToggle={false} 
initialState={{ density: 'compact', ...initialState }} 
enableColumnResizing 
enableColumnFilters 
enableToolbarBottom={false} 
enableGlobalFilter={false} 
state={{ isLoading: loading }} 
muiTableContainerProps={{ sx: { maxHeight: '600px' } }}
====

But it is not work

### Your Minimal, Reproducible Example (Sandbox or code snippets)

[Not exam](https://www.material-react-table.dev/?path=/docs/styling-sticky-header-examples--sticky-header-default)

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The Sticky Header feature used to be enabled by default, but now it is "opt in". 

The storybook stories have been fixed.

Pass the `enableStickyHeader` prop to enable it, along with the maxHeight in the muiTableContainerProps that you already have
