### ISSUE TITLE
Global Filter and column filter search both are not working  Debounce Error

### ISSUE THREAD

**Issue by KumarMridul** [KevinVandy/material-react-table#184]
### material-react-table version

1.3.2

### Describe the bug and the steps to reproduce it

When I am trying to search any input from the table in the search i am getting this warning and error.
And input are not filtered.

Console:
Warning:
 react-dom.development.js:88 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

Error:
MRT_GlobalFilterTextField.tsx:51 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at MRT_GlobalFilterTextField.tsx:51:1
    at later (debounce.js:8:1)

### Minimal, Reproducible Example - (Optional, but Recommended)

I simply copied one of the example from Material react table in my react application but all the features are working except
filter search.

https://codesandbox.io/s/github/KevinVandy/material-react-table/tree/main/material-react-table-docs/examples/enable-editing-cell/sandbox?file=/src/TS.tsx

### Screenshots or Videos (Optional)

![Uploading Screenshot 1944-08-13 at 3.57.20 PM.png…]()

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.
- [X] I have verified I am using the correct peer dependency versions for my version of material-react-table listed in the [installation instructions](https://www.material-react-table.com/docs/getting-started/install#installation).

**Comment by KevinVandy** [comment]
This error only pops up for those who are using a pre react and react dom 17 versions. You indicated that you followed the full install instructions, but double check that.

**Comment by KumarMridul** [comment]
Thanks @KevinVandy I had version 16. Working smoothly once upgraded to 17 version.
