### ISSUE TITLE
renderDetailPanel - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mightym** [KevinVandy/material-react-table#19]
### material-react-table version

v0.22.2

### Describe the bug and the steps to reproduce it

Whenever I add `renderDetailPanel={({ row }) => <div></div>}` to my table I'm getting a TS `Maximum call stack size exceeded` Error.  If I remove the property my table works perfect. 

### Your Minimal, Reproducible Example (Sandbox or code snippets)

Table: 

```
        <MaterialReactTable
          columns={columns}
          data={data?.results ?? []}
          // renderDetailPanel={({ row }) => <div></div>}
          rowCount={data?.count ?? 0}
          state={{
            isLoading,
            showAlertBanner: isError,
            showProgressBars: isFetching && isStale,
          }}
        />
```
Columns

```
  const columns = useMemo(
    () => [
      {
        accessorKey: 'id',
        header: 'ID',
      },
    ],
    []
  );
```

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Thanks for reporting and thanks for sponsoring!

I've tried to reproduce this in codesandbox and the project locally, but cannot find any error. 

https://codesandbox.io/s/sleepy-robinson-f17msg?file=/src/TS.tsx

What version of TypeScript does your project have installed?

In the meantime, found and fixed 1 small bug with renderDetailPanel where it was not showing the expand buttons column unless `enableExpanding` was passed. Now that's not needed in v0.23.1.

**Comment by mightym** [comment]
`typescript": "^4.7.4",`
and `"react": "^18.2.0",`

Also just in case, this is my typescript config:

```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "strict": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "CommonJS",
    "target": "ES6",
    "jsx": "react",
    "baseUrl": "./",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "types": [
      "node",
      "jest",
      "@testing-library/jest-dom",
      "cypress",

    ],
    "incremental": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true
  },
  "exclude": ["node_modules"],
  "ts-node": {
    "compilerOptions": {
      "module": "CommonJS"
    }
  }
}
```
Its really strange, I'm running/developing this project now for months. And never encountered such a weird issue. 
Anyway, don't bother yourself too much, I will try a few other things to figure out the issue.

**Comment by mightym** [comment]
Tried different TS versions, no luck so far. But I figured out that this basically happens on every of these properties:
```
renderDetailPanel
renderRowActionMenuItems
renderRowActions
renderToolbarBottomCustomActions
renderToolbarInternalActions
renderToolbarTopCustomActions
```

**Comment by KevinVandy** [comment]
> Tried different TS versions, no luck so far. But I figured out that this basically happens on every of these properties:
> ```
> renderDetailPanel
> renderRowActionMenuItems
> renderRowActions
> renderToolbarBottomCustomActions
> renderToolbarInternalActions
> renderToolbarTopCustomActions
> ```

Does it also happen for custom Cell or Header renders in column defs?

**Comment by mightym** [comment]
No that works perfect. I already tried some complex custom Cell and Header renders.

**Comment by KevinVandy** [comment]
> No that works perfect. I already tried some complex custom Cell and Header renders.

Would you be able to post some larger code snippets? 

I know there are some grouping and expanding bugs in TanStack Table V8.2 itself that can cause an infinite loop currently, and we're looking into a fix for that soon. Trying to see which features you have enabled.

The `render` methods causing this error confuses me, but I'll keep trying to reproduce.

**Comment by KevinVandy** [comment]
Anyone else running into this? I still never have. May close soon as stale.

Was it an actual infinite loop crashing your whole app, or just a TypeScript max call stack size exceeded?

**Comment by mightym** [comment]
Sorry that I didn't reply ... totally missed it. 

I can reduce it with a bare create react app via:

```
 <MaterialReactTable
          columns={columns}
          data={data?.results ?? []}
          renderDetailPanel={({ row }) => <div></div>}
          rowCount={data?.count ?? 0}
          state={{
            isLoading,
            showAlertBanner: isError,
            showProgressBars: isFetching && isStale,
          }}
        />
```

And yes its a `TypeScript max call stack size exceeded`. 

But sure, close the ticket. Not sure how I can help :-/. We anyway started in between building our own TanStack Table v8 + MUI table component. No criticism, you guys are doing an awesome job on this project. <3

**Comment by KevinVandy** [comment]
Won't close as now it sounds like I can make a reproducible example. Will try that tonight. Thank you!

**Comment by mightym** [comment]
@KevinVandy I just upgraded to your latest version and it works!!! (I swear my code is still the same! :)  )

**Comment by mightym** [comment]
Closing this. Thanks a lot again for your time and help @KevinVandy
