### ISSUE TITLE
Default sort function is case-sensitive

### ISSUE THREAD

**Issue by neilbags** [KevinVandy/material-react-table#193]
### material-react-table version

v1.3.4

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

The documentation says:
"By default, Material React Table will use an alphanumeric sorting function for all columns." 

But it appears to be using one of the case-sensitive algorithms. I've forked the Basic Example to illustrate this. All I have changed is 'Joe' to 'joe' and set the initial state to sort by name.firstName:
https://codesandbox.io/s/jovial-bush-th8o4h?file=/src/TS.tsx

Ref:
https://www.material-react-table.com/docs/guides/sorting#sorting-functions

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/jovial-bush-th8o4h?file=/src/TS.tsx

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm pretty sure this is intentional by TanStack Table. If you need a different sorting behavior, you can specify a different `sortingFn` per column, or in the `defaultColumn` prop. See the built-in sortingFn options [here](https://tanstack.com/table/v8/docs/api/features/sorting#sorting-functions)

**Comment by neilbags** [comment]
Thanks, yes I am aware of how to change the sorting function. I raised the issue because the documentation didn't appear to match the behaviour. If the behaviours is intentional do you want a PR to update the docs?

**Comment by KevinVandy** [comment]
> Thanks, yes I am aware of how to change the sorting function. I raised the issue because the documentation didn't appear to match the behaviour. If the behaviour is intentional do you want a PR to update the docs?

Sure. I didn't think that saying alphanumeric implied case sensitivity or not. What should it say?

**Comment by neilbags** [comment]
In the docs, because the word 'alphanumeric' is in a code tag, I think the reader would assume you are referring to the alphanumeric sorting function from Tanstack, rather than just making a general statement about alphanumeric sorting.

 I think the docs should either say:
- By default, Material React Table will use a case-sensitive alphanumeric sorting function for all columns.
OR
- By default, Material React Table uses the alphanumericCaseSensitive sorting function for all columns.

I'm not sure which is correct because I haven't dug into the code to see whats actually happening
