### ISSUE TITLE
Custom filterFn breaks the tooltip

### ISSUE THREAD

**Issue by qwelol** [KevinVandy/material-react-table#201]
### material-react-table version

v1.3.9

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

If prop filterFn is function then filterType value in tooltip is undefined. 

### Minimal, Reproducible Example - (Optional, but Recommended)

This can be checked with an example from storybook: 
https://www.material-react-table.dev/?path=/docs/features-filtering-examples--custom-filter-fns#custom-filter-fns

### Screenshots or Videos (Optional)

![filter](https://user-images.githubusercontent.com/39767122/202139443-6c83b951-8d78-4c50-9b70-0279f6f7d7db.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You just need to provide a localization entry with the name of your custom filter like in the example in the official docs

https://www.material-react-table.com/docs/guides/column-filtering#customize-filter-modes-source-code

<img width="595" alt="image" src="https://user-images.githubusercontent.com/28243511/204104001-2f06004f-3df4-478a-bda1-f5be653e7bcf.png">
