### ISSUE TITLE
Horizontal and Vertical virtualization 

### ISSUE THREAD

**Issue by dianventer** [KevinVandy/material-react-table#210]
### material-react-table version

V1.3.9

### react & react-dom versions

v18.0.2

### Describe the bug and the steps to reproduce it

Setting the following virtualizer prop true make the vertical virtualization to work incorrectly:

horizontal: true

I understand what this means. I was just wondering if it's possible to have horizontal and vertical virtualization to be enabled simultaneously.

I am attempting to render a 183 Column by 80k Row table in a project.
The performance is however unusable.

How can both axis' virtualization be enabled simultaneously?

### Minimal, Reproducible Example - (Optional, but Recommended)

The code is described above.

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
MRT does not have column virtualization right now, but is being considered for v2 ( big refactor needed). I might recommend building your own data grid with TanStack Virtual and TanStack Table. Or AG Grid for that kind of table right now.

**Comment by KevinVandy** [comment]
I have started development on v2, which can be followed here on the [v2 branch](https://github.com/KevinVandy/material-react-table/tree/v2)

**Comment by dianventer** [comment]
Thanks! I will contribute to the branch. I also want to add a "Does not contain" filter and add null checks to the "Contains" filter as well.

**Comment by KevinVandy** [comment]
> Thanks! I will contribute to the branch. I also want to add a "Does not contain" filter and add null checks to the "Contains" filter as well.

@dianventer Most of that stuff can still go into v1 main branch. It's only stuff with a virtualization rewrite, div grid, and using React 18 concurrent mode features that cause breaking changes that I'm saving for a big v2 release
