### ISSUE TITLE
No loading animation when filter is set and data empty

### ISSUE THREAD

**Issue by BendixP** [KevinVandy/material-react-table#237]
### material-react-table version

1.3.16

### react & react-dom versions

18.0.20

### Describe the bug and the steps to reproduce it

The skeleton rows get filtered out. So there is no visible loading animation.

### Minimal, Reproducible Example - (Optional, but Recommended)

(https://stackblitz.com/edit/github-hncymy?file=src/TS.tsx)

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This will be fixed in v1.5.0.

https://www.material-react-table.dev/?path=/story/fixed-bugs-loading-data--nested-loading-data-with-initial-filter
