### ISSUE TITLE
Cancel button in row edit

### ISSUE THREAD

**Issue by Rizodu** [KevinVandy/material-react-table#24]
### material-react-table version

v0.26.2

### Describe the bug and the steps to reproduce it

In row edit mode, when cancelling the same row a second time, the "cancel" button acts as confirm

### Your Minimal, Reproducible Example (Sandbox or code snippets)

https://www.material-react-table.dev/?path=/story/features-editing-examples--editing-enabled-edit-mode-cell

### Screenshots or Videos (Optional)

https://user-images.githubusercontent.com/31573205/179561322-b5d33783-b600-4727-a4e5-8ae3570b2c84.mp4

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This ended up being such a simple fix. lol. Will be fixed in `0.35.0`

<img width="483" alt="image" src="https://user-images.githubusercontent.com/28243511/184278559-660952c3-2b44-4681-9b94-0eddc0b95d31.png">

**Comment by KevinVandy** [comment]
Should be fixed as of `v0.35.1`
