### ISSUE TITLE
Using a fixed size for a pinned column makes the pinned column unstable.

### ISSUE THREAD

**Issue by dnjsgur0629** [KevinVandy/material-react-table#240]
### material-react-table version

1.4.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

There's two issues.
It might be better to divide the issue, but I think it's relevant, so I'm writing it together.

##### 1. The size value affects `.Mui-TableHeadCell-Content`, not `.MuiTableCell-head`.
Each column is slightly wider because of `padding`, but the left value to pin the column is still synchronized with the `size` value.
So, when there are multiple pinned columns, the columns are unstable as much as the size of the `padding`.

##### 1. When the width of a column is widened by a feature such as `show filter`, the left value for pinning the column is not synchronized with the width.
The column has widened, but The left value keeps the same and the pinned columns are unstable more.

### Minimal, Reproducible Example - (Optional, but Recommended)

[![Edit MRT_pinned_column_issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mrt-pinned-column-issue-thlksw?fontsize=14&hidenavigation=1&theme=dark)

##### Case of 1
![mrt_unstabel_pin_columns](https://user-images.githubusercontent.com/65391273/206939216-061bf2c3-d673-4975-bbd3-1bd8321c3d3e.gif)
![image](https://user-images.githubusercontent.com/65391273/206662969-a204bd7f-446b-45b9-bb30-4c6bcdbde8d8.png)
![image](https://user-images.githubusercontent.com/65391273/206663022-cdaafc9a-0f4f-420c-8e37-7ecaf4557f3a.png)
![image](https://user-images.githubusercontent.com/65391273/206663306-ee7fe240-8d98-4c2f-9452-9ba0397d7106.png)

##### Case of 2
![mrt_unstabel_pin_columns_with_filter](https://user-images.githubusercontent.com/65391273/206939221-02c406d1-fc88-4a87-8b7e-577f52aaf2ed.gif)
![image](https://user-images.githubusercontent.com/65391273/206665236-1f514d45-1992-4747-8594-02a0b6733a09.png)
![image](https://user-images.githubusercontent.com/65391273/206665316-fef7cb18-71f0-453c-bbcd-40f7f01a4a09.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I don't have time to dig into it

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm not sure I'm following, as I don't see anywhere where the column is "unstable" (don't know what you mean by that). The columns shrinking as a user horizontally scrolls is supposed to be a "feature", not a bug. If you want the filter to be visible always, you can make the column wider with the `size` option, or you make the filter text field smaller with the `muiTableHeadCellFilterTextFieldProps` column option `sx.minWidth` value.

**Comment by dnjsgur0629** [comment]
@KevinVandy
I've added .gif to better explain the issue.
I pinned 3 columns: `No.`, `Name` and `FirstName`. Since these three columns are pinned, I think they should not move when scrolling horizontally. But if you look at the gif, you can see that the two columns except for No are moving when scroll.

**Comment by KevinVandy** [comment]
> @KevinVandy
> I've added .gif to better explain the issue.
> I pinned 3 columns: `No.`, `Name` and `FirstName`. Since these three columns are pinned, I think they should not move when scrolling horizontally. But if you look at the gif, you can see that the two columns except for No are moving when scroll.

So this is by design, but you could maybe get rid of the flex grow if you want by switching layout mode to grid and modifying the flex style to not grow.

**Comment by dnjsgur0629** [comment]
This may not seem like a issue when aligned to the left. But the problem becomes noticeable when centered or right-aligned.
Could you please take a look at the gif below?
![is_this_really_designed](https://user-images.githubusercontent.com/65391273/206970089-0a892ee9-c58d-435b-ba10-b450cbcda8f6.gif)
The `Name` column moves and covers both the header and data of the `No.` column.
Is this correct by design? In my opinion, as much as the `No.` column widens, the left of the `Name` column also increses, so the pinned columns should not move.
And in fact, in my real project (not codesandbox), the width of the table cell is made flexible by the method of #238, so I can't set `layoutMode` to `"grid"`

**Comment by dnjsgur0629** [comment]
In the following code snippet, the left and right values are determined, and even if the cell width changes later, the left and right value does not seem to be changed.
https://github.com/KevinVandy/material-react-table/blob/eaa4a3d49579397bed48679bab3a652788966e6f/packages/material-react-table/src/column.utils.ts#L228-L279
https://github.com/KevinVandy/material-react-table/blob/eaa4a3d49579397bed48679bab3a652788966e6f/packages/material-react-table/src/body/MRT_TableBodyCell.tsx#L171-L220

**Comment by KevinVandy** [comment]
@dnjsgur0629 There is now an easy way to turn off the column growing. I've added it into the docs https://www.material-react-table.com/docs/guides/column-resizing#enable-column-resizing-no-grow-demo

I think this will solve your issue you had here?
