### ISSUE TITLE
Filter string not showing if set programmatically when showColumnFilters=true

### ISSUE THREAD

**Issue by BendixP** [KevinVandy/material-react-table#243]
### material-react-table version

1.3.16

### react & react-dom versions

18.0.20

### Describe the bug and the steps to reproduce it

If showColumnFilter is true and I set a filter programmatically the string is not shown at first. Only if I close and open the filter row it appears. 

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-ikb5ar?file=src/TS.tsx

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is a known issue. My plan is to get rid of the separate state managed by the filter components themselves. 2 Problem with this is that there will no longer be any debouncing built in, and it will require React 18 concurrent mode features to keep a good rendering performance as the user types, which will bump up the requirements of this library.

If someone else has a better idea that does not require React 18, I'd like to hear it.

**Comment by KevinVandy** [comment]
@BendixP I think this should be fixed in v1.5.4
Created a storybook example to keep track of this too https://www.material-react-table.dev//?path=/story/features-filtering-examples--external-set-filter-value
