### ISSUE TITLE
Table rows all fall on "even" when renderDetailPanel is enabled

### ISSUE THREAD

**Issue by ryjogo** [KevinVandy/material-react-table#245]
### material-react-table version

1.4.0

### react & react-dom versions

17.0.1

### Describe the bug and the steps to reproduce it

Looks like the table rows are all on "even" when renderDetailPanel is enabled, this causes the "striped" setup to fail. 

### Minimal, Reproducible Example - (Optional, but Recommended)

```
        muiTableBodyProps={{
          sx: (theme) => ({
            '& tr:nth-of-type(odd)': {
              backgroundColor: "limegreen",
            },
          }),
        }}

```

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Yeah, that's just how the detail panel works. Nothing wrong with the lib. Try just styling every other odd row instead?

Try `'& tr:nth-child(4n+1)` or `'& tr:nth-child(4n+3)` instead

www.material-react-table.dev/?path=/story/styling-style-table-body-rows--style-custom-striped-rows-detail-panel

**Comment by ryjogo** [comment]
Yeah fair enough; i wasn't sure whether to open a bug or not - but now i did it :). thanks anyway, yes this is totally fine with a css fix! thank you.
