### ISSUE TITLE
filtering with method "contains" or "equals" Uncaught TypeError

### ISSUE THREAD

**Issue by ryjogo** [KevinVandy/material-react-table#251]
### material-react-table version

1.4.2

### react & react-dom versions

17.0.1

### Describe the bug and the steps to reproduce it

When i try and filter a column, and change the filter type to "contains" or "equals" then i get the following error. I think it could be because some of the data in this column is blank?

### Minimal, Reproducible Example - (Optional, but Recommended)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at Object.Oo [as filterFn] (filterFns.ts:25:32)
    at o (getFilteredRowModel.ts:101:59)
    at g (getFilteredRowModel.ts:96:68)
    at getFilteredRowModel.ts:90:60
    at Object._getFilteredRowModel (utils.ts?6c1d:158:16)
    at Object.getFilteredRowModel (Filters.ts:424:22)
    at Object.getPreGroupedRowModel (Grouping.ts:217:42)
    at getGroupedRowModel.ts:10:47
    at Object._getGroupedRowModel (utils.ts?6c1d:143:21)
    at Object.getGroupedRowModel (Grouping.ts:227:22)
    
```

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by ryjogo** [comment]
I have made sure that specific column is output on my datasource now, and i do not get the error - so it's definitely when the field is not available.

**Comment by KevinVandy** [comment]
This is pretty much a problem with TanStack Table itself where it does not like `null` values in data. This can be solved by having an `accessorFn` that defaults to an empty string or other default value instead of null.
