### ISSUE TITLE
Error with MUI version 5.11.0

### ISSUE THREAD

**Issue by nhatncb** [KevinVandy/material-react-table#257]
### material-react-table version

1.4.2

### react & react-dom versions

18

### Describe the bug and the steps to reproduce it

![image](https://user-images.githubusercontent.com/49893714/207801299-f2d5fc9b-d56b-4d0c-8970-ab0d6dc5bd47.png)

### Minimal, Reproducible Example - (Optional, but Recommended)

None

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Thanks for bringing this to my attention. The solution for anyone who runs into this during the next few days is to upgrade to `"material-react-table": "^1.4.3"`.

I am also reporting this issue to MUI itself though, as they should not have breaking changes like this.
