### ISSUE TITLE
Sticky footer sould be sticky even for pinned columns

### ISSUE THREAD

**Issue by dnjsgur0629** [KevinVandy/material-react-table#271]
### material-react-table version

5.10.17

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it
Issue from #250 
If the enableStickyFooter props set true, the pinned column's footer should also be sticky.

### Minimal, Reproducible Example - (Optional, but Recommended)

[![Edit stickyFooter](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stickyfooter-tg0xrw?fontsize=14&hidenavigation=1&theme=dark)

### Screenshots or Videos (Optional)

![206984527-431bf98e-461e-4bc8-8de7-e104ac5ed95f](https://user-images.githubusercontent.com/65391273/208604022-57789bdd-f02f-406b-a640-730abc6ac0e6.gif)

### Do you intend to try to help solve this bug with your own PR?

No, because I don't have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This will be fixed in v1.5.1. Just needed a `z-index: 1` on the Table Footer
