### ISSUE TITLE
Clearing empty/not empty chips don't respect allowed filter functions for column

### ISSUE THREAD

**Issue by ChapterSevenSeeds** [KevinVandy/material-react-table#288]
### material-react-table version

v1.5.2

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Given a column with the filter function "fuzzy" not allowed, change the filter function to "empty" or "notEmpty" and then delete the chip that appears in the default filter field. The filter mode will then change to "fuzzy".

Kevin, I have a few ideas for how to fix this:

1. Provide a default filter mode prop for the column. Removing the "Empty" chip would revert the filter to the default mode. Would this benefit from the addition of a default filter value?
2. Remove the clear button for the "Empty" and "Not Empty" chips so that the user is forced to use the filterFn menu to change the mode.

What do you think would be best?

### Minimal, Reproducible Example - (Optional, but Recommended)

```js
import React from 'react';
import ReactDOM from 'react-dom/client';
import MaterialReactTable from 'material-react-table';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <div style={{ width: '300px' }}>
      <MaterialReactTable
        enableColumnFilterModes
        initialState={{
          columnFilterFns: {
            stuff: 'empty'
          },
          showColumnFilters: true
        }}
        data={[
          {
            stuff: "Hello"
          }
        ]}
        columns={[
          {
            header: 'Stuff',
            accessorKey: "stuff",
            enableColumnFIlterModes: true,
            columnFilterModeOptions: ["empty", "notEmpty", "contains"]
          }
        ]}
      />
    </div>
  </React.StrictMode>
);
```

Click the delete button to the right of the "Empty" chip. Notice that the filter mode is now "fuzzy".

### Screenshots or Videos (Optional)

![image](https://user-images.githubusercontent.com/63123355/209850202-529599ab-4e0b-458a-83e2-d6f901f1f6ea.png)
![image](https://user-images.githubusercontent.com/63123355/209850237-098cb3fa-136d-47b5-8b91-0970201ce574.png)

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Probably the easiest solution would be to just have the value change to whatever is first in the `columnFilterModeOptions` array if provided, otherwise, then default to `fuzzy`.
