### ISSUE TITLE
Server-side select (dropdown) filter can't be cleared

### ISSUE THREAD

**Issue by lupuchard** [KevinVandy/material-react-table#291]
### material-react-table version

v1.5.2

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

If you follow the feature guide on "manual server-side column filtering" but make one of the columns a 'select' variant column then the "clear filter" button remains disabled after selecting a filter value, making it impossible to clear the filter.

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Screenshots or Videos (Optional)

![alabama](https://user-images.githubusercontent.com/2514990/209995758-4742462c-36e7-4dfd-93a9-255a7c245922.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I've tried to replicate this, but cannot. Here is my [Stackblitz example where I followed the same steps you did](https://stackblitz.com/edit/github-okdfqz?file=src%2FTS.tsx)

The x is not disabled at all

<img width="334" alt="image" src="https://user-images.githubusercontent.com/28243511/210017441-df1bfc2a-d3f3-4d4f-b838-d312cf63be96.png">

Please provide your own code sandbox where this behavior is seen or at least your full code snippet. Filling "." is not very helpful, and I'm trying to help you out here.

**Comment by lupuchard** [comment]
Your filterSelectOptions is weird. The [column options docs](https://www.material-react-table.com/docs/api/column-options) say it should be an array of objects with a text and value, not just an array of strings. When I fix that in your example, the filter can't be cleared.

**Comment by KevinVandy** [comment]
> Your filterSelectOptions is weird. The [column options docs](https://www.material-react-table.com/docs/api/column-options) say it should be an array of objects with a text and value, not just an array of strings. When I fix that in your example, the filter can't be cleared.
> 
> https://stackblitz.com/edit/github-okdfqz-ks7gxg?file=src%2FTS.tsx

That array isn't weird. I designed it to accept both data structures and have both ways be accepted in TypeScript.

This stackblitz does expose what the issue is though. Thanks.

**Comment by KevinVandy** [comment]
Found the source of your issue. The values should be strings, not numbers. I'm not sure if the library needs to account numbers here.

**Comment by KevinVandy** [comment]
This should be fixed in v1.5.4
