### ISSUE TITLE
renderDetailPanel get called 2x3 times for each row, when expand the detail view

### ISSUE THREAD

**Issue by lilin1013** [KevinVandy/material-react-table#295]
### material-react-table version

v1.3.16

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

1. go to example https://stackblitz.com/edit/github-tcjwan-vm59w3?file=src%2FTS.tsx, 
2. open the browser debugger with console tab
3. expand one node in the table
4. you can see renderDetailPanel for each row is called twice 

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-tcjwan-vm59w3?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

<img width="1920" alt="Screenshot 2023-01-02 at 19 07 22" src="https://user-images.githubusercontent.com/2203810/210266195-7900c60b-38a3-4ce6-9e6a-7c4035cdf3b0.png">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
What problem does this cause?

**Comment by KevinVandy** [comment]
Just tested this out by removing React Strict Mode and using React 17 and it is fine. Only renders once.

https://stackblitz.com/edit/github-tcjwan-jnglrr?file=package.json,src%2Fmain.tsx

React 18 now renders components twice in strict mode (and probably future versions of react), but only once in when the app is compiled and running in production.

If you want to change how React renders components, you can get rid of Strict mode in your project.
