### ISSUE TITLE
Customization filter: filterFn: 'betweenInclusive' and "between" have issus, error comes in console

### ISSUE THREAD

**Issue by sorousch9** [KevinVandy/material-react-table#309]
### material-react-table version

1.5.6

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When I use filterFn: between I get this error

: A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component . 

![Untitled](https://user-images.githubusercontent.com/78909837/211534040-febbed74-cc77-4c7a-a18e-c4ec9049020d.png)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/github/KevinVandy/material-react-table/tree/main/apps/material-react-table-docs/examples/customize-filter-variants/sandbox?file=/src/TS.tsx

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was fixed in v1.5.9
