### ISSUE TITLE
Gropuing expand/contract button does not work if paginateExpandedRows is set to false and any global filter is applied

### ISSUE THREAD

**Issue by braj-k** [KevinVandy/material-react-table#314]
### material-react-table version

v1.5.7

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

Steps to reproduce

1. Set the **_paginateExpandedRows_**  to `false`
2. Enable _**grouping**_ on 1 or more columns
3. Enable **_globalSearching_** as well
4. Now try to do a global search. The search works and data is filtered.
5. Try expanding/contracting the groups. This will not work.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/material-react-table-grouping-expand-issue-314-jqq754

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by braj-k** [comment]
![Uploading Screenshot 2023-01-11 at 7.42.12 PM.png…]()

**Comment by KevinVandy** [comment]
There are actually 2 options you have to fix this.

1. Use the filterFromLeafRows prop to apply filtering to the sub-rows first
2. Set the prop maxLeafRowFilterDepth={0} so that sub-rows don't get filtered out

More info here https://www.material-react-table.com/docs/guides/expanding-sub-rows#expanded-leaf-row-filtering-behavior

**Comment by KevinVandy** [comment]
Closing this as all you need to do is use either the `filterFromLeafRows` or `maxLeafRowFilterDepth` props as documented in both the [column filtering docs](https://www.material-react-table.com/docs/guides/column-filtering#expanded-leaf-row-filtering-options) and [expanding sub row docs](https://www.material-react-table.com/docs/guides/expanding-sub-rows#expanded-leaf-row-filtering-behavior)
