### ISSUE TITLE
Select all will also select disabled row

### ISSUE THREAD

**Issue by Elvincth** [KevinVandy/material-react-table#326]
### material-react-table version

v1.5.9

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

When using the select all checkbox in the datatable, it will also select the disabled rows. This is not the expected behavior. The select all checkbox should only select the enabled rows.

As you can see in the screenshot, the total row count is 85, and some of the rows is disabled. When I click the select all checkbox, it will select all the rows, including the disabled rows (85 of 85).

### Minimal, Reproducible Example - (Optional, but Recommended)

N/A

### Screenshots or Videos (Optional)

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/6602723/212632580-ca2a0062-7b0a-423e-bd57-2d4187aab5cf.png">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I think a `getSelectAllRowsFn` or something similarly named needs to be added to TanStack Table itself. I'll look into this soon.

**Comment by KevinVandy** [comment]
@Elvincth Hey turns out this is already possible in the current library, but I'm going to ship an update that makes it so you don't have to disable the checkboxes manually

All you have to do is pass in a callback function to `enableRowSelection` that conditionally enables it.

For example:

```jsx
<MaterialReactTable
   enableRowSelection={(row) => row.original.age >= 21}
/>
```

**Comment by KevinVandy** [comment]
I think all issues around this have been taken care of as of v1.6.2. See this example for more info: https://www.material-react-table.dev/?path=/story/features-selection-examples--selection-enabled-conditionally

**Comment by domi-glyph** [comment]
Hello, could you help me? I have similar issue and it is reproducible. 
Check it here : https://codesandbox.io/s/awesome-bird-0b8zex?file=/src/App.js

Steps to reproduce : 
1. toggle check all
2. toggle again to uncheck all
Here you will notice the disabled row will also uncheck, and if you try to toggle select all, it can't be "checked".

Initially the table will have several rows that is "checked", deselect all will also "uncheck" the disabled rows. I need the disabled rows to keep their state as "checked"
