### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by Abhimishra2424** [KevinVandy/material-react-table#327]
### material-react-table version

v1.5.9

### react & react-dom versions

"react": "^17.0.2",

### Describe the bug and the steps to reproduce it

./node_modules/@tanstack/virtual-core/build/lib/index.esm.js 124:92
Module parse failed: Unexpected token (124:92)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     sync
|   } = _ref;
>   const toOffset = (sync ? offset : offset + instance.options.scrollMargin) + (adjustments ?? 0);
|   (_instance$scrollEleme = instance.scrollElement) == null ? void 0 : _instance$scrollEleme.scrollTo == null ? void 0 : _instance$scrollEleme.scrollTo({
|     [instance.options.horizontal ? 'left' : 'top']: toOffset,

### Minimal, Reproducible Example - (Optional, but Recommended)

![Screenshot from 2023-01-18 12-06-39](https://user-images.githubusercontent.com/47156246/213101910-7bf1cd32-088c-4dee-b368-fbc2ff025778.png)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Try upgrading `react-scripts` to v5.0.1

**Comment by Abhimishra2424** [comment]
ok I will do

**Comment by Abhimishra2424** [comment]
thank you problem solve, it was working
