### ISSUE TITLE
TableData is visible in renderTopToolbarCustomActions and tableData is not viewed in renderRowActions.

### ISSUE THREAD

**Issue by gdw0923-daim** [KevinVandy/material-react-table#331]
### material-react-table version

v1.5.9

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

title - TableData is not viewed when button is inserted into renderRowActions and click action.

### Minimal, Reproducible Example - (Optional, but Recommended)

import React from 'react'
import {
    TextField, Select, SelectChangeEvent, MenuItem, Paper, Menu, Table,
    TableBody, TableCell, TableContainer, TableHead, TableRow, Box, Modal,
    Button, Stack, Checkbox, Typography, Tooltip, IconButton
} from '@mui/material'
import MaterialReactTable, {
    MRT_Cell,
    MRT_ColumnDef,
    MRT_Row,
    MRT_TableInstance
} from 'material-react-table'
import { Delete, Edit } from '@mui/icons-material'
import { Common } from '../../common-interface'

export default function NodeDefaultSetting() {

    const [homes, setHomes] = React.useState<Common.Home[]>([])

    const columns = React.useMemo<MRT_ColumnDef<Common.Home>[]>(
        () => [
            {
                accessorKey: 'priority',
                header: 'Priority',
            },
            {
                accessorKey: 'group_id',
                header: 'Group Id',
            },
        ],
        [],
    )

    function handleSaveCell(cell: MRT_Cell<Common.Home>, value: any) {

    }

    function handleDeleteRow(row: MRT_Row<Common.Home>, table: MRT_TableInstance<Common.Home>) {
        console.log(homes) // FIXME : It is not viewed here.   ( homes is tableData )
        console.log(table)

        setHomes((homes) => {
            console.log(homes) // FIXME : You can view it here.
            return []
        })

        const aa = homes.filter((value, index) => { return index !== row.index })
        console.log(aa)
        console.log(row)
        // setHomes(aa)
    }

    function handleCreateNewRow() {
        // FIXME : You can view it here.
        let group_id = 1
        while (homes.some((value) => { return value.group_id === group_id })) {
            group_id++
        }
        setHomes([...homes, { priority: 0, group_id: group_id }])
        console.log(homes)
    }

    return (
        <div>
            <MaterialReactTable
                        columns={columns}
                        data={homes}
                        editingMode='cell'
                        enableRowActions
                        muiTableBodyCellEditTextFieldProps={({ cell }) => ({
                            //onBlur is more efficient, but could use onChange instead
                            onBlur: (event) => {
                                handleSaveCell(cell, event.target.value)
                            },
                        })}
                        renderBottomToolbarCustomActions={() => (
                            <Typography sx={{ fontStyle: 'italic', p: '0 1rem' }} variant='caption'>
                                Double-Click a Cell to Edit
                            </Typography>
                        )}
                        renderRowActions={({ row, table }) => (
                            <Box>
                                <Tooltip arrow placement="right" title="Delete">
                                    <IconButton color="error" onClick={() => handleDeleteRow(row, table)}>
                                        <Delete />
                                    </IconButton>
                                </Tooltip>
                            </Box>
                        )}
                        renderTopToolbarCustomActions={() => (
                            <Button variant='outlined' onClick={handleCreateNewRow}>
                                Create New Row
                            </Button>
                        )}
                    />
        </div >
    )
}

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Sorry, I don't understand what this is trying to say

**Comment by KevinVandy** [comment]
Closing this as it was too vague.
