### ISSUE TITLE
OverlappingRows In memoMode="rows"

### ISSUE THREAD

**Issue by Abhimishra2424** [KevinVandy/material-react-table#333]
### material-react-table version

v1.5.9

### react & react-dom versions

"react": "^17.0.2",

### Describe the bug and the steps to reproduce it

I
![Screenshot from 2023-01-21 17-46-52](https://user-images.githubusercontent.com/47156246/213866514-985b3e06-a384-44ca-a7a5-2d3389ff80eb.png)
 am using rowVirtualizer with memoMode is Rows and my table has sub rows when I expand the rows the overlapping problem seeI

### Minimal, Reproducible Example - (Optional, but Recommended)

 i am using rowVirtualizer with memoMode is Rows and my table has sub rows when I expand the rows the overlapping problem seen

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Abhimishra2424** [comment]
![Screenshot from 2023-01-21 17-57-51](https://user-images.githubusercontent.com/47156246/213866794-e9da47a2-c2fc-41db-b091-d2fd5d54d5bc.png)
full screen also

**Comment by KevinVandy** [comment]
Hey, just FYI, this had a disclaimer in the docs that memoMode="row" in incompatible with row expanding features.

https://www.material-react-table.com/docs/guides/memoize-components#row-memoization-breaks-the-following-features

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/28243511/213877862-888c74ac-b94f-4360-aa29-b0e2cc9501b9.png">

**Comment by Abhimishra2424** [comment]
okay then i will close this issue  thank you
