### ISSUE TITLE
Allow row actions (actions column) to be always visible - enable actions column pinning.

### ISSUE THREAD

**Issue by Drezir** [KevinVandy/material-react-table#334]
### material-react-table version

1.5.7

### react & react-dom versions

both 18.2.0

### Describe the bug and the steps to reproduce it

Allow actions column pinning

### Minimal, Reproducible Example - (Optional, but Recommended)

None

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Drezir** [comment]
I see it can be done. I cannot find the name for actions in documentation.

**Comment by KevinVandy** [comment]
@Drezir The Display Columns docs lists all the ids of the built in columns https://www.material-react-table.com/docs/guides/display-columns

**Comment by Drezir** [comment]
@KevinVandy 
Thanks, It works but is this padding/margin normal among pinned action and data column?
![image](https://user-images.githubusercontent.com/11374081/214062896-8614de24-d5ce-4a69-9552-ea36844e04e0.png)

**Comment by KevinVandy** [comment]
I cannot tell what's wrong unless you paste your code here

**Comment by Athrun-Judah** [comment]
I had the same problem.This occurs when I pin some columns to the right. @KevinVandy 

> @KevinVandy Thanks, It works but is this padding/margin normal among pinned action and data column? ![image](https://user-images.githubusercontent.com/11374081/214062896-8614de24-d5ce-4a69-9552-ea36844e04e0.png)
