### ISSUE TITLE
scrolling problem with 1.00.000 rows

### ISSUE THREAD

**Issue by Abhimishra2424** [KevinVandy/material-react-table#336]
### material-react-table version

1.3.4

### react & react-dom versions

17

### Describe the bug and the steps to reproduce it

I am rendering 100000  rows with virtualize is true but there was a problem come in scrolling and also I am using row selection with keyboard keys up/down I Focus on Tr element and scrolling but not perfect performance getting please help me with how to solve the scrolling problem with 100000 rows

### Minimal, Reproducible Example - (Optional, but Recommended)

not have

### Screenshots or Videos (Optional)

#

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
If you are going to report a performance issue, you need to have a reproducible example

**Comment by Abhimishra2424** [comment]
can i  send you in meta storage ?

**Comment by Abhimishra2424** [comment]
I will send
