### ISSUE TITLE
"x" group by button not working when set by initialstate

### ISSUE THREAD

**Issue by oliverfrost1** [KevinVandy/material-react-table#344]
### material-react-table version

v1.6.0

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

You can't click the x button on groupings:
![image](https://user-images.githubusercontent.com/41832493/215501977-7db906d1-19dd-4fcf-917e-7a825686c9c3.png)

If you click the search button, the x button works again. 

The bug can be seen on the documentation page: https://www.material-react-table.com/docs/guides/aggregation-and-grouping

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/guides/aggregation-and-grouping

### Screenshots or Videos (Optional)

![Skærmbillede 2023-01-30 151943](https://user-images.githubusercontent.com/41832493/215502415-c424a342-80b1-4f71-92fe-ee36936c6e2e.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is a z-index issue introduced in the latest version, not related to initial state. Will update this soon. `muiAlertProps` can be changed manually in the meantime

**Comment by oliverfrost1** [comment]
Thanks, Kevin. That sounds good :)

**Comment by KevinVandy** [comment]
@oliverfrost1 should be fixed in v1.6.1
