### ISSUE TITLE
Grouping breaks when no sorting and search for child

### ISSUE THREAD

**Issue by oliverfrost1** [KevinVandy/material-react-table#347]
### material-react-table version

1.6.2

### react & react-dom versions

Your website

### Describe the bug and the steps to reproduce it

If you search for an element that is a child of a grouped row, it breaks the grouping, so that the child appears above it. '

If there is any sort of sorting going on, it works. 

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/guides/aggregation-and-grouping#aggregation-grouping-example

### Screenshots or Videos (Optional)

![image](https://user-images.githubusercontent.com/41832493/215810147-173ef329-b9e1-4083-8965-3a22b2db0832.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
ok I think I see the problem here. Try setting `enableGlobalFilterRankedResults={false}` for now when grouping is enabled.

I should have a fix for that soon when I have time in the next couple days.

**Comment by oliverfrost1** [comment]
Thanks Kevin, that sounds great!
