### ISSUE TITLE
renderDetailPanel is incompatible with row virtualization

### ISSUE THREAD

**Issue by KevinVandy** [KevinVandy/material-react-table#365]
### Discussed in https://github.com/KevinVandy/material-react-table/discussions/364

<div type='discussions-op-text'>

<sup>Originally posted by **Calebvh** February  9, 2023</sup>
Posting here since I'm not sure if this is a bug or not. 

I am having issues with the renderDetailsPanel option on a virtualized table. This option works great if I move to a paginated tabled with options ("enablePagination" and removing "enableRowVirtualization") however if I am using virtualization the details panel is expanded over the rows below it and it's z-index is too low to go above the border lines of the row below it. 

Below is what I'm seeing with a red background for the div in the panel and dark blue for the panel itself.
![image](https://user-images.githubusercontent.com/21250593/217877363-5ce7be2d-822a-4bf6-abe9-a065dc1a843b.png)

Opening multiple results in many of the rows no longer being visible
![image](https://user-images.githubusercontent.com/21250593/217877944-309afe55-6a38-4e40-99dd-3459688f6a73.png)

I was wondering if anyone had a similar issue or knows of how to resolve this? 

To reproduce, you should be able to use any dataset you want but just with virtualization enabled. Below is my current configuration that is experiencing this issue. 
`

   <MaterialReactTable

            columns={columns}
            data={Object.values(statusList)}
            enableBottomToolbar={false}
            enableGlobalFilterModes
            enablePagination={false}
            enableDensityToggle={false}
            enableColumnFilters={false}
            enableRowVirtualization
            initialState={{columnVisibility: {storeId: false, pluCount: false,totalMemory: false,freeMemory: false }}}
            muiTableContainerProps={{ sx: { maxHeight: '800px' } }}
            onSortingChange={setSorting}
            state={{ isLoading, sorting }}
            renderDetailPanel={({row}) => (
                <div style={{ padding: '10px', backgroundColor: "rgba(255, 49, 64, 1)"}}>
                    <h3>Details</h3>
                    <p>Device IP: {row.original.ipAddress}</p>
                    <p>Device Name: {row.original.hostname}</p>
                    <p>Device Status: {row.original.statusMessage}</p>
                    <p>Device Version: {row.original.applicationVersion}</p>
                </div>
            )}
            rowVirtualizerInstanceRef={rowVirtualizerInstanceRef} //optional
            rowVirtualizerProps={{ overscan: 8 }} //optionally customize the virtualizer
        />
`
</div>

**Comment by Elvincth** [comment]
I had a similar issue as well. Is it because the height of the panel can't be calculated because of virtual scroll?

**Comment by gitOfKumarSathish** [comment]
@KevinVandy , is there any plan of Fixing this issue?

**Comment by gitOfKumarSathish** [comment]
@KevinVandy,
Thanks in Advance!
is there any possibility of fixing this issue?

**Comment by KevinVandy** [comment]
@gitOfKumarSathish a somewhat large refactor is needed unfortunately. We'll see. It is a big priority for me.

**Comment by natalyamuratova** [comment]
I have the same issue (row virtualization and expanded panel). The expanded panel simply overlaps the bottom rows. 
![image](https://github.com/KevinVandy/material-react-table/assets/24488371/ec8aa4ff-0866-423a-a1b4-98b5d138aafa)
It would be great if the expanded panel was located **between** the rows.
Is this a feature or a bug? Is it possible to display the panel between the lines?
Thanks.

**Comment by KevinVandy** [comment]
Good news for anyone following this. Detail Panels and Row Virtualization will be compatible with each other in version 2.6.0.
One caveat is that the expand/collapse animation for the detail panel will be disabled, but I otherwise got it working.

**Comment by KevinVandy** [comment]
Working example now in the docs:
https://www.material-react-table.com/docs/guides/detail-panel#enable-detail-panel-virtualized-demo
