### ISSUE TITLE
[Accessibility Issue] Column header sort button is not responsing to "Enter" or "Space"

### ISSUE THREAD

**Issue by zeqiu-mirage** [KevinVandy/material-react-table#366]
### material-react-table version

v1.7.2

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

Go to the basic example: https://www.material-react-table.com/docs/examples/basic
Push "Tab" button, until focus falls on one of the column header sort button, push "Enter" or "Space", no response. Using keyboard should be able to sort or unsort the column.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/github/KevinVandy/material-react-table/tree/main/apps/material-react-table-docs/examples/basic/sandbox?file=/src/TS.tsx

### Screenshots or Videos (Optional)

![image](https://user-images.githubusercontent.com/6391338/217975917-17cdecc1-c89f-4d63-b67c-01ec136b902c.png)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
It's currently implemented the way MUI recommends. If you have an easy fix, I'm open to it. At the very least, the column actions menu should be accessible as a backup option.

**Comment by zeqiu-mirage** [comment]
@KevinVandy The reason why keyboard doesn't work is because the onClick is on parent Box, while the parent Box is not focusable, and SortLabel is a button with on onClick. The fix should be easy: add onClick={column.getToggleSortingHandler()} to MRT_TableHeadCellSortLabel with event.stopPropagation().

**Comment by KevinVandy** [comment]
> @KevinVandy The reason why keyboard doesn't work is because the onClick is on parent Box, while the parent Box is not focusable, and SortLabel is a button with on onClick. The fix should be easy: add onClick={column.getToggleSortingHandler()} to MRT_TableHeadCellSortLabel with event.stopPropagation().

Sweet. Would you like to make a pr for that? Otherwise I'll try to get to that this week.

**Comment by zeqiu-mirage** [comment]
@KevinVandy didn't find instruction about build and testing, can you send it or point to me?

**Comment by KevinVandy** [comment]
> @KevinVandy didn't find instruction about build and testing, can you send it or point to me?

Everything needed to run the project locally is in the contributing guide

**Comment by zeqiu-mirage** [comment]
Here is the PR: https://github.com/KevinVandy/material-react-table/pull/390
