### ISSUE TITLE
ExpandLessIcon is not implemented

### ISSUE THREAD

**Issue by nemanjam1** [KevinVandy/material-react-table#368]
### material-react-table version

1.6.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

ExpandLessIcon is not implemented, when I add custom icon that icon is not visible after row expansion instead ExpandMoreIcon is still visible.

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You're right, it is unused. I'll probably just remove it. Only the ExpandMore icon gets used and it get's rotated internally.

**Comment by nemanjam1** [comment]
Maybe we should keep it. For example if people want to have different icons (+ and -)

**Comment by KevinVandy** [comment]
@nemanjam1 I published a new version v1.7.4 where you can now override the `muiExpandButtonProps.children` with a callback per row.
