### ISSUE TITLE
expandRowsFn

### ISSUE THREAD

**Issue by nemanjam1** [KevinVandy/material-react-table#369]
### material-react-table version

1.7.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

expandRowsFn does not seem to be implemented. I guess this function can be used for server side row expansion.

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This prop does not exist anywhere in TanStack Table or MRT. Where did you find a reference or mention of it?

**Comment by tyv** [comment]
it exist here: https://www.material-react-table.com/docs/api/props#expandRowsFn-prop
