### ISSUE TITLE
Change `pageIndex` starts from 1 instead of 0.

### ISSUE THREAD

**Issue by LvChengbin** [KevinVandy/material-react-table#378]
### material-react-table version

v1.7.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

`Material-UI` [Pagination API](https://mui.com/material-ui/api/pagination/) use `1` as it's default value, `material-react-table` should use the same strategy with `Material-UI` pagination components.

### Minimal, Reproducible Example - (Optional, but Recommended)

*No sample code.*

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Does this cause a bug? I don't see any. TanStack Table itself uses 0 based page indexing.

Also, I'm reading the MUI TablePagination docs and it says that it is 0 based indexing, so I think that everything is ok from MRT's end.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/28243511/219473604-cfe513bc-4d39-4c82-b912-62fc1583d4e5.png">

MRT uses [TablePagination](https://mui.com/material-ui/api/table-pagination/), not [Pagination](https://mui.com/material-ui/react-pagination/)

**Comment by LvChengbin** [comment]
@KevinVandy  Thank you so much. I didn't see the document of TablePagination.
For us, we are providing both table view (using table pagination) and grid view (using pagination) for lists.
Because of this problem, we can't implement these two views with same pagination parameters.
But I think `material-react-table` should conform the TablePagination API.
Thank you again.

**Comment by KevinVandy** [comment]
@LvChengbin when hooking up the state, all you would have to do is add a +1 to the value

**Comment by LvChengbin** [comment]
@KevinVandy I know that I just need to add a `+1` or `-1`, but I think it's weird that two similar components for same function in one UI library have different parameter strategies.

**Comment by LvChengbin** [comment]
@KevinVandy I send an issue to material-ui, they may change this in v6.

https://github.com/mui/material-ui/issues/36233
