### ISSUE TITLE
MRT doesn't respect parent height and just overflows

### ISSUE THREAD

**Issue by oliverfrost1** [KevinVandy/material-react-table#379]
### material-react-table version

v1.7.4

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

MRT should respect the height of the parent element, and get smaller to fit into it, but it doesn't. If you place it in a div that is 500px tall, it just overflows out of it. 

You can fix it manually in the CSS by making the paper height 100% and the table container height 100%. 

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-zeky5k?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

![image](https://user-images.githubusercontent.com/41832493/219423173-246c5c28-0a08-4700-bcd2-ade0cccf69e2.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by domi-glyph** [comment]
i'm having the same problem as well and i don't know how to fix this too.

The current solution i have is using `muiTableContainerProps` props and set height and width in sx.

`
muiTableContainerProps={{
                              sx: { width: '100%', height: '100%' },
                            }}
`

**Comment by DiegoBM** [comment]
Try setting layoutMode="grid" in the grid properties, that worked for me

**Comment by AliBdeir** [comment]
Having the same issue, and none of the posted solutions fix it.

**Comment by AliBdeir** [comment]
Also having this issue, and it's causing multiple problems, even with the solutions posted.

**Comment by alinak23** [comment]
Having the same problem, if there are any solutions for this ?

**Comment by arcasoy** [comment]
I was also seeing this issue. I was able to fix it through applying some styles to the different accessible props. Here's the outcome
![image](https://github.com/KevinVandy/material-react-table/assets/32803978/a471895c-6feb-4f5f-9ad5-1a6664b2c264)

The selected div is the same as in OPs post. The two additions I made to make this height responsive:

- Manually override the immediate child div style with height: 100% (red tick mark). This is done by adding the following prop ```muiTablePaperProps={{ sx: { height: '100%' } }}```
- Add calc(100% - 112px) to muiTableContainerProps prop (blue tick mark). This is done by adding the following prop ```muiTableContainerProps={{ sx: { height: 'calc(100% - 112px)' } }}```
The 112px comes from the addition of the header and footer tabs (56px each in my case). Adjust as you see fit with your table's design.

This provides a table that's height responsive where the row display itself expands and shrinks while the headers and footers stay visible.

**Comment by s-light** [comment]
thanks @arcasoy .
i needed to additionally add this to `index.html`
```html
<style>
  html, body {
    /* fix flash of white on reload */
    background-color: black;
  }
  html, body, #root {
    /* enable 100% height for inner containers.. */
    height: 100%;
  }
</style>
```

and make sure that my App container also has `sx={{ height: "100%", display: "flex", flexDirection: "column" }}` set.

`App.jsx`
```jsx
// ...

export default function App() {
    return (
        <Container
            maxWidth="false"
            sx={{ height: "100%", display: "flex", flexDirection: "column" }}
        >
            <Typography variant="h4" component="h1" gutterBottom>
                test for MRT2
            </Typography>
            <MyTable/>
        </Container>
    );
}
```

**Comment by KevinVandy** [comment]
Going to close this as this is kinda a feature rather than a bug in order for the table container scrolling to work as expected.

You can do something like this:

```ts
<div style={{ height: '300px' }}>
    <MaterialReactTable
      columns={columns}
      data={data}
      muiTableContainerProps={({ table }) => ({
        sx: {
          height: `calc(100% - ${table.refs.topToolbarRef.current?.offsetHeight}px - ${table.refs.bottomToolbarRef.current?.offsetHeight}px)`,
        },
      })}
      muiTablePaperProps={{
        sx: {
          height: '100%',
        },
      }}
    />
  </div>
```

if you really need it.

**Comment by arcasoy** [comment]
Would it be useful to add this as a prop to the <MaterialReactTable /> component? I imagine this is a commonly utilized styling and, with how elegant @KevinVandy's solution is, I wonder if an `adjustToParent: true` prop (or some other name) could be added to apply the styles suggested. This might just make implementation for a new user more seamless.
