### ISSUE TITLE
Overlapping rows in memoMode="rows"

### ISSUE THREAD

**Issue by mishapoiuytrewq** [KevinVandy/material-react-table#384]
### material-react-table version

v1.8.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Overlapping rows in memoMode="rows"
Reproducing in chrome 110 and firefox 110 on ubuntu 22.10
```ts
<MaterialReactTable
      columns={columns}
      data={data}
      enableColumnActions={false}
      enableColumnFilters={false}
      enableDensityToggle={false}
      enableGlobalFilter={false}
      enableHiding={false}
      enablePagination={false}
      enableSorting={false}
      enableRowVirtualization
      memoMode="rows"
    />
```
```ts
  const columns = useMemo<MRT_ColumnDef<any>[]>(
    () => [
      {
        accessorKey: "firstName",
        header: "First Name"
      },
      {
        accessorKey: "text",
        header: "Text"
      }
    ],
    []
  );
```
```ts
export const data = new Array(1000).fill(0).flatMap(() => [
  {
    firstName: "Dylan",
    text:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed est bibendum, ultricies erat vel, condimentum erat. Morbi maximus, mauris nec viverra hendrerit, tellus nibh pharetra ante, in euismod augue lorem ac tellus."
  },
  {
    firstName: "Raquel"
  },
  {
    firstName: "Ervin"
  },
  {
    firstName: "Brittany",
    text:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed est bibendum, ultricies erat vel, condimentum erat. Morbi maximus, mauris nec viverra hendrerit, tellus nibh pharetra ante, in euismod augue lorem ac tellus."
  },
  {
    firstName: "Branson"
  }
]);
```

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/overlapping-rows-in-memomode-rows-96uk4y?file=/src/TS.tsx

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
If you're going to memoize rows and use virtualization, you may need to change the `rowVirtualizerProps.estimateSize` value

**Comment by mishapoiuytrewq** [comment]
> If you're going to memoize rows and use virtualization, you may need to change the `rowVirtualizerProps.estimateSize` value

It may be worth rewriting from react-virtual to react-virtuoso. I have not met such a problem there

**Comment by KevinVandy** [comment]
Just don't memorize rows if you're using memorization. This is just an issue where measure only gets called during render. No plans on migrating away from TanStack.
