### ISSUE TITLE
Issue with displayed column size when changing column visibility from false to true

### ISSUE THREAD

**Issue by KensukeKikuch** [KevinVandy/material-react-table#394]
### material-react-table version

v1.8.1

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Changing the visibility of a column from false to true can cause the column size to be displayed incorrectly, even though the internal column size calculation (column.getSize()) is correct. 
The issue can be reproduced by following the steps below:

1. Set the initial visibility of a column to false.
2. Change the visibility of the same column to true.
3. Notice that the displayed column size is not incorrectly.
4. Observe that when a horizontal scrollbar is present, the displayed column size becomes nearly min size (if set enableColumnResizing=true, column size will be 0), and when it is not present, the displayed size becomes nealy max size.

This behavior was not present in versions prior to v1.6.6, and has been reproduced in all versions since the column resizing update in v1.7.0.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/material-react-table-column-size-issue-6oc2b8?file=/src/App.js

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
@KensukeKikuch This should be fixed in v1.8.2
