### ISSUE TITLE
Server-side manual pagination with react-virtual

### ISSUE THREAD

**Issue by Yellrus** [KevinVandy/material-react-table#4]
How to do server-side pagination with react-virtual? Please, thx)

**Comment by KevinVandy** [comment]
Server side manual (controlled) pagination is definitely possible. The best example I can currently point to is from TanStack Table itself, but you can pass the same state props to MRT. https://tanstack.com/table/v8/docs/examples/react/pagination-controlled. 

https://tanstack.com/table/v8/docs/examples/react/pagination-controlled

I'm not sure what you mean by "with react-virtual" as I usually either see pagination or virtualization used, but not both at the same time. Do you mean infinite scrolling or something like that?

Regardless, you can customize some react-virtual options with `virtualizerProps`.
