### ISSUE TITLE
Grouping expand/collapse button does not work if paginateExpandedRows is set to false and any global filter is applied.

### ISSUE THREAD

**Issue by braj-k** [KevinVandy/material-react-table#405]
### material-react-table version

v1.8.4

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

I have raised this concern previously [here](https://github.com/KevinVandy/material-react-table/issues/314).
The proposed solution does not work for Global Filters.
I have kept one of the proposed solutions in the sandbox. It does not work. I have experimented with other proposed solutions as well

Steps to reproduce

1. Set the paginateExpandedRows to false
2. Enable grouping on 1 or more columns
3. Enable globalSearching as well
4. Now try to do a global search. The search works and data is filtered.
5. Try expanding/collapsing the groups. This will not work.

You can keep the groups expanded and then try the filtering, you will not be able to collapse.
If you clear the global search however, the expand/collapse restarts working.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/material-react-table-grouping-expand-issue-314-forked-28c5fk

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
A quick solution here would be to set the `enableGlobalFilterRankedResults={false}` prop

**Comment by braj-k** [comment]
Thanks @KevinVandy. This option works. I can confirm. Updated the sandbox as well.
