### ISSUE TITLE
Remote Fetching Examples arent loading data

### ISSUE THREAD

**Issue by marketsystems** [KevinVandy/material-react-table#406]
### material-react-table version

1.8.4

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

remote fetching examples currently just displaying "Error Loading Data" on website

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/examples/remote
https://www.material-react-table.com/docs/examples/react-query

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm aware. Vercel is being dumb

**Comment by KevinVandy** [comment]
This ended up being a problem with my Vercel account billing and they shut off my api routes. It is fixed now lol
