### ISSUE TITLE
muiTablePaginationProps={{rowsPerPage}} Not Working 

### ISSUE THREAD

**Issue by manosec** [KevinVandy/material-react-table#411]
### material-react-table version

1.8.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I am new to using material-react-table

I have data that comes from the backend with axios API call and defining the columns with the useMemo hook from react so after calling the API, I am using useState to assign the response data to a variable.

Now, the data has been mapped successfully and shown the UI with default records of 10 per page.

I am trying to modify them to 5, that's where my problem begins.

<MaterialReactTable columns={columns} data={items} 
muiTablePaginationProps={{
    rowsPerPage: 5,
    rowsPerPageOptions: [5, 10, 25, 50],
  }}
/>

The above muiTablePaginationProbs doesn't have any effect on my UI, I was struggling. kindly check my issue and let me know if anything went wrong.

Note:
It shows 5 in the drop-down box below the right corner but in data, it still shows 10 rows of data.

### Reproducible Example

**Data:**

const [data, setData] = useState([])

  useEffect(() => {
    const loadPost = async () => {
      const response = await axios
        .get("http://localhost:5000/data")
        .then((response) => {
          setData(response.data.result);
        });
    };
    loadPost();
  }, []);

**Columns:**

const columns = useMemo(
    () => [
    
      {
        accessorKey: "apple_count",
        header: "Apple",
      },
      {
        accessorKey: "orange_count", 
        header: "Orange",
      },
      {
        accessorKey: "Pine_count",
        header: "PineApple",
      },
    ],
    [data]
  );

return (<MaterialReactTable columns={columns} data={data} 
              muiTablePaginationProps={{rowsPerPage:5, 
                                                       rowsPerPageOptions: [5, 10]
                                                        }} 
            />);

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by manosec** [comment]
![reference_ss](https://user-images.githubusercontent.com/86837128/223474413-4eedfe92-3905-4783-ad12-3b06c5573975.png)

See Here it shows 5 but the data is more than 5(it is 10).

Kindly help me with this.

**Comment by KevinVandy** [comment]
I probably just need to omit `muiTablePaginationProps.rowsPerPage` from the TS types that come from MUI, because they are not meant to work here. You have to manage that through the pagination state instead.

https://www.material-react-table.com/docs/guides/pagination#manage-pagination-state

**Comment by dnjsgur0629** [comment]
I am customizing the pagination in my code and I was surprised to see that "rowsPerPage" was omitted at some point since it works perfectly fine for me as a prop. There are cases where "rowsPerPage" works well, and since it is the simplest way to control pagination, I think it would be better to include "rowsPerPage" in the TS type again. What do you think?

here is my case:
[![Edit material-react-table-pagination](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-react-table-pagination-tg0xrw?fontsize=14&hidenavigation=1&theme=dark)
