### ISSUE TITLE
Using prop onIsFullScreenChange disables the full screen toggle functionality

### ISSUE THREAD

**Issue by simonfloren** [KevinVandy/material-react-table#413]
### material-react-table version

1.8.4

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

As title says using the prop `onIsFullScreenChange` disables the functionality of toggling full screen. Unlike setting the prop `enableFullScreenToggle` to `false` the button remains rendered and is not disabled in terms of the `disabled` React prop/HTML attribute. This can be reproduced by passing an empty function to the prop. Attempting to set the state `isFullScreen` through the table instance API in the passed function will trigger the function until the maximum call stack size exceeded error pops up, so that workaround did not work.

### Minimal, Reproducible Example - (Optional, but Recommended)

[Full screen issue example forked from the basic example in the docs](https://stackblitz.com/edit/github-akiyhh?file=src%2FTS.tsx)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You just also have to pass back `isFullScreen` to the `state` prop if you manage the full screen state yourself.

```state={{ isFullScreen }}```

https://stackblitz.com/edit/github-akiyhh-rx7scb?file=src%2FTS.tsx
