### ISSUE TITLE
Hide pinned columns leave white spaces and leads to errors when enableColumnVirtualization is set to true

### ISSUE THREAD

**Issue by gumofunghi** [KevinVandy/material-react-table#418]
### material-react-table version

v1.5.7

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

When column virtualization is enabled, pinning hidden column or hiding pinned column will leave a white space in the table. If try to hide all columns when there is pinned column or pin columns when all columns are hidden, it will lead to an error as shown in screenshot below.

The problem in my code is similar with this example:
https://www.material-react-table.dev/?path=/story/features-virtualization--enable-column-virtualization-with-pinning 

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.dev/?path=/story/features-virtualization--enable-column-virtualization-with-pinning 

### Screenshots or Videos (Optional)

There is huge white space on the left when I pin hidden columns.
![image](https://user-images.githubusercontent.com/32225533/223885197-581915f4-cb2b-487c-a29e-8d4625ae37fe.png)

White spaces also generated when I pin columns, but not as huge as when the pinned column is hidden.
![image](https://user-images.githubusercontent.com/32225533/223887561-62418e57-02b7-44fd-aee3-ca8becc19ec1.png)

The error when try to hide all columns but there is pinned column.
![image](https://user-images.githubusercontent.com/32225533/223885385-b3537713-4f4f-4c79-8c94-c15134ec3470.png)

This error occurs when try to pin few columns when all columns are hidden.
![image](https://user-images.githubusercontent.com/32225533/223886199-d1141d25-d42c-4144-b725-ef96efc69928.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by jeg924** [comment]
I found a similar problem in https://www.material-react-table.dev/?path=/story/features-virtualization--row-and-column-virtualization-with-features.

When resizing and pinning virtual columns, there's extra whitespace and disconnect between the edge of the table and the pinned columns.

![image](https://github.com/KevinVandy/material-react-table/assets/46009030/5fd7febb-9712-4ca7-a1dd-b4c37314588e)

**Comment by KevinVandy** [comment]
This should be all the way fixed in v2.4.1 releasing tonight. More testing underway
