### ISSUE TITLE
Row onClick function is called when selecting an action or clicking to close it

### ISSUE THREAD

**Issue by alexstanbury** [KevinVandy/material-react-table#421]
### material-react-table version

latest

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I want to be able to click a row to navigate to a url, but I also have row actions set up as menu items.

The problem is that the row click event is called when either:

Clicking one of the menu items in the action menu.
or
Clicking away to close the action menu.

This means I can't make the row clickable and have actions at the same time.

See [here](https://codesandbox.io/p/sandbox/keen-cache-2nuryt) for a demo of the issue

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/keen-cache-2nuryt

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
If you are implementing onClicks manually like that, just remember to add `event.stopPropagation()` in the onClicks

https://codesandbox.io/p/sandbox/keen-cache-2nuryt?file=%2FREADME.md

**Comment by alexstanbury** [comment]
Hi, adding event.stopPropagation() to the menu items works for that, but I still get the alert when clicking away to close

https://codesandbox.io/p/sandbox/infallible-nobel-ys9h9m

It looks as though there is some delayed event propagation happening still, I'm not sure if there is a way of stopping it though.

**Comment by KevinVandy** [comment]
fixed in v1.9.1
