### ISSUE TITLE
resize handle works in opposite direction in rtl direction

### ISSUE THREAD

**Issue by sajjad-choobdari** [KevinVandy/material-react-table#424]
### material-react-table version

1.8.5

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

In right-to-left languages, when resizing a column, the resizing handle works in the opposite direction it is dragged.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/dazzling-chihiro-010ojp

### Screenshots or Videos (Optional)

https://user-images.githubusercontent.com/46104002/224428996-1e4040ef-b1e2-42a9-8ffb-1cac17b3175d.mov

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Is my rtl example set up differently than yours? https://www.material-react-table.com/docs/guides/localization
I do not see this issue on my docs site, but I do see it in your sandbox.

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/28243511/226692823-877c66c7-c162-4bcb-867e-f4388484e8f7.png">

**Comment by sajjad-choobdari** [comment]
I compared them and it seems your example didn't follow the [steps 3 and 4 of the MUI documentation for configuring right-to-left](https://mui.com/material-ui/guides/right-to-left/#3-install-the-rtl-plugin)
after I added it to your example it broke on yours too

**Comment by KevinVandy** [comment]
In the latest v2, there is now a `columnResizeDirection`table option that can be used to make the column move in the opposite direction. Depending on which way you set up rtl CSS, you may or may not need it, but it is there.
https://www.material-react-table.dev/?path=/story/features-column-resizing-examples--column-resizing-enabled-default-on-change-rtl
