### ISSUE TITLE
Infinite scrolling table doesn't load ANY data

### ISSUE THREAD

**Issue by evitalv** [KevinVandy/material-react-table#431]
### material-react-table version

1.8.5

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

There is an error when loading data. This error doesn't happen on local environments/with mock data, but does happen in production with real APIs and URLs.

I would appreciate if you fixed this as soon as possible, please.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/examples/infinite-scrolling

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm aware. Vercel is being dumb and breaking api deployments and I just have not had time to debug it yet

**Comment by KevinVandy** [comment]
you can look at the mantine version in the meantime https://www.mantine-react-table.com/docs/examples/infinite-scrolling

**Comment by evitalv** [comment]
Do you know the last version that worked? I'll have to use that then. I'm afraid Mantine isn't possible since we have an organization-wide directive to use MUI in React projects.

**Comment by evitalv** [comment]
Right, sorry. I got this issue on my environment right after I upgraded MRT version but it turned out that it was caused by something else, not MRT. Thanks for your help.

**Comment by KevinVandy** [comment]
This ended up being a problem with my Vercel account billing and they shut off my api routes. It is fixed now lol
