### ISSUE TITLE
Overriding muiTableBodyCellProps component shows ref warning

### ISSUE THREAD

**Issue by skempisty** [KevinVandy/material-react-table#435]
### material-react-table version

v1.9.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

This may occur when overriding other components, but I only know about this case.

When I try to use `MaterialReactTable`'s `muiTableBodyCellProps` prop, I can override the cell component by returning an object with a `component` property that returns a component.

Everything seems to be working just fine, but I'm getting this concerning console warning:

> Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

> Check the render method of `MuiTableCellRoot`.

Remove the component override and you'll see there's no warning. I've provided a codesandbox that should help illustrate what I'm facing.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/bold-scott-8fg0s9?file=/src/App.js

### Screenshots or Videos (Optional)

![image](https://user-images.githubusercontent.com/10687488/226476592-5472f617-8e95-443c-8e86-687eec85b4cd.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Closing this as overriding the `component` with custom jsx is not supported.

**Comment by skempisty** [comment]
My use case is that I need to wrap every cell with a tooltip. Pretty simple implementation which actually does seem to work except for the verbose warning message.

![image](https://user-images.githubusercontent.com/10687488/226982239-8fd3f235-b7d0-40ba-b9e8-b506b46ca55a.png)

`Cell` isn't going to work since I want to avoid having to add the tooltip on every column. Any chance there's a better recommended way to accomplish what I'm trying to do? Googling got me to this `component` override method.

**Comment by KevinVandy** [comment]
> `Cell` isn't going to work since I want to avoid having to add the tooltip on every column. Any chance there's a better recommended way to accomplish what I'm trying to do? Googling got me to this `component` override method.

If you simply do not want to have to define the `Cell` multiple times for all columns, just define it in the `defaultColumn` prop.

**Comment by KevinVandy** [comment]
@nivnahmias 
> I have the exact same use-case and wondering how this can be implemented without logging errors to the console

Not sure, as said in the comment above, there are much better options with `Cell` and/or `defaultColumn`. But maybe it needs to be wrapped in `React.forwardRef`? MRT relies on refs being defined on the table cells for some features, so doing this wrong might cause unintended bugs.

**Comment by zhongjiaguo001** [comment]
How was it resolved? I used this method in custom edit cells, but the console raised a warning
