### ISSUE TITLE
Problem with column filtering caused by Virtual

### ISSUE THREAD

**Issue by evitalv** [KevinVandy/material-react-table#438]
### material-react-table version

1.9.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Our project uses MRT with infinite scrolling and virtualizer and manualFiltering. I'm trying to upgrade to MRT 1.9.1 and I encountered the following bug: when I select "Filter by a column" and enter something that returns no results, the correct message is displayed (No results found). But when I enter another character to filter by, the screen goes completely blank and I get an error:
![error](https://user-images.githubusercontent.com/50102168/227001089-6efed6be-f824-4dbf-9c38-a998b0302f9f.png)

I tried out several MRT versions and found out that this bug was introduced in 1.7.4 so I thought Virtual is probably causing this. And yes. I commented out everything in our code related to Virtual and the problem disappeared.

### Minimal, Reproducible Example - (Optional, but Recommended)

Our table props:
      columns={columns}
      data={flatData}
      enablePagination={false}
      enableGlobalFilter={false}
      enableTopToolbar
      enableRowSelection
      getRowId={(originalRow) => originalRow.id}
      enableRowVirtualization
      manualFiltering
      manualSorting
      rowVirtualizerInstanceRef={rowVirtualizerInstanceRef}
      rowVirtualizerProps={{ overscan: 12 }}

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
hmmm. I cannot quite reproduce this in the [virtualized example](https://www.material-react-table.com/docs/examples/virtualized). Might have something to do with the `manual*` props

**Comment by KevinVandy** [comment]
If you are using `scrollToIndex`, temporarily wrap it in a `try/catch`. This is a problem with TanStack Virtual itself. I'll investigate further

```js
useEffect(() => {
    //scroll to the top of the table when the sorting changes
    try {
      rowVirtualizerInstanceRef.current?.scrollToIndex?.(0);
    } catch (error) {
      console.error(error);
    }
  }, [sorting]);
```
