### ISSUE TITLE
Error when switching from virtualized to non-virtualized table

### ISSUE THREAD

**Issue by DiegoBM** [KevinVandy/material-react-table#441]
### material-react-table version

v1.9.1

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Following the recommendation of not using the virtualized grid if the set of rows is small I decided to set the "enableRowVirtualization" property dependent on the size of the dataset since I receive a variable number of rows. The problem comes when the previous render the property was false (a small number of rows), and the next render it receives a larger number of rows switching into virtualized mode, in that case the component will cause the next warning:

```
Warning: React has detected a change in the order of Hooks called by MRT_TableBody. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useMemo                    useMemo
2. useMemo                    useMemo
3. undefined                  useReducer
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

that will turn into this error:

```
Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom.development.js:16507:1)
    at updateReducer (react-dom.development.js:16568:1)
    at Object.useReducer (react-dom.development.js:17898:1)
   ....
```

### Minimal, Reproducible Example - (Optional, but Recommended)

Simply set the property "enableRowVirtualization" to some conditional like
`enableRowVirtualization={data.length > 200}`
Then as you start the app pass it an empty array as usual, and after that load a dataset larger than 200 rows

### Terms

- [ ] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The [docs](https://www.material-react-table.com/docs/guides/virtualization) explicitly say that this is not supported

> WARNING: Don't enable row or column virtualization conditionally. It may break React's Rule of Hooks, and/or cause other UI jumpiness.

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/28243511/227306227-34158a52-6d31-4a4f-8ae9-4c33fbffb999.png">

**Comment by KevinVandy** [comment]
@DiegoBM The only other option would be for me to have the virtualizer always on internally. So react-virtual would run whether or not it was needed or was being used to virtualize the rows. This is all because `useVirtualizer` is a react hook, and cannot be called conditionally.

Here is the relevant code where this happens internally in MRT if you are curious or have suggestions: https://github.com/KevinVandy/material-react-table/blob/main/packages/material-react-table/src/body/MRT_TableBody.tsx#L121

**Comment by KevinVandy** [comment]
after this convo, I realize this probably should be refactored/improved, but it will be a bit of a bundle size increase to implement.

**Comment by DiegoBM** [comment]
Thanks for the feedback @KevinVandy. I was reviewing that code this evening when I realised that it came from there. The only thing I could think of was to always call `useVirtualizer` even if it's result is not used later on, since being a hook should never be called conditionally anyways, but I presume that you made it conditional because there is some sort of noticeable overhead resulting of calling `useVirtualizer`?.

Otherwise I guess that the only option would be either to recreate the table with keys as I did, or to render two different tables for the virtualized and non-virtualized case, which we can do on our end as well.

**Comment by KevinGhadyani-Okta** [comment]
Another option is to pass an "on/off" prop to the virtualizer hook. Not ideal, but it's a possible solution.

My issue is that the error doesn't match the issue. It doesn't say "don't use the virtualizer dynamically", it says something about `useReducer` which isn't clear.

I had an infinite-scrolling table which dynamically kicked in the virtualizer past 50 items and don't remember seeing this error, but in another app with 200 entries per page, this error was causing his app to error.

**Comment by KevinVandy** [comment]
After even more consideration over the past year, I think we're going to keep the requirement that virtualization can never be enabled conditionally. It already causes other CSS/feature changes under the hood depending on whether or not it is enabled, and having it switch between different css layout modes at a certain row count is jolting. It's just best to always have it enabled if you think you need it.

The warning in the docs about it causing extra overhead is slightly true, but it is there mostly to discourage anyone who is already using pagination set to 10 rows to enabling it for now good reason.

Still open to suggestions (though I don't really want to have MRT always running virtualization logic even when it's not being used), but will close this for now.

**Comment by KevinGhadyani-Okta** [comment]
Thanks for confirming! 👍
