### ISSUE TITLE
Need to print MRT through Print icon 

### ISSUE THREAD

**Issue by sandeep1407** [KevinVandy/material-react-table#442]
### material-react-table version

v1.8.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

not sure it has opened earlier or not. 
I am trying to print Material React table grid only along with header of the page using toolbar Print Icon instead of print whole page.  I have many tabs on the pages and each tabs are using material react table grid so when I am trying to print specific tabs data from material react table then its printing whole pages with all tabs.
can you please add the functionality into material react table to choose specific area of the page and can be print it through print icon toolbar.

### Minimal, Reproducible Example - (Optional, but Recommended)

you can look any example in code sandbox with print icon to reproduce it.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Printer specific CSS and features has not really been in the scope of this project. I assume devs can write any CSS media queries that they need to format for printing themselves.

I'm assuming you just need add stuff like

```js
muiTablePaginationProps={{
  sx: { 
    '@media print': { display: 'none' }
  }
}}

in a few places

**Comment by sandeep1407** [comment]
> Printer specific CSS and features has not really been in the scope of this project

Thanks for your suggestion Kevin. 
I thought it can be add a feature in this project to provide the functionality for choose what want to print.

its just my thought. thanks again.
