### ISSUE TITLE
[BUG] Pagination does not properly work with expandable rows feature

### ISSUE THREAD

**Issue by nichita-pasecinic** [KevinVandy/material-react-table#446]
### material-react-table version

1.9.2

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

1. Open: https://stackblitz.com/edit/github-mwon5r?file=src%2FTS.tsx
2. Expand all rows 
3. Go to second page (via pagination)
![image](https://user-images.githubusercontent.com/98735377/228161082-2d0c0b95-9eb1-4cc2-8ab4-10ff43e9121d.png)

4. Collapse all rows 
![image](https://user-images.githubusercontent.com/98735377/228161176-fed2e76f-024d-4f3e-944a-1681be3fde48.png)

No data overlay will be shown

Expected: Page index to reset to a valid value 

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-mwon5r?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

Expanded: 
![image](https://user-images.githubusercontent.com/98735377/228160829-d248c321-af16-4aef-b668-6b70d872b213.png)

After collapse:
![image](https://user-images.githubusercontent.com/98735377/228160756-116cb2ea-4ffd-4cde-bd1d-5b5e7a01106a.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This should be fixed in v1.9.3
