### ISSUE TITLE
Table height does not fix itself after grouped rows collapsed and reopened

### ISSUE THREAD

**Issue by akhfaern** [KevinVandy/material-react-table#450]
### material-react-table version

1.9.2

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

1. create a grouped table
![image](https://user-images.githubusercontent.com/5367389/229114241-94376db7-fb58-4dae-917e-13837c342078.png)
2. collapse all rows
3. table height is now reduced
4. go to last rows
5. try to reopen
6. rows does not appear because of table height is reduced
7. you can not see the last row results
![image](https://user-images.githubusercontent.com/5367389/229114664-217208f9-5926-47ca-b2b7-6c8e4276365f.png)

8. you can see the same result on aggregation-and-grouping sample on website

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/guides/aggregation-and-grouping

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I can't really reproduce this in the way you are describing

**Comment by akhfaern** [comment]
actually i just found out that last rows after expanding the group are sent to next page because of page size. you can see it yourself at your own web page demo
https://www.material-react-table.com/docs/guides/aggregation-and-grouping#aggregation-grouping-example

just close all expanded rows first then go to last row and try to re expand it. you will see expanded rows are not shown on the same page but on the next page. but expected behaviour should be on the same page since it is grouped at the first page.

**Comment by KevinVandy** [comment]
It would be a pretty tedious calculation to figure out which pageIndex the table needs to jump to in order to keep some of the rows that were in view in the same view. Not sure that behavior is even needed.

**Comment by akhfaern** [comment]
people thinks expanded rows are still hidden and it is buggy even tough it is expanded and displayed on the second page. every data grid has this feature behaves like the one i said. you can check it yourself

**Comment by KevinVandy** [comment]
Ok, how would you implement it?

**Comment by KevinVandy** [comment]
After re-reading your problem here a bit more, I think you just missed that there is a `paginateExpandedRows` prop that you can set to false that will fix your problem.

**Comment by KevinVandy** [comment]
Closing this as the solution is simply 

`paginateExpandedRows={false}`

and it will behave how you want it to.
