### ISSUE TITLE
After building the app filters doesn't work!

### ISSUE THREAD

**Issue by MateoStackWizard** [KevinVandy/material-react-table#463]
### material-react-table version

v1.9.3

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

It is really hard to reproduce it - but basically this is how the things go.
On my localhost everything works perfectly fine - but after I build the app the filters on the table does not work!
Immediately after typing something on column filter or global filter I am getting errors (._i3 for column filter and ._i5 for global filter)
After trying to debug it I have found that some values does not get the value in the loop and I can't understand why.
The screenshots are provided below and I think that something is not right in line 110 in the "resolvedGlobalFilters[i]!".

### Minimal, Reproducible Example - (Optional, but Recommended)

It is hard to reproduce.

### Screenshots or Videos (Optional)

Here is the error for global filter
<img width="529" alt="Global filter error" src="https://user-images.githubusercontent.com/126579720/231183739-5b2c8144-8c60-4172-889e-a7b3ae0c1138.png">
Here is the error for column filter
<img width="530" alt="Column filter error" src="https://user-images.githubusercontent.com/126579720/231183759-f6d8377a-f389-4c54-b60a-61c320ca34f2.png">
Here is the breakpoint where my currentGlobalFilter is undefined
<img width="245" alt="currentGlobalFlter" src="https://user-images.githubusercontent.com/126579720/231183771-727b862b-8ce4-4861-b672-eda31b8684b8.png">
Here is the breakpoint where resolvedGlobalFilter have value
<img width="296" alt="resolvedGlobalFilter" src="https://user-images.githubusercontent.com/126579720/231183776-82194645-4fde-455e-9a12-5535f10157aa.png">

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by MateoStackWizard** [comment]
Turns out something didn't transpiled correctly while building the project - upgrading to React 18.0.2 and react-scripts to 5.0.1. solved the issues.

**Comment by KevinVandy** [comment]
There was a similar issue with Next.js and TanStack Table a while back. Wonder if there is some underlying build tool at a certain version that caused this problem.

https://github.com/TanStack/table/issues/4610
