### ISSUE TITLE
[Styles Bug 🐛]: `compact` density show unnecessary scrollbar (overflow) 

### ISSUE THREAD

**Issue by nichita-pasecinic** [KevinVandy/material-react-table#476]
### material-react-table version

1.10.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

Just by using 
```tsx
 initialState={{
        density: 'compact',
      }}
```
It adds an unnecessary scrollbar to the table container. 

With default density the styles are ok (check bellow screenshots)

Thanks!

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-8af2aq?file=src%2FJS.js,src%2FTS.tsx,src%2FmakeData.ts

### Screenshots or Videos (Optional)

With compact density:
![image](https://user-images.githubusercontent.com/98735377/232488248-11d54bbc-b4a4-44a2-861a-d834def26f77.png)

With default density is ok:
![image](https://user-images.githubusercontent.com/98735377/232488344-986ed684-f2b7-4341-a434-f3e7a47d8a35.png)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by mm0hammadi** [comment]
In what resolution is there scroll?
 Is it in small size or large size?
I tested the link and it looks ok in large size!

**Comment by mm0hammadi** [comment]
also you can add this line    enableDensityToggle={false}

**Comment by KevinVandy** [comment]
This bug will be fixed in the next patch

**Comment by nichita-pasecinic** [comment]
@mm0hammadi it is on smaller screen sizes (you can resize the browser window - until the scroll appears)

@KevinVandy thank you! 🚀

**Comment by nichita-pasecinic** [comment]
@mm0hammadi here is the recording, I hope now it is clear ))
https://drive.google.com/file/d/18IhiPvZIDVa9ebiBiKLS5_b1vWQZSDD5/view

Thanks

**Comment by KevinVandy** [comment]
fixed in v1.11.0
