### ISSUE TITLE
No Records Fallback component 

### ISSUE THREAD

**Issue by nichita-pasecinic** [KevinVandy/material-react-table#483]
### material-react-table version

1.10.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

Currently the `No Records` label is inside the table row and a td which makes it hard to styles.
Also there is a bug with resizing 

On first render with a smaller screen size it centers the text like so: 
![image](https://user-images.githubusercontent.com/98735377/233160697-a4b3645e-a598-486e-893f-649061e76670.png)

But in case user scrolls inside the table the text centring is not respected anymore (it scrolls with the entire table)
![image](https://user-images.githubusercontent.com/98735377/233160836-9dd4980d-fe38-4c22-9b1e-c748f0e82c48.png)

The same is equivalent if user first opens the table on smaller screen size (as above) and then resizes the browser tab 
![image](https://user-images.githubusercontent.com/98735377/233161070-fdbc5f94-56af-4a58-a01c-558d4ac727e0.png)

In my use case, there is a more complex fallback component to use inside the table than just the label, and it needs to always needs to be centered within table container width (if there are more columns, such that the horizontal scroll is required, the "No data overlay" should remain on the same position and not move with the table)

As a suggestion - with "No data overlay" will be much easier to work if it would not be within table, as there is no data, it is possible to render just the headers and have a fallback container for such use cases.

An example could be the "No data overlay" from MUI Data grid component (it behaves same as described above)
https://stackblitz.com/run?file=demo.tsx 

![image](https://user-images.githubusercontent.com/98735377/233162416-4945f6c5-126b-4109-b2b7-a96b49331368.png)

Thanks again!

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-uycgvn?file=src%2FTS.tsx

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
@nichita-pasecinic Are you aware of the new `renderEmptyRowsFallback` prop that was introduced in v1.10.0? You should be able to customize all of this.

**Comment by nichita-pasecinic** [comment]
@KevinVandy sure, I've used it, but found out that for more complex layouts it does not work and 'cause it is under table row and it's hard to style. A better alternative would be a container that isn't under table layout, but is separate.

Currently the `renderEmptyRowsFallback` allows only slightly to customize the empty table state
