### ISSUE TITLE
resize works incorrectly if you name the accessor as utf-8. (> 1.8.4)

### ISSUE THREAD

**Issue by hithats** [KevinVandy/material-react-table#487]
### material-react-table version

>1.8.5

### react & react-dom versions

v.17.0.2

### Describe the bug and the steps to reproduce it

Thanks for the great package.

From v1.8.5 onwards, column resize will behave strangely if you name the accessor as utf-8. In 1.8.4 it works fine. 

I'm wondering if accessor naming no longer supports utf-8, or if it's a temporary bug and I should wait for a fix.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/practical-carlos-pggxwn

### Screenshots or Videos (Optional)

`> 1.8.4`

![image](https://user-images.githubusercontent.com/75402771/233770105-9412523a-47e8-47ff-833a-9f03550fb385.png)

`=< 1.8.4`

![image](https://user-images.githubusercontent.com/75402771/233770672-8d092756-beeb-4f45-8319-b57d2e7c7f53.png)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
To shed a bit of light on this, internally, the column `ids` are run through this regex function to replace any invalid characters that would not be valid as a CSS var with underscores

https://github.com/KevinVandy/material-react-table/blob/main/packages/material-react-table/src/column.utils.ts#L354

The good news is you can keep your accessorKeys as they are. I just recommend also adding an `id` to each of your column definitions. Use an id that looks like a JavaScript variable for best results. 

For example:

```ts
 {
        accessorKey: "성",
        id: 'firstName', //JS/CSS friendly id for internal processing
        header: "First Name", //uses the default width from defaultColumn prop
      },
      {
        accessorKey: "이름",
        id: 'lastName', //JS/CSS friendly id for internal processing
        header: "Last Name",
        // enableResizing: false, //disable resizing for this column
      },
```

**Comment by hithats** [comment]
Thank you. id works fine!
