### ISSUE TITLE
Expanded sub rows does not look like tree

### ISSUE THREAD

**Issue by QusaiAlghalil** [KevinVandy/material-react-table#492]
### material-react-table version

1.10.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

expanded sub rows should bee looks like a tree as same as the demo you have provide.
I've  copied and paste the code you provided to the demo but seems like the sub rows sign (arrow sign)  is at the same alignment to the main rows sign

### Minimal, Reproducible Example - (Optional, but Recommended)

..

### Screenshots or Videos (Optional)

<img width="864" alt="material react table" src="https://user-images.githubusercontent.com/113530721/234112524-8f481ef5-8477-40e9-8410-f48c75e20fbc.png">

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
If you have any CSS that changes the padding of `td` elements, that would cause this. Make sure you are not overriding any table cell `padding-left` or `padding` properties globablly in your app.

**Comment by QusaiAlghalil** [comment]
> If you have any CSS that changes the padding of `td` elements, that would cause this. Make sure you are not overriding any table cell `padding-left` or `padding` properties globablly in your app.

I did not see any CSS that changes the padding of 'td' elements.
btw how could I set default selected (checked) rows  ?

**Comment by KevinVandy** [comment]
@QusaiAlghalil Inspect element on your table cells and see what paddings are being set. Or if you have some weird alignment css coming from somewhere. That's the only way these indentations would get messed up.
