### ISSUE TITLE
muiTablePaginationProps={{rowsPerPage}} is Working

### ISSUE THREAD

**Issue by dnjsgur0629** [KevinVandy/material-react-table#498]
### material-react-table version

1.9.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I am aware that in #411, rowsPerPage was omitted because muiTablePaginationProps={{rowsPerPage}} did not work as expected.

I am customizing the pagination in my code and I was surprised to see that "rowsPerPage" was omitted at some point since it works perfectly fine for me as a prop. 
https://github.com/KevinVandy/material-react-table/blob/1c86f4d46a9a168e73c824be16e1ba1e555d49fc/packages/material-react-table/src/MaterialReactTable.tsx#L846-L850
So, There are cases where "rowsPerPage" works well, and since it is the simplest way to control pagination, I think it would be better to include "rowsPerPage" in the TS definition again. What do you think about this?

### Minimal, Reproducible Example - (Optional, but Recommended)

case of muiTablePaginationProps={{rowsPerPage}} works:
[![Edit material-react-table-pagination](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-react-table-pagination-tg0xrw?fontsize=14&hidenavigation=1&theme=dark)

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Sorry, closing this as "won't do" because it encourages going around and overriding TanStack Table state. Doing it the way you do in your sandbox example makes all of the internal pagination values incorrect. If you insist doing it this way in your own codebase, you have @ts-ignore to fallback on.
