### ISSUE TITLE
Adding initialState prop makes positionActionsColumn="last" not work

### ISSUE THREAD

**Issue by ryanmk54** [KevinVandy/material-react-table#5]
### Describe the bug

`positionActionsColumn="last"` works correctly without the `initialState` prop
After adding 
```
const initialState = {
  density: "compact"
} as const;
```
and reloading, the actions column is the first column again.

### Your minimal, reproducible example

https://codesandbox.io/s/infallible-dubinsky-555h5q?file=/src/TS.tsx:469-524

### Steps to reproduce

1. The actions column is in the first column when first loading the page

### Expected behavior

As a user, I am expecting the `positionActionsColumn="last"` to put the actions column in the last column, but it is still in the first column.

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1811468/174846302-525aaafb-8fde-4f96-b439-039a83b54543.png)

### material-react-table version

0.13.1

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed as of V0.13.3 along with other column ordering fixes
