### ISSUE TITLE
Using header group disables column ordering in header

### ISSUE THREAD

**Issue by oliverfrost1** [KevinVandy/material-react-table#503]
### material-react-table version

v1.11.10

### react & react-dom versions

Your website

### Describe the bug and the steps to reproduce it

You cannot drag in this one: 
![image](https://user-images.githubusercontent.com/41832493/235144879-47c752f5-c71a-441d-9bb2-2f505b7d9da7.png)

When using header groups. 

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-eykhrr?file=src%2FTS.tsx

vs this one working: 
https://stackblitz.com/github/KevinVandy/material-react-table/tree/main/apps/material-react-table-docs/examples/enable-column-ordering/sandbox?file=src%2FTS.tsx

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was an intentional implementation, because generating the UI with toggles for repeated headers top (when they get spread across the whole table) starts to look weird. If someone rewrote this part and handled all of the edge cases with multiple top headers being repeated, I'd merge it though.

**Comment by oliverfrost1** [comment]
Ahh, I hadn't even thought about that. My use case was that the user would only be allowed to drag columns about within one header group, so that problem with multiple headers hadn't crossed my mind. 

Could the header groups disappear when columns are dragged onto another part of the table, where there is another header group? That would seem kind of intuitive, given that they are no longer "grouped".
