### ISSUE TITLE
Virtualization perfomance issue

### ISSUE THREAD

**Issue by fofyga** [KevinVandy/material-react-table#505]
### material-react-table version

1.11.0

### react & react-dom versions

18.1.0

### Describe the bug and the steps to reproduce it

Hi. I have table with 10 000 row, like your example. I set enableColumnVirtualization={true} and enableRowVirtualization={true} props.
When i try to scroll table It happen very slow, because you are use sx prop in MRT_TableBodyCell.tsx and MRT_TableBodyRow.tsx. It's generate new class for each row when table scrolling. And I have warning in console from material ui "Over 200 classes were generated for component MuiTableRow-root with the id of "MuiTableRow-root-kvnHKj".
Consider using the attrs method, together with a style object for frequently changed styles.
E....."

In production mode, it works faster, but not enough.

See my screenshot, this is added indefinitely when you scroll the table

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/github/KevinVandy/material-react-table/tree/main/apps/material-react-table-docs/examples/virtualized/sandbox?file=src%2Fmain.tsx,package.json,src%2FTS.tsx

### Screenshots or Videos (Optional)

![image](https://user-images.githubusercontent.com/18482720/235300525-8ba9fa0b-c098-48e4-b821-4f26d4466e59.png)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by fofyga** [comment]
If you use emotions, it works faster, but it also works. A tag is generated for each line.

**Comment by KevinVandy** [comment]
There are definitely performance wins still to be had here

**Comment by dikshantbrahma** [comment]
@KevinVandy any chance this can be fixed? Running into the same issue on my end as well.

**Comment by KevinVandy** [comment]
@dikshantbrahma @fofyga Row Virtualization performance has been slightly improved in v1.11.3. A single emotion class is generated for each row now after moving the `translateY` style to the `style` prop instead of `sx`.
