### ISSUE TITLE
Column pinning results in empty space between a regular pinned column and a pinned mrt-row-actions column.

### ISSUE THREAD

**Issue by nthNathan** [KevinVandy/material-react-table#509]
### material-react-table version

1.9.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Pinning and unpinning various columns on the right side (including the "mrt-row-actions" column) results in the empty space shown in the screenshots. It may be necessary to resize the table/page width for the empty space to be visible.

### Minimal, Reproducible Example - (Optional, but Recommended)

List of the relevant props I am using:

initialState={{
   columnPinning: { right: ["mrt-row-actions"] },
}}
enableHiding
enablePinning
enableRowActions

### Screenshots or Videos (Optional)

![Screenshot (498)](https://user-images.githubusercontent.com/118927705/235809774-1feab31b-1f4d-4a84-a99c-f78045163e72.png)
![Screenshot (497)](https://user-images.githubusercontent.com/118927705/235809795-440c0d33-9697-42b4-ba96-b20fc32a288a.png)
Note that you can see some visual customization I've done to the row actions column, but the bug still repro'd when I removed all of the customization.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by nthNathan** [comment]
No, I don't have virtualization enabled. Should I?

**Comment by KevinVandy** [comment]
> No, I don't have virtualization enabled. Should I?

no, virtualization can cause bugs with column pinning

**Comment by ismailhelmy** [comment]
I am facing the same exact issue, only in "pin to right" only. However in "pin to left" it is working fine. @nthNathan

**Comment by KevinVandy** [comment]
I'm aware of this issue for potential right pinning spacing problems. I might need to add a new feature to TanStack Table to fix this. Need proper end/right space tracking.

**Comment by Linos2508** [comment]
Hi @KevinVandy I'm facing same issue as ismailhelmy, do you have any ETA for a potencial fix?

**Comment by KevinVandy** [comment]
@nthNathan @Linos2508 @ismailhelmy This should be fixed in v1.11.4
