### ISSUE TITLE
Filter with input type=date loses value

### ISSUE THREAD

**Issue by emilianot** [KevinVandy/material-react-table#527]
### material-react-table version

v1.11.3

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

When a column has `muiTableHeadCellFilterTextFieldProps = { type: "date" }` it loses the value after selecting the date.

Browser Warning: `The specified value "Mon May 15 2023 21:00:00 GMT-0000" does not conform to the required format, "yyyy-MM-dd`.

Tested on:
- Chrome 112.0.5615.138
- Microsoft Edge Version 113.0.1774.35
- Firefox Version 113.0

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/elegant-gould-94s9uj?file=%2Fsrc%2FTS.tsx%3A10%2C9-10%2C64

### Screenshots or Videos (Optional)

![reactmtab](https://github.com/KevinVandy/material-react-table/assets/29287315/5762cce6-db8e-4bed-a66c-3112c2d3dea6)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by khalidMhd** [comment]
@emilianot
Have you fixed this issue? I am facing the same issue.

**Comment by rhettl** [comment]
I too have this issue and haven't found a solution.

**Comment by KevinVandy** [comment]
Closing this because the `filterVariant: 'date'` and others are now available where these problems will not exist.
