### ISSUE TITLE
1.11.3 Introducted virtualization crashing when screen is squeezed 

### ISSUE THREAD

**Issue by oliverfrost1** [KevinVandy/material-react-table#535]
### material-react-table version

1.11.3

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

On the Edge browser, if you squeeze a virtualized table, it will crash the page. I'm not quite sure what is causing it, but I think that it is the rows resizing vertically because of word-wrapping that is somehow messing up the virtualization. Our CSS setup is in the linked stackblitz.

It doesn't happen on 1.11.2, so it was probably introduced in 1.11.3. 

### Minimal, Reproducible Example - (Optional, but Recommended)

The bug happens under very certain circumstances, that I'm having a hard time reproducing. I have made a stackblitz that is very similar to our production environment, but it still can't reproduce the bug. It only happens with few rows 4-10, but with more rows visible, it doesn't happen.

I can't make it happen on Firefox. This is a stackblitz that is close to our production environment: https://stackblitz.com/edit/github-yi44cs?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

Video of it happening (excuse the white box, screenshots of stack trace below:

https://github.com/KevinVandy/material-react-table/assets/41832493/b697f9db-1482-46ab-948c-5cda652bed32

![1](https://github.com/KevinVandy/material-react-table/assets/41832493/b759f8f4-3004-4aa6-9afc-08b268137c84)
![2](https://github.com/KevinVandy/material-react-table/assets/41832493/57281f86-4fb4-4e98-86d9-9ad4870525bf)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I can't get this to happen on my own edge on mac browser yet. Try adding back this: (was removed internally to fix firefox issue last week)

```tsx
rowVirtualizerProps={{
  measureElement: (element) => element?.getBoundingClientRect().height,
}}
```

We might need this internally now

```tsx
rowVirtualizerProps={{
  measureElement:
    navigator.userAgent.indexOf('Firefox') === -1
      ? (element) => element?.getBoundingClientRect().height
      : undefined,
}}
```

so that we don't crash any browser.

**Comment by KevinVandy** [comment]
@oliverfrost1 Try v1.11.4

**Comment by oliverfrost1** [comment]
@KevinVandy 1.11.4 fixes the issues. I tried everything I could think of to crash it on both Edge and Firefox. Thank you very much, Kevin!
