### ISSUE TITLE
`onFilterChanged` argument is wrong (?)

### ISSUE THREAD

**Issue by githorse** [KevinVandy/material-react-table#537]
### material-react-table version

v1.11.3

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

I expected `onColumnFiltersChange` to be called with the updated [`ColumnFiltersState`](https://tanstack.com/table/v8/docs/api/features/filters#state), but the argument `e` is a function instead:

```
function onColumnFiltersChange(e: any) {
  console.log(`onColumnFiltersChange: argument should be type object, I think, but is type ${typeof e}:`, e)
}

return (
  <MaterialReactTable
    columns={columns}
    data={data}
    enableColumnFilters={true}
    onColumnFiltersChange={onColumnFiltersChange}
  />
)
```

This seems to be a bug, or else I'm misunderstanding how this is supposed work -- if so, it would be great if the docs could explain this callback in more detail.

### Minimal, Reproducible Example - (Optional, but Recommended)

see [Stackblitz demo](https://stackblitz.com/edit/github-6r9xwu-jjeg96?file=src%2FTS.tsx)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I recommend reading the State Management guide in the docs
