### ISSUE TITLE
renderRowActionMenuItems is rendering a small white rectangle when the returned value is and empty array or null

### ISSUE THREAD

**Issue by skiabox** [KevinVandy/material-react-table#548]
### material-react-table version

v1.11.3

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

It is a white rectangle that is easily reproduced if the user return an empty array in this attribute.

### Minimal, Reproducible Example - (Optional, but Recommended)

renderRowActionMenuItems={({ closeMenu, row, table }) => {
                // check if selectedDetail is not null and matches the current row id
                if (selectedDetail && selectedDetail === row.id) {
                  return [
                    <MenuItem
                      key={0}
                      onClick={() => {
                        setIsOpen(true);
                        console.log("Add Obligation clicked!");
                        console.log("row id: ", row.id);
                        closeMenu();
                      }}
                      sx={{ m: 0 }}
                    >
                      <ListItemIcon>
                        <AddCircleIcon />
                      </ListItemIcon>
                      Add Obligation
                    </MenuItem>
                  ];
                } else {
                  // return empty array to prevent the menu from being rendered
                  return [];
                }
              }}

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
In what situations is row actions enabled, but no actions are specified?

**Comment by Mephistofeles** [comment]
Yes, if you return an empty array from renderRowActionMenuItems. I have the same problem.

**Comment by solovevayaroslavna** [comment]
I have the same problem. Any workaround?
![image](https://github.com/KevinVandy/material-react-table/assets/90199600/f0ea1401-2998-4907-b081-96014a70aae5)

**Comment by KevinVandy** [comment]
instead of passing an empty array when there are no actions, pass undefined

**Comment by solovevayaroslavna** [comment]
workaround, which our team used: we added our custom menu button  (https://v1.material-react-table.com/docs/guides/row-actions#add-row-action-buttons) with MoreHorizIcon from Mui, and added cusom menu close/open logic where we solved the problem with the 'empty array'
