### ISSUE TITLE
Issues with manual filter when change mode

### ISSUE THREAD

**Issue by tdanh2k** [KevinVandy/material-react-table#55]
### material-react-table version

v0.40.11

### Describe the bug and the steps to reproduce it

1. Create table with these props: manualFiltering, enableColumnFilters, enableColumnFilterModes, onColumnFiltersChange.
2. Manage the customFilter state.
3. Open column filter, type anything in the box.
4. Then switch modes. The column that has its mode changed will not display when capture in useEffect, but the input still persists (It should also clear the input or keep the filter when change modes).

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://codesandbox.io/s/material-react-table-check-jpysue?file=/src/App.js

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The filter should be reset properly now upon changing filter modes as of `v0.41.0`
