### ISSUE TITLE
`onGroupingChanged` is called with function

### ISSUE THREAD

**Issue by githorse** [KevinVandy/material-react-table#550]
### material-react-table version

v11.1.3

### react & react-dom versions

v18.20.0

### Describe the bug and the steps to reproduce it

`onGroupingChange` is called with a function, not a `grouping` state:

```
<MaterialReactTable
  onGroupingChange={(grouping) => console.log(`onGroupingChange:`, typeof grouping)}
/>

// onGroupingChange: "function"
```

By contrast, other callbacks like `onColumnOrderChange` are called with the relevant state:

```
<MaterialReactTable
  onColumnOrderChange={(columnOrder) => console.log(`onColumnOrderChange:`, columnOrder)}
/>

// onColumnOrderChange: ["foo", "bar"]
```

It looks like these callbacks are designed to work with [React `setState` functions](https://react.dev/reference/react/useState#setstate), so they might be called either with the value or a function from old value to new. (Can't say for sure because I can't find any definition of `OnChangeFn` in MRT or Tanstack docs.) So this would probably be transparent to me if I just hook my state directly up to React `setState` -- but I'm doing something slightly more complicated (otherwise why would I be managing state?) and will have to handle these callbacks myself.

Questions:
2. Do we need the function (`oldState => newState`) style? It would certainly be more convenient to just get the new state as the argument.
3. If we need to use the functional style, could the callbacks be made consistent?

### Minimal, Reproducible Example - (Optional, but Recommended)

see [CodeSandbox example](https://codesandbox.io/p/sandbox/pedantic-sea-cwdo9b?file=%2Fsrc%2FTS.tsx%3A112%2C1)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
As explained in the [state management docs](https://www.material-react-table.com/docs/guides/table-state-management#add-side-effects-in-set-state-callbacks), this is just how it works. The `on[StateName]Change` functions are for hoisting state. They are compatible with React setState functions.
