### ISSUE TITLE
TypeError: e.replaceAll is not a function

### ISSUE THREAD

**Issue by ahmedfeki** [KevinVandy/material-react-table#557]
### material-react-table version

1.8

### react & react-dom versions

18

### Describe the bug and the steps to reproduce it

The error happened in the build  in android device 
not sure how to reproduce it 
following the chunk 
it happens here : 
`Es=function(e){return e.replaceAll(".","_").replaceAll(" ","_").replaceAll("+","_").replaceAll("(","_").replaceAll(")","_")},`

### Minimal, Reproducible Example - (Optional, but Recommended)

`Es=function(e){return e.replaceAll(".","_").replaceAll(" ","_").replaceAll("+","_").replaceAll("(","_").replaceAll(")","_")},`

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Update the version of material react table. This is a bug that was solved months ago for older browsers.
