### ISSUE TITLE
Some props do not work

### ISSUE THREAD

**Issue by quyle92** [KevinVandy/material-react-table#562]
### material-react-table version

1.8.2

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I try to add some additional props related to `@mui/material`  to my table but it seems some of them do not work. 

1/ I set  `manualFiltering` to `true` to implement server-side pagination + column filtering.
But all props specified `muiTableHeadCellFilterCheckboxProps` does not help in changing styles.

2/ I created custom numbered-pagination component by using `Pagination` component from `@mui/material` and I want to include that component at table's footer, but using all 3 `muiTableFooterCellProps`, `muiTableFooterProps` , `muiTableFooterRowProps` fails.

### Minimal, Reproducible Example - (Optional, but Recommended)

MaterialReactTable
                    ...
                    muiTableFooterCellProps={{
                             children: <Pagination {...props} />
                    }}
                    muiTableFooterProps={{
                             children: <Pagination {...props} />
                    }}
                    muiTableFooterRowProps={{
                             children: <Pagination {...props} />
                    }}
                    // none of these props take effect
                    muiTableHeadCellFilterCheckboxProps={{
                        checkedIcon: CheckCircleIcon,
                        color: 'error',
                        onChange: (event) => {
                            console.log(event);
                        },
                        size: 'small',
                    }}
                />

### Screenshots or Videos (Optional)

![mui-table](https://github.com/KevinVandy/material-react-table/assets/59790219/04c88738-4ffe-4921-9744-006656426926)

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
children props don't work, except in special circumstances where coded it to allow it, like muiTableBodyProps

**Comment by quyle92** [comment]
OK thanks for your reply...  
Only children props don't work or other props don't work either? And is there any workaround?
Also how about the`muiTableHeadCellFilterCheckboxProps`? Is there any thing wrong with my code that prevent it to work?

**Comment by KevinVandy** [comment]
The checkbox props there only applies to the checkbox filter variant. I guess we could also repurpose them for multi select. Will have to think about that one

**Comment by quyle92** [comment]
I've just switched `filterVariant` to `select` but its checkbox filter does not have icon by default.
Here it is:
![image](https://github.com/KevinVandy/material-react-table/assets/59790219/1fd71fcb-d0d5-4287-b242-23b29ba2a887)

**Comment by quyle92** [comment]
> checkbox filter variant

sorry but does `filterVariant: select` equivalent to "checkbox filter variant"?

**Comment by KevinVandy** [comment]
@quyle92 No it is for the "checkbox" variant that only shows a checkbox. Not for selects

<img width="491" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/bcb6a2a3-996d-4bd4-804b-11153b6d9932">
