### ISSUE TITLE
"Expand" column width is dynamic and cause a large width

### ISSUE THREAD

**Issue by nicolaeClichici** [KevinVandy/material-react-table#564]
### material-react-table version

1.11.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

Hi!
Because of passing a default size for columns, expand column become very large. Is there any method to keep `defaultColumn={{ size: x}}` functionality and to make expand column "pinned" with static width?

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/charming-satoshi-6fd72z?file=/src/App.tsx

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/113600769/470376f1-de68-48a2-88e6-d7c7ddc16cf3)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Just set the `size` column option for the column. I have a whole section in the docs for this exact scenario https://www.material-react-table.com/docs/guides/display-columns#customize-built-in-mrt-display-columns

**Comment by nicolaeClichici** [comment]
``` 
defaultColumn={{ size: 50 }}
displayColumnDefOptions={{ "mrt-row-expand": { size: 10 } }}
 ```
 
 This is now working, defaultColumn overrides the size from mrt-row-expand

**Comment by denispalii** [comment]
Hi guys, any updates on this ? :)  
Thanks.

**Comment by githorse** [comment]
I also would really like to fix the width of the actions & command columns. See [relevant discussion](https://github.com/KevinVandy/material-react-table/discussions/650).

**Comment by nathan-fletcher-seagull-com** [comment]
I had some success with flexGrow: 0.

layoutMode="grid"

displayColumnDefOptions={{
"mrt-row-actions": {
                  size: 40,
                  maxSize: 40,
                  minSize: 40,
                  muiTableBodyCellProps: () => ({
                     sx: {
                        flexGrow: 0,
                         },
                  }),
               },

**Comment by KevinVandy** [comment]
> I had some success with flexGrow: 0.
> 
> layoutMode="grid"
> 
> displayColumnDefOptions={{
> "mrt-row-actions": {
>                   size: 40,
>                   maxSize: 40,
>                   minSize: 40,
>                   muiTableBodyCellProps: () => ({
>                      sx: {
>                         flexGrow: 0,
>                          },
>                   }),
>                },

Just use the v2 layout mode grid-no-grow feature. This is a solved problem now
