### ISSUE TITLE
Between Inclusive Filter always has a value, clear filter menu is always active

### ISSUE THREAD

**Issue by BennyAlex** [KevinVandy/material-react-table#567]
### material-react-table version

1.12.1

### react & react-dom versions

storybook

### Describe the bug and the steps to reproduce it

https://www.material-react-table.dev/?path=/story/features-filtering-examples--filtering-change-mode-enabled

when changing the mode of the Age column to between inclusive, the menu item clear filter is always active. It appears there are undefined values in the filter state.
![image](https://github.com/KevinVandy/material-react-table/assets/17402724/77b7395a-9e4c-40b7-bf96-593b54eaff67)

Also switching to between back will still shows this bug.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.dev/?path=/story/features-filtering-examples--filtering-change-mode-enabled

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
should be fixed in v1.14.0
