### ISSUE TITLE
Actions are still visible even if i am changing the state of enableRowActions on route change.

### ISSUE THREAD

**Issue by bhavesh112** [KevinVandy/material-react-table#579]
### material-react-table version

v1.4.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

 I am using the same component over different routes in which some tables will have `enableRowActions : true` and others `false`. It is decided on the basis of a writable prop.

I am facing the issue when i navigate from a page where `enableRowActions` is `false` and actions are hidden. It remains hidden for the next route as well. This issues is also there the other way around. 

I tried manually inserting `mrt-row-actions` in `columnOrder` state and removing from it as well.
I have also tried to control the behaviour by `columnVisibility` but neither of those works. But on refreshing the page it works.
I am assuming here that enableRowActions is keeping the initital state it gets and doesnt update it on subsequent renders.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
const MasterPage = ({writable}) =>{
const params = useParams();
// data is fetched using params which provide the slug to use for fetching data.
// writable is providing from context the logic is very length to detect whether certain user is 
// authorized or not hence skipping that part
return (<>
  <MaterialReactTable 
    data={data}
    columns={columns}
    enableRowActions={writable}
  />

  </>)
}


```

in `App.js`

```
<Route path='/:slug' element={<MasterPage />}

```

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The columnVisibility method should definitely work. That's the recommended way. Show how you were trying that.

**Comment by bhavesh112** [comment]
Tried again with enableRowActions={true} then dynamically updating columnVisibility it works then.

**Comment by KevinVandy** [comment]
Update to v2.8.0 where dynamically enabling features that cause internal MRT display columns to show/hide is now fully supported. https://www.material-react-table.dev/?path=/story/features-row-actions-examples--row-actions-enabled-conditionally
