### ISSUE TITLE
dynamic enableMultiRowSelection only works with renderDetailPanel

### ISSUE THREAD

**Issue by kinglau66** [KevinVandy/material-react-table#581]
### material-react-table version

v1.14

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

 ```     
enableMultiRowSelection={multi}
// toggle multi only works with renderDetailPanel
renderDetailPanel={() => <></>}
```

dynamic enableMultiRowSelection only works with renderDetailPanel

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/github-pwal2v-mps41p?file=src%2FTS.tsx

The "Toggle Multi" button works correctly when clicked. However, if you comment out the `renderDetailPanel` function and click the button, the changes will not be reflected.

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/15945904/b7702f18-1c33-4b06-b063-4730e9f5abef)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This has been fixed all the way in v2.8.0 as display columns are no longer memoized unless during column resizing or column/row dnd events.
