### ISSUE TITLE
Progress bars not disappear after isLoading is set to false. 

### ISSUE THREAD

**Issue by LvChengbin** [KevinVandy/material-react-table#582]
### material-react-table version

v1.14.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

The process bars keep showing after the `isLoading` prop has already been changed to false.

### Minimal, Reproducible Example - (Optional, but Recommended)

I'm sorry I can't provide you a reproducible example because it only happens randomly.
But it worked well after I change the `<Collapse />` component that used in `<MRT_LinearProgressBar />` to `<Box />` component of material ui.

![image](https://github.com/KevinVandy/material-react-table/assets/963223/928950dc-6cef-42c9-868c-5dd99f051c66)

I tried printing the `isLoading` and `showProgressBars` variables, before the return line, both are `false`.

I don't have enough time to figure out if it should be an issue of material-ui `<Collapse />` component.

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/963223/cab2628f-9828-4333-9820-a577fb5614e3)

_No response_

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Are you using a memoMode?

**Comment by LvChengbin** [comment]
@KevinVandy No, I'm not using the memoMode.

**Comment by KevinVandy** [comment]
Would you be able to share a full code snippet of your `MaterialReactTable` call?

**Comment by zhongjiaguo001** [comment]
Hello, my friend. When I activate the loading state, the loading bar disappears, leaving only the skeleton screen. This is my code.
![code](https://github.com/KevinVandy/material-react-table/assets/44691489/1e083dc8-1c8d-4286-b25d-28760fb067ca)

**Comment by zhongjiaguo001** [comment]
> Hello, my friend. When I activate the loading state, the loading bar disappears, leaving only the skeleton screen. This is my code.你好，我的朋友。当我激活加载状态时，加载栏消失，只留下骨架屏幕。这是我的代码。 ![code](https://user-images.githubusercontent.com/44691489/262620369-1e083dc8-1c8d-4286-b25d-28760fb067ca.png)

The operation before the progress bar disappears seems to involve me just changing the pagination to a custom component.
