### ISSUE TITLE
After cleaning the filter, the chip (empty or not empty) does not disappear.

### ISSUE THREAD

**Issue by rpmeir** [KevinVandy/material-react-table#584]
### material-react-table version

v1.12.0

### react & react-dom versions

react  v18.0.2 and react-dom v18.0.2

### Describe the bug and the steps to reproduce it

After applying empty or not empty filters to some column, and then clearing the filter for that same column, the chip (empty or not empty) does not disappear and remains in the input as if the column was still being filtered.

This also happens when calling the table instance's API resetColumnFilters function.

P.S. 
I will try to find the cause of the problem and help with the solution, but I only have time available on weekends. Thanks!

### Minimal, Reproducible Example - (Optional, but Recommended)

The example above was run on the project page, in the advanced example demo.

[Advanced Demo](https://www.material-react-table.com/docs/examples/advanced#advanced-demo)

### Screenshots or Videos (Optional)

![MRT_ChipNotDisabled](https://github.com/KevinVandy/material-react-table/assets/32312300/be5a3ff6-8ea5-415d-bf17-83c34660fb38)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was fixed at some point in the latest v2
