### ISSUE TITLE
Inline Edit - editingMode="row" gives the component state all undefined

### ISSUE THREAD

**Issue by dinesh-aot** [KevinVandy/material-react-table#590]
### material-react-table version

v1.14.0

### react & react-dom versions

v18.

### Describe the bug and the steps to reproduce it

If you set the editingMode="row", you will not be able to access any state in the component within the "onEditingRowSave" handler. 
Please check this sample. This is from your own example provided in the documentation
https://codesandbox.io/p/sandbox/funny-allen-8c4dfr?file=%2Fsrc%2FTS.tsx%3A60%2C7-60%2C23

If you just make the editingMode to "modal" instead of "row" it will start working. 

### Minimal, Reproducible Example - (Optional, but Recommended)

import React, { useMemo, useState, useEffect } from "react";
import {
  MaterialReactTable,
  type MaterialReactTableProps,
  type MRT_ColumnDef,
} from "material-react-table";
import { data, type Person } from "./makeData";

const Example = () => {
  const columns = useMemo<MRT_ColumnDef<Person>[]>(
    () => [
      //column definitions...
      {
        accessorKey: "firstName",
        header: "First Name",
      },
      {
        accessorKey: "lastName",
        header: "Last Name",
      },

      {
        accessorKey: "address",
        header: "Address",
      },
      {
        accessorKey: "city",
        header: "City",
      },

      {
        accessorKey: "state",
        header: "State",
      }, //end
    ],
    []
  );

  const [tableData, setTableData] = useState<Person[]>([]);
  useEffect(() => {
    setTableData(data);
  }, []);

  const handleSaveRow: MaterialReactTableProps<Person>["onEditingRowSave"] =
    async ({ exitEditingMode, row, values }) => {
      //if using flat data and simple accessorKeys/ids, you can just do a simple assignment here.
      console.log("Table data ", tableData);
      tableData[row.index] = values;
      //send/receive api updates here
      setTableData([...tableData]);
      exitEditingMode(); //required to exit editing mode
    };

  return (
    <MaterialReactTable
      columns={columns}
      data={tableData}
      editingMode="row" //default
      enableEditing
      onEditingRowSave={handleSaveRow}
    />
  );
};

export default Example;

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
what state are you accessing and where?

**Comment by dinesh-aot** [comment]
@KevinVandy  Thanks for the response.
Here is my code
`import React, { useEffect } from "react";
import {
  MaterialReactTable,
  type MaterialReactTableProps,
  type MRT_ColumnDef,
  type MRT_Row,
} from "material-react-table";
import { FormHelperText, Grid } from "@mui/material";
import { Group, User } from "../../models/user";
import { RESULT_STATUS } from "../../constants/application-constant";
import UserService from "../../services/userService";
import { EpicTrackPageGridContainer } from "../shared";
import Select from "react-select";
import MasterTrackTable from "../shared/MasterTrackTable";

const UserList = () => {
  const [isValidGroup, setIsValidGroup] = React.useState<boolean>(true);
  const getUsers = React.useCallback(async () => {
    setResultStatus(RESULT_STATUS.LOADING);
    try {
      const userResult = await UserService.getUsers();
      if (userResult.status === 200) {
        setUsers(userResult.data as never);
      }
    } catch (error) {
      console.error("User List: ", error);
    } finally {
      setResultStatus(RESULT_STATUS.LOADED);
    }
  }, []);

  const getGroups = React.useCallback(async () => {
    try {
      const groupResult = await UserService.getGroups();
      if (groupResult.status === 200) {
        setGroups(groupResult.data as Group[]);
      }
    } catch (error) {
      console.error("Group List: ", error);
    }
  }, []);

  React.useEffect(() => {
    getUsers();
  }, []);

  React.useEffect(() => {
    getGroups();
  }, []);
  const [groups, setGroups] = React.useState<Group[]>([]);
  const [users, setUsers] = React.useState<User[]>([]);
  const [resultStatus, setResultStatus] = React.useState<string>();
  const [selectedGroup, setSelectedGroup] = React.useState<
    Group | undefined | null
  >();
  const columns = React.useMemo<MRT_ColumnDef<User>[]>(
    () => [
      {
        id: "name",
        accessorFn: (row: User) => `${row.last_name}, ${row.first_name}`,
        header: "Name",
        sortingFn: "sortFn",
        enableEditing: false,
      },
      {
        accessorKey: "email",
        header: "Email",
        enableEditing: false,
      },
      {
        accessorKey: "group.name",
        header: "Group",
        enableEditing: true,
        Edit: ({ cell, column, table }) => (
          <>
            <Select
              getOptionValue={(opt) => opt.id}
              getOptionLabel={(opt) => opt.name}
              options={groups}
              required={true}
              // menuPortalTarget={document.body}
              onChange={(newVal) => setSelectedGroup(newVal)}
              defaultValue={groups.find(
                (p) => p.id === cell.row.original.group?.id
              )}
              value={selectedGroup}
              onBlur={(event) => {
                const isValid = !!event.target.value.length;
                setIsValidGroup(isValid);
              }}
            />
            {!isValidGroup && (
              <FormHelperText
                error={true}
                className="MuiFormHelperText-sizeSmall"
                style={{ marginInline: "14px" }}
              >
                Please select the group
              </FormHelperText>
            )}
          </>
        ),
      },
    ],
    [groups, isValidGroup]
  );

  const handleCancelRowEdits = () => {
    setIsValidGroup(true);
    setSelectedGroup(null);
  };

  const handleSaveRowEdits: MaterialReactTableProps<User>["onEditingRowSave"] =
    async ({ exitEditingMode, row, values }) => {
      setIsValidGroup(!!selectedGroup);
      if (!!selectedGroup) {
        setSelectedGroup(null);
        exitEditingMode(); //required to exit editing mode and close modal
      }
    };

  return (
    <>
      <EpicTrackPageGridContainer
        direction="row"
        container
        columnSpacing={2}
        rowSpacing={3}
      >
        <Grid item xs={12}>
          <MaterialReactTable
            columns={columns}
            data={users}
            editingMode="row"
            enableColumnOrdering
            enableEditing
            onEditingRowSave={handleSaveRowEdits}
            onEditingRowCancel={handleCancelRowEdits}
          />
        </Grid>
      </EpicTrackPageGridContainer>
    </>
  );
};

export default UserList;
`

**Comment by Nibertj** [comment]
I am seeing the exact same thing.

**Comment by KevinVandy** [comment]
This looks to be a
