### ISSUE TITLE
When data rows are deleted and pagination resets to the last page due to page index out of bounds (with table prop, autoResetPageIndex = false), data is not shown in certain cases.

### ISSUE THREAD

**Issue by kenny-lu-hl** [KevinVandy/material-react-table#602]
### material-react-table version

v1.14.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Here is a code sandbox demonstrating the bug.  [Code sandbox bug demo](https://codesandbox.io/s/when-autoresetpageindex-false-and-pagination-resets-to-last-page-data-is-not-shown-in-table-forked-849nrm?file=/src/App.js)
Bug description is also in the sandbox.
Fix for bug is given below.

### Description
When using autoResetPageIndex=false and data passed to the updates, page index can get out of bounds (i.e. There are no longer enough data rows for the current page index).

Use the provided code sandbox to see this behavior, click Get 3 pages of data then go the 3rd page (showing rows 21-30 of 30). Then click Get 2 pages of data. Notice table footer now shows 11-20 of 20, but no data is displayed. Then if you click go to previous page, you can see data on the first page. And if you click go to next page, data in 2nd page is shown correctly

In this case, the table tries to reset the page index so that the second page is shown. However there is a bug in the useEffect that attempts to reset the index. Description and fix for bug are in the discord thread.

### Cause
There are two issues with this if statement in MRT_TableRoot component. 
(packages\material-react-table\src\table\MRT_TableRoot.tsx : line 394)
        if (firstVisibleRowIndex > totalRowCount) {
          table.setPageIndex(Math.floor(totalRowCount / pageSize));
        }

- Comparison in if statement should be updated.
The comparison should be firstVisibleRowIndex >= totalRowCount  instead of '>'
(-1 discrepancy between index and count. )

- Math to calculate new index is wrong when totalRowCount is a multiple of pageSize. 
Example.  totalRowCount of 10 and pageSize of 5 gives new index of  2 (3rd page) but index should be 1 (2nd page)

### Fix
Either of fixes work. Page index will be updated and table rows will be populated with data.

**Option 1**
Page index calculation uses table.getPageCount().   

        if (firstVisibleRowIndex >= totalRowCount) {
          const lastPageIndex = Math.max(0, table.getPageCount() - 1)
          table.setPageIndex(lastPageIndex);
        }

**Option 2**
Or we can just compare the pageCount with pageIndex instead of having to calculate firstVisibleRowIndex as in option 1.  

       const pageCount = table.getPageCount()
       if (pageIndex >=  pageCount) {
          const lastPageIndex = Math.max(0, pageCount  - 1)
          table.setPageIndex(lastPageIndex);
        }

### Pull Request
I'd be happy to submit a pull request, but I am not sure what testing standards this project has. I didn't see tests in the repo, so not sure if unit tests are required for this fix?

### Minimal, Reproducible Example - (Optional, but Recommended)

Code sandbox example included in description section above.

### Do you intend to try to help solve this bug with your own PR?

Yes, I am also opening a PR that solves the problem along side this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by MarcinSzalomski** [comment]
Did you find any solution by any chance? @kenny-lu-hl

**Comment by kenny-lu-hl** [comment]
> Did you find any solution by any chance? @kenny-lu-hl

The fix is included in the original post.

**Comment by KevinVandy** [comment]
This should be fixed in v2.7.0
