### ISSUE TITLE
non-pinned column text overflow on pinned column

### ISSUE THREAD

**Issue by gurunathgd02** [KevinVandy/material-react-table#603]
### material-react-table version

1.11.2, 1.14.0

### react & react-dom versions

React 18.2.0,  React Dom 18.2.0

### Describe the bug and the steps to reproduce it

If we pin a column and select a row and when we hover over the selected row the text of non pinned row overflow over the pinned column text.

1. Pin a column left/right
2. Select a row
3. Scroll horizontally to the right or the left
4. Hover over the selected row
5. You will see non-pinned row text overlaps pinned row text

### Minimal, Reproducible Example - (Optional, but Recommended)

![1](https://github.com/KevinVandy/material-react-table/assets/138104541/1dba1bf9-5840-4557-a5d2-14bb822dae2d)
![2](https://github.com/KevinVandy/material-react-table/assets/138104541/5c408306-7826-46b2-a15e-8870ea77bd98)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by kaiqueaguilar** [comment]
I'm having the same problem, I came here to open an issue.

https://www.material-react-table.dev/?path=/story/features-column-pinning-examples--column-pinning-with-select

<img width="784" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/92055543/87dbccd5-8b20-4f1b-adc2-f4a3aba343e4">

**Comment by KevinVandy** [comment]
I spent a couple hours a few weeks ago trying to fix this, but didn't get far. Help would be appreciated

**Comment by ArtemPasechnyi** [comment]
I did some research and this is what I found

https://github.com/KevinVandy/material-react-table/assets/91153498/6469bbc6-141e-4e1a-8306-974b5bb9240c

**Comment by ArtemPasechnyi** [comment]
Thinking I can fix it and make PR

**Comment by gurunathgd02** [comment]
Thank You @ArtemPasechnyi for the idea.

In muiTableBodyRowProps you can add below sx property. You can choose your color for selected row and for hover. You can also skip hover color too, if you do not want to set it.

sx: {
            "&.MuiTableRow-root.Mui-selected td": {
              bgcolor: "#bbdefb",
            },
            "&.MuiTableRow-root.Mui-selected.MuiTableRow-root:hover td": {
              bgcolor: "#90caf9",
            },
          },

Which worked for me.

**Comment by KevinVandy** [comment]
This has been fixed in v2.9.0 with some added ::before and ::after pseudo elements!
