### ISSUE TITLE
Deeply nested key returning undefined console error

### ISSUE THREAD

**Issue by wmoore8** [KevinVandy/material-react-table#616]
### material-react-table version

v1.14.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

When accessing a deeply nested value that is undefined using `accessorKey`, the console log spits out a bunch of warnings are annoying to read past. Is there any way to disable this functionality? 

What makes me believe this is a bug is this only happens with keys that are deeply nested (ie in my attached screenshot, audit.create_utc will return this console error, but just having audit would not).

### Minimal, Reproducible Example - (Optional, but Recommended)

`
const columns = 
{
      header: 'Created',
      accessorKey: 'audit.create_utc'
}

//...
<MaterialReactTable
    columns={columns}
/>
//...
`

### Screenshots or Videos (Optional)

<img width="450" alt="Screen Shot 2023-07-10 at 4 03 14 PM" src="https://github.com/KevinVandy/material-react-table/assets/38674278/d1a9aa12-d036-4809-9b9a-c7873ba39273">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This happens if your nested data structure is inconsistent and sometimes has undefined values. In previous versions, we even through errors here to prevent devs from trying this to prevent unintended behavior with all the other features. Now we just show the warning.

What I recommend doing here if you have inconsistent data structures is to use an accessorFn instead of accessorKey. That way you can gracefully handle undefined data and have proper fallback values.

**Comment by wmoore8** [comment]
Hi @KevinVandy,

Thanks for the quick response!! I guess I'm still a little confused about the "data structure is inconsistent" part. In my case, `audit.create_utc` is always there; it’s just that sometimes its value is undefined. Why is it that only a deeply nested key that gives the console error? To clarify more, my records (sorta) look like this:
```
const foo = {
   bar: ‘bar’,
   baz: undefined,
   audit: {
      create_utc: undefined
   }
}
```
When `baz` is undefined, MRT is fine with it; but when `create_utc` is undefined, I get the warning. In other words, I’m getting the warning when the *value* in a nested field is missing, not when one of the keys is missing (which I think is what you mean by “inconsistent data structure”).
So it seems like MRT is treating missing values differently for a top-level key vs a nested key.
I could use the `accessorFn` to resolve this, but we have a lot of these and obviously I lose all the advantage of the very convenient nested `foo.bar` syntax if I have to change them all to `accessorFn`.

**Comment by wmoore8** [comment]
"See related [Tanstack Table issue 4788](https://github.com/TanStack/table/discussions/4788)"

**Comment by wmoore8** [comment]
"See related [Tanstack Table issue 4788](https://github.com/TanStack/table/discussions/4788)"

**Comment by KevinVandy** [comment]
You can use an `accessorFn` instead of the string `accessorKey`. In your `accessorFn`, you can handle the undefined checks how you want.
