### ISSUE TITLE
Columns resizing acts weird

### ISSUE THREAD

**Issue by daniilguit** [KevinVandy/material-react-table#625]
### material-react-table version

1.14.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Column resizing works weird and unpredictable:
Example showcasing: https://www.material-react-table.com/docs/guides/column-resizing#enable-column-resizing-demo
Try resizing column any column: e.g. if you resize First Name column moving your mouse right the resize line will move faster that your mouse, if you resize  Email address - resize line (and column size) would change not proportional to mouse move

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/guides/column-resizing#enable-column-resizing-demo

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/231284/4f831f6d-f8aa-4c4c-92f1-77cd9bedb49f

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by oliverfrost1** [comment]
Try setting the layoutMode prop to "grid" like so: " layoutMode="grid""

**Comment by KevinVandy** [comment]
Good news, upgrade to v2 (beta at the time of writing) for way better column resizing behavior. There is a new `layoutMode: 'grid-no-grow'` layoutMode that gets set internally when `enableColumnResizing is enabled. Use that instead of `layoutMode="grid"`
