### ISSUE TITLE
Sort cause scrolling

### ISSUE THREAD

**Issue by nicolaeClichici** [KevinVandy/material-react-table#631]
### material-react-table version

v.1.14.0

### react & react-dom versions

v.18.2.0

### Describe the bug and the steps to reproduce it

1. Sort desc one column
2. Scroll to the bottom of table
3. Update an value from sorted column witch will cause placing row to the top of table

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/charming-satoshi-6fd72z?file=/src/App.tsx

### Screenshots or Videos (Optional)

![chrome_vAZLA7zRH5](https://github.com/KevinVandy/material-react-table/assets/113600769/bf6e1303-2e50-4c11-86ce-906501a37eef)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm not sure this is actually a problem?
