### ISSUE TITLE
Checkboxes not remembering state of data when editing

### ISSUE THREAD

**Issue by wmoore8** [KevinVandy/material-react-table#632]
### material-react-table version

v1.14.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Hello!

Posting a question regarding the editing actions in a row. Specifically, when the row has boolean data that I want to edit, I did not like the default "true/false" dropdown and would rather a checkbox to display that. 

I've set up an example in the code sandbox below that shows exactly what's going wrong. To describe it exactly, when I click to edit a row, the checkbox comes up for my boolean column. However, the checkbox does not register the value of that boolean, instead always coming up as an empty checkbox and not changing the display of the column being marked true or not.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/damp-surf-tdc5sj?file=%2Fsrc%2FTS.tsx%3A33%2C4

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by zhyph** [comment]
I found that using a custom component is better in this scenario, instead of changing the TextField type to `checkbox`, I used an actual Checkbox using the [`Edit`](https://www.material-react-table.com/docs/guides/editing#use-custom-editing-components) property on columns, here's a sandbox:
https://codesandbox.io/p/sandbox/holy-wave-wc9pj8?file=%2Fsrc%2FTS.tsx%3A26%2C40

**Comment by githorse** [comment]
Thank you @zhyph! Can you help me understand why we need to use `defaultChecked` instead of `checked` here?

**Comment by zhyph** [comment]
@githorse The only reason I used is to make it "controlled", you could create a `state` and use it instead of using the `_valuesCache`, otherwise there's no way of making it reactive. Not sure if there's a better way of dealing with this.
