### ISSUE TITLE
Click handler on row causes TS2589: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by JasonDWilson** [KevinVandy/material-react-table#634]
### material-react-table version

1.14.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

- Create a component that renders MaterialReactTable
- Add a Double click handler to muiTableRowProps

``` javascript
          muiTableBodyRowProps={({ row }) => ({
            onDoubleClick: () => {
              // setEncounter(row.original);
              // setShowEncounterDetail(true);
              console.log(`Row [${row.id}] clicked`)
            },
            sx: {
              cursor: "pointer"
            }
          })}
```
- npm run build
- look for src/modules/vision/components/Encounters/EncountersTable.tsx(119,9): error TS2589: Type instantiation is excessively deep and possibly infinite.

### Minimal, Reproducible Example - (Optional, but Recommended)

``` javascript
        <MaterialReactTable
          columns={columns}
          data={filteredEncounters}
          enableGlobalFilter
          enableRowSelection
          enableTopToolbar={false}
          muiTableBodyRowProps={({ row }) => ({
            onDoubleClick: () => {
              // setEncounter(row.original);
              // setShowEncounterDetail(true);
              console.log(`Row [${row.id}] clicked`)
            },
            sx: {
              cursor: "pointer"
            }
          })}
          onGlobalFilterChange={setGlobalFilter}
          onRowSelectionChange={setRowSelection}
          state={{ rowSelection: rowSelection, globalFilter: globalFilter }}
        />
```

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by JasonDWilson** [comment]
Incidentally the error goes away if I tell typescript that the type is generic:
``` typescript
          muiTableBodyRowProps={({row}:any) => ({
            onDoubleClick: () => {
              setEncounter(row.original);
              setShowEncounterDetail(true);
            },
            sx: {
              cursor: "pointer"
            }
          })}
```
TS really doesn't like the MRT_Row type.

**Comment by KevinVandy** [comment]
I have a section in the docs now about how to use the generics and type-safety a bit better. Adding your TData generic to all of the MRT types is pretty much required.
https://www.material-react-table.com/docs/guides/best-practices#type-safety
