### ISSUE TITLE
Can't over ride Table Row hover background color 

### ISSUE THREAD

**Issue by ajmaln-tw** [KevinVandy/material-react-table#649]
### material-react-table version

1.9.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I'm not able to override the table row hover stylings
Below is MRT table styling all other styles got reflected in UI, but muiTableBodyRowProps hover not reflecting in the UI

```
muiTableHeadRowProps={{
                        sx: {
                            backgroundColor: "#212529"
                        }
                    }}
                    muiTableBodyCellProps={{
                        sx: {
                            fontSize: "11px",
                            color: "#fff",
                            borderTop: "1px solid #181b1e",
                            backgroundColor: "#0000"

                        }
                    }}
```
                    muiTableBodyRowProps={{
                        sx: {
                            fontSize: "11px",
                            color: "#000",
                            borderTop: "1px solid #181b1e",
                            backgroundColor: "#0000",
                            "&:hover": {
                                color: "#ff0000",
                                backgroundColor: "#0fdd" 
                            }
                        }
                    }}
                    muiTopToolbarProps={{
                        sx: {
                            display: "block",
                            flexDirection: "column",
                            backgroundColor: "#181b1e"
                        }
                    }}
                    muiTableHeadCellProps={{
                        sx: {
                            fontSize: "14px",
                            fontWeight: 700,
                            color: "#ffffff",
                            py: 3
                        }
                    }}`

This is my table view without hover
![image](https://github.com/KevinVandy/material-react-table/assets/129822667/3622bbc4-3e7a-4b0e-92f6-d753de71af98)

with hover
![image](https://github.com/KevinVandy/material-react-table/assets/129822667/4756802d-c4cf-4071-97ce-fdc205236713)

I changed the style and hovered over the row styling not reflected on UI
![image](https://github.com/KevinVandy/material-react-table/assets/129822667/bde9b579-cc86-420d-80e1-977446891403)

### Minimal, Reproducible Example - (Optional, but Recommended)

  ```
 <MaterialReactTable
                    initialState={{ density: "comfortable", showHideColumnFilters: "false" }}
                    columns={columns}
                    data={data}
                    state={state}
                    enableFilters={enableFilters}
                    enableRowVirtualization={enableRowVirtualization}
                    virtualizerInstanceRef={enableRowVirtualization && virtualizerInstanceRef}
                    virtualizerProps={{ overscan: 25 }}
                    muiTableContainerProps={{ sx: { maxHeight: "600px", color: "#ffffff" } }}
                    onSortingChange={setSorting}
                    displayColumnDefOptions={displayColumnDefOptions}
                    getCanMultiSelect={getCanMultiSelect}
                    enableColumnFilter={enableFilters ? true : false}
                    onRowSelectionChange={handleRowSelection}
                    enableBottomToolbar={false}
                    enableStickyFooter={false}
                    muiTableHeadRowProps={{
                        sx: {
                            backgroundColor: "#212529"
                        }
                    }}
                
                    muiTableBodyCellProps={{
                        sx: {
                            fontSize: "11px",
                            color: "#fff",
                            borderTop: "1px solid #181b1e",
                            backgroundColor: "#0000"

                        }
                    }}
                    muiTableBodyRowProps={{
                        sx: {
                            fontSize: "11px",
                            color: "#000",
                            borderTop: "1px solid #181b1e",
                            backgroundColor: "#0000",
                            "&:hover": {
                                color: "#ff0000", // Change color on hover
                                backgroundColor: "#0fdd" // Change background color on hover
                            }
                        }
                    }}
                    muiTopToolbarProps={{
                        sx: {
                            display: "block",
                            flexDirection: "column",
                            backgroundColor: "#181b1e"
                        }
                    }}
                    muiTableHeadCellProps={{
                        sx: {
                            fontSize: "14px",
                            fontWeight: 700,
                            color: "#ffffff",
                            py: 3
                        }
                    }}

                    {...rest}
                />
```

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/129822667/2512d9ec-53c5-4024-87ee-d4ceda1444dc)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by zbouslikhin** [comment]
A workaround would be 
```
      muiTableBodyRowProps={{
        sx: {
          backgroundColor: styles.backgroundColor,
          color: styles.colorText,
          '&:hover td': {
            backgroundColor: styles.lightHover,
          },
        },
      }}
```

**Comment by ajmaln-tw** [comment]
it worked for me
before
![image](https://github.com/KevinVandy/material-react-table/assets/129822667/65141bf3-f287-4771-84cb-3ace2ca48fba)
hover
![image](https://github.com/KevinVandy/material-react-table/assets/129822667/41de127c-f575-4166-9248-58463b10ff9e)

thank you so much @zbouslikhin
