### ISSUE TITLE
Overriding body style can mess with app style.

### ISSUE THREAD

**Issue by kikonejacob** [KevinVandy/material-react-table#65]
### material-react-table version

1.0.0-beta.7

### Describe the bug and the steps to reproduce it

The following align assign a style to body. I think this component should not change the dom outside of the component scope and if it does, it should make sure it restore it correctly.

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://github.com/KevinVandy/material-react-table/blob/2d17b09c327b6e140a83eb9aedbef7245f38ce24/src/table/MRT_TablePaper.tsx#L25

### Screenshots or Videos (Optional)

<img width="285" alt="image" src="https://user-images.githubusercontent.com/3852574/188773894-23916829-2dd4-4ce7-8915-7982f703c4de.png">

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I think I fixed this in `v1.0.0-beta.8`. Try it out. 

I hate that I have to even touch the body style, but its the only way to get the full screen feature to work. 

Now at least I am storing the original value in a ref so it can be reset properly

**Comment by kikonejacob** [comment]
> I think I fixed this in `v1.0.0-beta.8`. Try it out.
> 
> I hate that I have to even touch the body style, but its the only way to get the full screen feature to work.
> 
> Now at least I am storing the original value in a ref so it can be reset properly

awesome! Thanks !
you probably already tried it but I though you could use [RequestFullScreen API.](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen)

https://jhey.dev/writing/make-your-elements-full-with-requestfullscreen/
