### ISSUE TITLE
Warning: A component is changing an uncontrolled input to be controlled

### ISSUE THREAD

**Issue by githorse** [KevinVandy/material-react-table#654]
### material-react-table version

v1.14.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I have a value in my record that might be a string or `undefined`. It's initially `undefined`, but the user might edit it to give it a value. When I do that, I get an ugly console error:

```
console.js:213 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
```

**I am aware this is [an issue with React](https://github.com/mui/material-ui/issues/18173), not MRT** -- basically, React is objecting to a perfectly valid (and common) scenario, a controlled input that starts out `undefined`. In my own code, I use the [standard silly workaround](https://stackoverflow.com/questions/47012169/a-component-is-changing-an-uncontrolled-input-of-type-text-to-be-controlled-erro) for this problem:

```
value={value || ''}
```

But I don't have direct control over the `value` when using the built-in MRT row editor. Setting the value to `''` in *my* upstream code (i.e., in state, as opposed to the last instant before it hits the input) is not really correct, and creates problems -- like, how do I ensure that doesn't get written back to the database as an empty string? 

It would be great if MRT could implement the `value || ''` workaround to turn off this spurious warning. I doubt that breaks anything since it's kind of broken by default in React -- but if so, perhaps it could be protected with a flag (`allowNull` or some such).  

### Minimal, Reproducible Example - (Optional, but Recommended)

See [CodeSandbox example](https://codesandbox.io/p/sandbox/pensive-mountain-jtyc2g?file=%2Fsrc%2FmakeData.ts%3A2%2C13)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Vetnametz** [comment]
Same problem **defaultValue: "",**
```
muiEditTextFieldProps: {
          select: true,
          defaultValue: "",
          error: !!validationErrors?.region,
          helperText: validationErrors?.region,
        },
```
not fixin error

**Comment by KevinVandy** [comment]
It already does this internally, and I have not seen the error. Will reopen if anyone still runs into this 

<img width="457" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/7f1dd7f3-8f06-419e-9fc7-4d12ec54455f">

**Comment by Klaus-8** [comment]
Hi,

I'm still facing this issue :(

![image](https://github.com/KevinVandy/material-react-table/assets/97245667/e97a42b2-c5ab-435c-811d-0a1c48935e00)
