### ISSUE TITLE
Required engine versions mismatched with dependancies

### ISSUE THREAD

**Issue by robert-pitt-foodhub** [KevinVandy/material-react-table#657]
### material-react-table version

1.14.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

Within the package.json for material-react-table ([here](https://github.com/KevinVandy/material-react-table/blob/v2/packages/material-react-table/package.json#L45)) specifies the min node version to be v14, however the dependancy for highlight-words has a minimum requirement of node v16 ([here](https://github.com/tricinel/highlight-words/blob/master/package.json#L5))

This mismatch is causing node to fail any builds in node v14 environments, as show in the screenshot below:

<img width="1367" alt="Screenshot 2023-08-16 at 13 55 43" src="https://github.com/KevinVandy/material-react-table/assets/70318887/021e5d7d-0546-4f33-b1cc-e7815e5824e2">

### Minimal, Reproducible Example - (Optional, but Recommended)

None

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I don't know how you are installing MRT in order to run into an issue like this, but no one else has ever run into this issue as far as I know.

**Comment by KevinVandy** [comment]
alright going forward, MRT will have to require node 16 and above. I think that's pretty reasonable with Node 20 LTS starting next week.
