### ISSUE TITLE
drag-and-dropped row does not stay where dropped (visually) 

### ISSUE THREAD

**Issue by githorse** [KevinVandy/material-react-table#660]
### material-react-table version

v1.14.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

As you can see in the [drag-and-drop demo in the MRT docs](https://www.material-react-table.com/docs/guides/row-ordering-dnd#enable-row-ordering-demo), the dropped row initially snaps back to its original place before then reappearing in the new spot:

https://github.com/KevinVandy/material-react-table/assets/8271372/d392e67d-9817-4a42-b822-0fa00052ea83

Compare this with, say, this [react-beautiful-dnd example](https://react-beautiful-dnd.netlify.app/iframe.html?id=single-vertical-list--basic), where the dropped item stays put. Obviously the latter behavior is preferable if we can get it.

(Worth noting that I've seen exactly this same snapping back problem with my own drag-and-drop component based on `react-beautiful-dnd`, which I solved by keeping the list of items in state so that I can immediately update it after the drop, but also syncing that stateful list of items to the external prop with a `useEffect` whenever the external prop changes. Normally that's a React antipattern but the only way I found to make it work seamlessly.)

See also [related drag-and-drop animation discussion](https://github.com/KevinVandy/material-react-table/discussions/661).

### Minimal, Reproducible Example - (Optional, but Recommended)

See [MRT row drag-and-drop demo](https://www.material-react-table.com/docs/guides/row-ordering-dnd#enable-row-ordering-demo).

### Screenshots or Videos (Optional)

(see above)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is just a side effect of only using the native browser apis instead of tons of fancy animation CSS. PRs are welcome to improve this, but I don't plan on spending time improving it myself.
