### ISSUE TITLE
'Uncaught TypeError' when using filterVariant 'select'

### ISSUE THREAD

**Issue by BendixP** [KevinVandy/material-react-table#664]
### material-react-table version

1.13.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

'Uncaught TypeError' is visible in console when filter Icon is clicked and filterVariant is set to 'select'.

![image](https://github.com/KevinVandy/material-react-table/assets/38940823/ead84791-2c21-4247-bfcb-e8d744d0d864)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/github/KevinVandy/material-react-table/tree/main/apps/material-react-table-docs/examples/customize-filter-components/sandbox?file=src%2FTS.tsx 

1. Set 'gender' filter
2. Click on little filter Icon
3. open console

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was probably fixed in v2.0.2
