### ISSUE TITLE
Double date picker fields not working

### ISSUE THREAD

**Issue by RomainDGrey** [KevinVandy/material-react-table#665]
### material-react-table version

1.14.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

You can directly reproduce it in the advanced example of the material react table's documentation : [Advanced table](https://www.material-react-table.com/docs/examples/advanced)
When you want to filter a date column, if the filter is based on two fields (Between or Between Inclusive), the selection of a date in the first datepicker will fulfilled both date pickers.

### Minimal, Reproducible Example - (Optional, but Recommended)

You can directly use the official [Sandbox](https://codesandbox.io/s/github/KevinVandy/material-react-table/tree/main/apps/material-react-table-docs/examples/advanced/sandbox?file=/src/TS.tsx)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was just missing a `filterRangeIndex` prop to indicate if it was the 1st or 2nd filter field. In v2, date range filters are built into MRT, so this will be easier by default going forward.
