### ISSUE TITLE
[BUG]Toogle select all disable button for custom action in toolbar

### ISSUE THREAD

**Issue by kzmKZuzmo** [KevinVandy/material-react-table#666]
### material-react-table version

1.14.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

if you select all rows by manual or click on the checkbox (select all) in the header of table and you have less than page size is than custom action button will be desibled

### Minimal, Reproducible Example - (Optional, but Recommended)

`import './App.css';
import {useMemo, useState} from "react";
import MaterialReactTable from "material-react-table";
import {Button} from "@mui/material";

function App() {

    const [conflicted, setConflicted] = useState([]);

    const columns = useMemo(
        () => [
            {
                id: "id",
                accessorKey: 'id',
                header: 'id',
            },
            {
                id: "type",
                accessorKey: 'type', //normal accessorKey
                header: 'type',
            },
            {
                id: "component",
                accessorKey: 'component',
                header: 'component',
            }
        ],
        [],
    );
    const handleSubmit = (event) => {
        event.preventDefault();
        setConflicted([
            {type: 3, id: 10055, component: "test1"},
            {type: 5, id: 20053, component: "test1"},
            {type: 6, id: 35652, component: "test1"},
            {type: 3, id: 40055, component: "test1"},
            {type: 5, id: 50015, component: "test2"},
            {type: 6, id: 65165, component: "test2"}])

    }

    return (
        <div className="App">
            <form onSubmit={handleSubmit}>
                <button type="submit">Submit</button>
            </form>

            <MaterialReactTable
                enableColumnFilterModes={false}
                enableColumnOrdering={false}
                enableGrouping={false}
                enablePinning={false}
                enableRowActions
                enableRowSelection

                selectAllMode="page"
                columns={columns}
                data={conflicted}
                initialState={
                    {
                        showColumnFilters: false,
                        grouping: ["component"]
                    }}
                getRowId={(row) => row.id}
                renderTopToolbarCustomActions={({table}) => {
                    const handleDeactivate = () => {
                        table.getSelectedRowModel().flatRows.map((row) => {
                            table.getSelectedRowModel().flatRows.map((row) => {
                                alert('deactivating ' + row.getValue('id'));
                            });
                        });
                    };
                    return (

                        <div style={{display: 'flex', gap: '0.5rem'}}>
                            <Button
                                color="info"
                                disabled={!table.getIsSomeRowsSelected()}
                                onClick={handleDeactivate}
                                variant="contained"
                            >
                                Move to correct
                            </Button>
                        </div>

                    );
                }
                }
            />
        </div>
    );
}

export default App;
`

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/16986250/517a292f-c2fa-4281-ae4f-95b497895060)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I don't really get what you're doing here, but here is how the MRT select all checkbox does it
```ts
const onSelectAllChange = (event: ChangeEvent<HTMLInputElement>) => {
  selectAllMode === 'all'
    ? table.getToggleAllRowsSelectedHandler()(event)
    : table.getToggleAllPageRowsSelectedHandler()(event);
 }
```
