### ISSUE TITLE
[BUG] Row selection when using server side data

### ISSUE THREAD

**Issue by sKoleff** [KevinVandy/material-react-table#668]
### material-react-table version

v1.14.0

### react & react-dom versions

v18.2

### Describe the bug and the steps to reproduce it

When using row selection with server-side data and changing the page row selection alert hides and `table.getIsSomeRowsSelected() && table.getIsAllRowsSelected()` returns false, or if on the next page all rows are selected, the alert says that the selected rows are 10 (state limit - 10), but actually they are 20...

### Minimal, Reproducible Example - (Optional, but Recommended)

I saw that in your example the problem exists also.
Eg: https://www.material-react-table.com/docs/examples/remote

### Screenshots or Videos (Optional)

Page 1 all selected:
<img width="1326" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/33654751/1c7b5d37-9ee5-41c9-9f85-e62c94ffe9c6">
Page 2 no alert for 10 selected rows:
<img width="1316" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/33654751/0a8a06ca-f2cf-4fb5-9381-0ccb654345f2">
Page 2 with all selected, but alert show 10 of * instead of 20:
<img width="1317" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/33654751/8c57db13-a60e-4772-b3ef-cd1aba7c5ac4">
Console log of the selection (20 selected rows):
<img width="876" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/33654751/2ff6b382-41aa-4c79-b478-6a3e74655a68">

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v2.5.1
