### ISSUE TITLE
Setting default rowsPerPage

### ISSUE THREAD

**Issue by vaclavgreif** [KevinVandy/material-react-table#669]
### material-react-table version

1.14.0

### react & react-dom versions

17.0

### Describe the bug and the steps to reproduce it

When trying to set detault number per row, still only 10 items are displayed by default:

```
muiTablePaginationProps={{
					rowsPerPageOptions: [10000000000, 5, 10, 50, 10],
					showFirstButton: false,
					showLastButton: false,
					rowsPerPage: 10000000000
				}}
```

I also tried setting rowsPerPage to -1 without any luck.

### Minimal, Reproducible Example - (Optional, but Recommended)

muiTablePaginationProps={{
					rowsPerPageOptions: [10000000000, 5, 10, 50, 10],
					showFirstButton: false,
					showLastButton: false,
					rowsPerPage: 10000000000
				}}

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You have to set page size through state or initialState

**Comment by vaclavgreif** [comment]
Awesome, thanks. For anyone searching for this, the following does work:
```
muiTablePaginationProps={{
					rowsPerPageOptions: [5, 10, 50, 10, 10000000000],
					showFirstButton: false,
					showLastButton: false,
				}}
				
initialState={
					{
						pagination: {
							pageSize:10000000000
						},
					}
				}
```
