### ISSUE TITLE
Enabling Column resizing hides few Column Actions 

### ISSUE THREAD

**Issue by vivasvan1** [KevinVandy/material-react-table#670]
### material-react-table version

v1.14.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Enabling the column resizing doesnt enable resizing of actions columns

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/peaceful-haze-wdszfq?file=%2Fsrc%2FTS.tsx%3A46%2C27

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is by design for all internal display columns, but you can change this with something like

```ts
defaultDisplayColumn={{enableResizing: true}}
```
or 
```ts
displayColumnDefOptions={{
  'mrt-row-actions': {
    enableResizing: true
  }
}}
```
