### ISSUE TITLE
React Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by kis** [KevinVandy/material-react-table#671]
### material-react-table version

1.14.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

When the table is loaded I see couple of react warnings in browser console: Warning: Each child in a list should have a unique "key" prop. Additionally it shows even more after click on Show/Hide columns button. The same after click on the dropdown in one of the cells. I was able to reduce one of the warnings with disabling selecting rows. Are there any solution to reduce react warnings?

### Minimal, Reproducible Example - (Optional, but Recommended)

```
<MaterialReactTable
      initialState={{
        columnPinning: { left: ['mrt-row-select', 'name'], right: ['actions'] },
        columnVisibility: { 'last-year-spend': false },
        density: 'comfortable',
        showSkeletons: !isLoading,
      }}
      state={{
        rowSelection,
      }}
      layoutMode='grid'
      tableInstanceRef={tableInstanceRef}
      data={displayData || []}
      columns={columns as MRT_ColumnDef<Record<string, unknown>>[]}
      enableDensityToggle={false}
      enableGlobalFilter={false}
      enablePinning
      enableColumnDragging
      enableColumnOrdering
      enableColumnResizing
      enableFullScreenToggle
      enableSelectAll={!isViewOnly && hasActions}
      selectAllMode='all'
      enableMultiRowSelection={hasActions}
      enableRowSelection={enableSelection}
      onRowSelectionChange={setRowSelection}
      getRowId={(originalRow: unknown) => (originalRow as Subscription).id}
      muiTableBodyRowProps={
        {
          'data-testid': 'subscription-item',
        } as TableRowProps
      }
      muiTableBodyCellProps={getRowStyle as TableCellProps}
 />
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is caused by you not using a unique value with the `getRowId` option. `getRowId` must identify rows by 100% unique values.
