### ISSUE TITLE
Content of neighbour column overlaps pinned column when the row selected and hovered. 

### ISSUE THREAD

**Issue by baki-kucukcakiroglu** [KevinVandy/material-react-table#674]
### material-react-table version

1.14.0

### react & react-dom versions

18.2.0 & 18.2.0

### Describe the bug and the steps to reproduce it

Content of neighbouring column overlaps pinned column when the row selected and hovered. This occurs when non-pinned columns have a horizontal scroll and the hovered row is also selected. 

Actually the non-pinned columns  that have horizontal scroll goes under pinned column but they are being apparent when the row is both selected and hovered. 

In images, non-pinned columns has a column "date" which doesn't fit the screen and being scrolled to be seen. However, it is being apparent when a row is selected and hovered.

Hovered and selected 
<img width="1275" alt="Screenshot 2023-09-07 at 20 05 36" src="https://github.com/KevinVandy/material-react-table/assets/113987895/cf80fe8c-a68b-485f-8b6d-3b3be46a387d">

Neither hovered nor selected
<img width="1276" alt="Screenshot 2023-09-07 at 20 09 56" src="https://github.com/KevinVandy/material-react-table/assets/113987895/bc6b8c1c-ead4-4627-9310-b02893f91aec">

Selected
<img width="1274" alt="Screenshot 2023-09-07 at 20 10 44" src="https://github.com/KevinVandy/material-react-table/assets/113987895/b6ab0756-2b92-4c86-b667-2983701533bd">

### Minimal, Reproducible Example - (Optional, but Recommended)

-

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This has been fixed in v2.9.0!
