### ISSUE TITLE
Row selection not working for nested rows (getSubRows)

### ISSUE THREAD

**Issue by srikrishna212** [KevinVandy/material-react-table#685]
### material-react-table version

1.9.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

**Describe the bug**
row-selection in the group rows are not correctly reacting to their sub-rows row-selection state

**Steps to reproduce**

Expand the first group row
Select the first sub-row
✅ Notice the parent row checkbox being "indeterminate"

Select the other 2 sub-rows in that same group
🛑 Notice the parent row checkbox is "unchecked", when it should be "checked"

**Expected behavior**
As a user, I expected the parent row to react to the row-selection status of its children, regardless on how they are selected/unselected:

some sub-rows selected: parent row "indeterminate"
no sub-rows selected: parent row "unchecked"
all sub-rows selected: parent row "checked"****

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/s/row-selection-sub-rows-kfgh2j

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This should all be fixed in the latest version (v2.7+)
