### ISSUE TITLE
Virtualized nested columns

### ISSUE THREAD

**Issue by tudro** [KevinVandy/material-react-table#686]
### material-react-table version

v1.14.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Hello,

If i enable column virtualization and i use a header like here https://www.material-react-table.com/docs/examples/advanced where you have the employee header/column with nested columns, i get an undefined header error. 

Here is a codesanbox based on your virtualized exemple where i added the `name` parent column for first, middle and last name. You just need to scroll to the right and at some point you'll get a blank page and the error.

Thank you

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/floral-bird-kv4p5c

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Added some fixes so that this will at least not crash anymore. Will look into more optimizations later.
