### ISSUE TITLE
[BUG] Row grouping with selection

### ISSUE THREAD

**Issue by sund168** [KevinVandy/material-react-table#693]
### material-react-table version

v1.14.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Here's the example at the official site: 
https://www.material-react-table.dev/?path=/story/features-sub-row-tree-examples--sub-row-tree-with-selection

Expand the group row... when all the sub rows are selected, the checkbox in the group row doesn't respond accordingly. 

Specifically:
when the group row is selected, if all sub rows are selected, the group row gets unselected while it should be selected;
when the group row is unselected, if all sub rows are unselected, the group row gets selected while it should be unselected.

### Minimal, Reproducible Example - (Optional, but Recommended)

Here's the example at the official site: 
https://www.material-react-table.dev/?path=/story/features-sub-row-tree-examples--sub-row-tree-with-selection

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/76795104/0950bcb4-425e-44a6-b643-539b0cbafd72)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was fixed in v2.5
