### ISSUE TITLE
Wrong row selection values/state when using tableInstanceRef

### ISSUE THREAD

**Issue by vipindigiqt** [KevinVandy/material-react-table#695]
### material-react-table version

1.15.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I'm getting the incorrect `getIsSomeRowsSelected()` and `getIsAllRowsSelected()` values, I think it is reversed.

Just use `tableInstanceRef` to get the tableRef, manage the row selection manually and it should be re-produced.

I've re-produced it here - https://stackblitz.com/edit/vitejs-vite-7hfh1s?file=src%2FApp.jsx

### Minimal, Reproducible Example - (Optional, but Recommended)

https://stackblitz.com/edit/vitejs-vite-7hfh1s?file=src%2FApp.jsx

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This has been fixed in v2 with the `useMaterialReactTable` hook: https://stackblitz.com/edit/vitejs-vite-bnyprq?file=src%2FApp.jsx
