### ISSUE TITLE
Grouping not working when a custom cell is rendered

### ISSUE THREAD

**Issue by hanieljazzar** [KevinVandy/material-react-table#697]
### material-react-table version

v1.15.0

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

I'm trying to group by a column that contains a link, but grouping fails. any idea how to group by text inside a link?

### Minimal, Reproducible Example - (Optional, but Recommended)

grouping: ['column']

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Your accessorFn should not contain any JSX. You didn't share any code here, but I'm assuming that's the mistake you make. Accessors should only resolve primitive values like strings, numbers, etc. if you are expecting the built-in filtering, grouping, sorting features to work.

You can still render JSX with the `Cell` option.

**Comment by hanieljazzar** [comment]
wasn't using JSX in accessorFn, I was using JSX in Cell, yet grouping doesn't work when there's JSX in Cell. Ended up having 2 columns, once with plain text that supports grouping and another one with the link using JSX in Cell

**Comment by KevinVandy** [comment]
> wasn't using JSX in accessorFn, I was using JSX in Cell, yet grouping doesn't work when there's JSX in Cell. Ended up having 2 columns, once with plain text that supports grouping and another one with the link using JSX in Cell

Hmm ok. Might look into further
