### ISSUE TITLE
State not changing for footer

### ISSUE THREAD

**Issue by jitujazz** [KevinVandy/material-react-table#698]
### material-react-table version

1.14.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

I am using a state for a column footer displaying the total. Based on the dropdown change, I am changing the data and also changing the total. But the issue is the data grid is not displaying the changed total

My column definition is below
`{
        header: 'Sun',
        footer: 'Totalss: '+sunTotal,
        accessorKey: 'sun'
}`

I have function defined when a dropdown changes. That function changes the total like below
`setSunTotal(data.reduce((acc, curr) => acc + curr.sunQty, 0));`

But, this doesn't seem to be changing the total on the grid. Am I doing anything wrong here?

### Minimal, Reproducible Example - (Optional, but Recommended)

Use `footer` for a column definition and use a state variable in it. Changing the state variable doesn't change the footer in the data grid

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Use the `Footer` instead of `footer` column option, and remember to maintain your `useMemo` dependency arrays correctly.
