### ISSUE TITLE
setEditingCell is undefined through the prop table of a component

### ISSUE THREAD

**Issue by nfuenmamelt** [KevinVandy/material-react-table#699]
### material-react-table version

material-react-table v1.14.0

### react & react-dom versions

react v18.2.0, react-dom v18.2.0, next v13.4.19

### Describe the bug and the steps to reproduce it

When we try to use the method setEditingCell to clean the active editing cell, example: "table.setEditingCell(null)", the method looks like is not defined and it is not executing the action of set editing cell in null.

here is an example on codesandbox: [CODE Example of issue](https://codesandbox.io/s/stupefied-dawn-7t54q8)

In this example we enable the edition of address column and when we change the select input, that action open a modal to show the confirm of the action, but if we cancel the action, the cell continue active even when in the function close we call "table.setEditingCell(null)".

### Minimal, Reproducible Example - (Optional, but Recommended)

[CODE Example of issue](https://codesandbox.io/s/stupefied-dawn-7t54q8)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This seems to be a bug where the edit button in the actions column is showing up for "cell" editing mode when it should not. Looks like both editingRow and editingCell are able to be populated at the same time. Will fix that.

**Comment by KevinVandy** [comment]
This was fixed at some point for v2
