### ISSUE TITLE
Row Actions column disappears when using initialState columnOrder

### ISSUE THREAD

**Issue by github-gael-soude** [KevinVandy/material-react-table#702]
### material-react-table version

1.15.0

### react & react-dom versions

11.11.1 & 18.2.0

### Describe the bug and the steps to reproduce it

On a MaterialReactTable with Row Actions (enableRowActions)
Using initialState columnOrder makes the Actions column disappear.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
      <MaterialReactTable
        data={data}
        columns={columns}
        initialState={{
          columnVisibility: columnVisibility,
          columnOrder: columnOrder,
        }}
        enableColumnFilterModes
        enableColumnOrdering
        enableColumnResizing
        enableFullScreenToggle
        enableRowActions
        state={{ isLoading: isLoading }}
      />
```

### Screenshots or Videos (Optional)

[Codesandbox example](https://codesandbox.io/s/charming-moore-zr96pv?file=/src/App.js:670-734)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Just make sure to include any built-in MRT columns in your columnOrder

https://www.material-react-table.com/docs/guides/display-columns

**Comment by github-gael-soude** [comment]
Thanks a lot
