### ISSUE TITLE
Column dragging issue

### ISSUE THREAD

**Issue by armantc** [KevinVandy/material-react-table#706]
### material-react-table version

v1.15.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

When set **enableTopToolbar** to false, and  **enableColumnOrdering** to true ,  first column dragging throw exception :

`Failed to execute 'setDragImage' on 'DataTransfer': parameter 1 is not of type 'Element'`

### Minimal, Reproducible Example - (Optional, but Recommended)

<MaterialReactTable
		data={data}
		columns={columns}
		enableTopToolbar={false}
		enableBottomToolbar={false}
		enableColumnResizing={true}
                enableColumnOrdering={true}
			/>

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v2.5.1
