### ISSUE TITLE
v2 Full screen sets low zIndex value to 10

### ISSUE THREAD

**Issue by jozeflvh** [KevinVandy/material-react-table#710]
### material-react-table version

2.0.0-alpha.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

The v2 version sets the zIndex to 10, when fullscreen is toggled. In our app the navbar and header bar sit at z-index 1100 and 1200. 
The hardcoded z-index toggle at the style level, makes it hard to override this setting.

I suggest to remove the zIndex toggle.

```
      style={{
        ...tablePaperProps?.style,
        ...(isFullScreen
          ? {
              bottom: 0,
              height: '100vh',
              left: 0,
              margin: 0,
              maxHeight: '100vh',
              maxWidth: '100vw',
              padding: 0,
              position: 'fixed',
              right: 0,
              top: 0,
              width: '100vw',
              zIndex: 10,
            }
          : {}),
      }}
    >
```

v2 line of code:
https://github.com/KevinVandy/material-react-table/blob/e8ef14bb07b86f033da17c9c533a1636069c9293/packages/material-react-table/src/table/MRT_TablePaper.tsx#L56

v1 line of code:
https://github.com/KevinVandy/material-react-table/blob/7fb5a5ecd6f16c406a2adca36c46d7220adcea91/packages/material-react-table/src/table/MRT_TablePaper.tsx#L56

### Minimal, Reproducible Example - (Optional, but Recommended)

https://github.com/KevinVandy/material-react-table/blob/e8ef14bb07b86f033da17c9c533a1636069c9293/packages/material-react-table/src/table/MRT_TablePaper.tsx#L56C25-L56C25

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by jozeflvh** [comment]
Suggested fix:
https://github.com/KevinVandy/material-react-table/pull/711

**Comment by KevinVandy** [comment]
This is now fixed by bumping up to `9999` by default, and it is documented how to change or bump it up even further

https://v2.material-react-table.com/docs/guides/full-screen-toggle

<img width="1280" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/4b6af8e9-6425-4343-bbf7-3c42072e219e">
