### ISSUE TITLE
enableColumnVirtualization, enableRowOrdering, then drag a row, table crashes.

### ISSUE THREAD

**Issue by YongThePsibor** [KevinVandy/material-react-table#717]
### material-react-table version

1.15.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

1. enableColumnVirtualization
2. enableRowOrdering
3. drag the row drag handler, the table crashes

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/columnvirtualization-row-drag-crash-tjxz5n

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/136299750/ff9afe6a-a87f-4442-89c1-5ca11e7ae666)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v2.5.1
