### ISSUE TITLE
positionExpandColumn doesn't work when it is set to 'last'

### ISSUE THREAD

**Issue by HrisyToteva** [KevinVandy/material-react-table#731]
### material-react-table version

v1.15.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

The Material-UI React table has a bug where the positionExpandColumn setting does not work as expected when it is set to 'left'.

When configuring the table to display the expand column on the left using positionExpandColumn="last", it does not render the expand column correctly it is always set to right.

### Minimal, Reproducible Example - (Optional, but Recommended)

positionExpandColumn="last"

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
The point of `postionExpandColumn: 'last'` is to put that column on the far right of the table. What do you expect? I cannot see what the bug is here? Elaborate?

**Comment by KevinVandy** [comment]
Maybe this was a misunderstanding of valid values for `positionExpandColumn`? `"left"` is not a valid value. `"first"` and `"last"` are though
