### ISSUE TITLE
v2 Full Screen not showing on top

### ISSUE THREAD

**Issue by ericstromsodt** [KevinVandy/material-react-table#735]
### material-react-table version

v2

### react & react-dom versions

v18

### Describe the bug and the steps to reproduce it

I migrated to version 2 of MRT. When I click the "full screen" button now, some of my theme's elements are on top of the table and the table no longer fills the browser window. May be related to other z-index issues reported?

![image](https://github.com/KevinVandy/material-react-table/assets/33902904/19a7b84f-15d9-4396-8953-45eab9c4bcc4)

### Minimal, Reproducible Example - (Optional, but Recommended)

I provided a screenshot in the bug description.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I think this is a simple z-index issue. By default, full-screen only bumps up the z-index to 10 for the table paper style. I think I'll bump it to 100, but you can customize it yourself with

```ts
muiTablePaperProps: ({table}) => ({
  style: {
    zIndex: table.getState().isFullScreen ? 1000 : undefined
  }
})
