### ISSUE TITLE
Table do not re-render on subRows change

### ISSUE THREAD

**Issue by cosinus90** [KevinVandy/material-react-table#736]
### material-react-table version

v1.15.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

When data for subRows is being loaded dynamically and rows[*].subRows assigned on data ready - MRT do not re-render. Moreover, changing a field of top-level row do not cause re-render too.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
  useEffect(() => {
    let localRows = rows; 
    const localExpanded = expanded;
    let changed = false;
    for(const i in localRows) {
      const subRows = localRows[i].subRows;
      if (_.isEmpty(subRows[0])) {
        const fetched = store.daily[localRows[i].interval];
        const pushing = [];
        if (!_.isEmpty(fetched)) {
          for (const j in store.hourlyIntervals) {
            const interval = store.hourlyIntervals[j];
            pushing.push(createRow({
              interval: interval,
              clicks: fetched.clicks[interval],
            // there are other columns
            }));
          }
          localRows[i].subRows = pushing;
          changed = true;
          localExpanded[i] = true;
        }
      }
    } 
    if (changed) {
      //localRows[0].interval = 'qqq'; // no effect
      //localRows = localRows.splice(0, 3); // has effect 
      setRows(localRows);
      setExpanded(localExpanded);
    }
  }, [store.daily]);



                  <MaterialReactTable  
                    data={rows}
                    columns={actualColumns}
                    enableBottomToolbar={false}
                    enablePagination={false}
                    enableExpanding={true}
                    state={{ expanded }}
                    onExpandedChange={expandedChange}
                    debugTable={true}
                  />
```

I have daily rows in the table, and I'd like to load hourly data on day row expand. Data is loaded, assigned to subRows, but not showing. If I uncomment //localRows[0].interval = 'qqq';  - all the same, the row remains as it was. If I uncomment //localRows = localRows.splice(0, 3); - qqq is shown and subRows are shown too. 

Initial subRows = [{}] otherwise expand icon not showing - and that empty row is shown on expand.

Is any way to force table or row re-render?

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I think you just need to do `let localRows = [...rows];` ? The table might only rerender if the reference to your data changes

**Comment by cosinus90** [comment]
It not helped. I even made full copy

```
const localRows: any[] = _.cloneDeep(dayRows);
....
console.log('setting rows', localRows);
setDayRows([...localRows]);
```

rows with subRows were printed to the console.

**Comment by cosinus90** [comment]
It was my fault. Setting state at another place overwrites that particular setting.
