### ISSUE TITLE
when calling row.getParentRow() in grouping gives error

### ISSUE THREAD

**Issue by KMJ-007** [KevinVandy/material-react-table#746]
### material-react-table version

1.12.0

### react & react-dom versions

17.0.2

### Describe the bug and the steps to reproduce it

i am using material react table with grouping, when i try to call getParentRow method while in grouping it gives me following error:
<img width="1426" alt="image" src="https://github.com/TanStack/table/assets/86996507/40907fc7-8eaf-44f1-bbb1-71ff1dcd0818">

where customer_name is column id, and the grouping value is AALFA_TEXTILE

### Minimal, Reproducible Example - (Optional, but Recommended)

updating

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KMJ-007** [comment]
not on urgent but i temp fixed using specific version of lib

thankyou

can you guide me on how to fix this issue?

i would love to contribute to the lib

**Comment by KevinVandy** [comment]
Just install the latest version of MRT. TanStack Table had this fixed a couple weeks ago
