### ISSUE TITLE
Removing double space within a string

### ISSUE THREAD

**Issue by VladislavBeluaev** [KevinVandy/material-react-table#750]
### material-react-table version

1.11.2

### react & react-dom versions

5.2.817.0.2

### Describe the bug and the steps to reproduce it

When a line with double space inside comes from the backend, the line is displayed with only 1 space

### Minimal, Reproducible Example - (Optional, but Recommended)

<div
      style={{ height: "auto", width: "100%", overflowY: "auto" }}
      id='table-content-data'
    >
      <MaterialReactTable
        columns={columns}
        data={rows}
        enableRowSelection={false}
        initialState={{ density: "compact" }}
        state={{
          pagination,
          sorting,
          columnFilters,
          globalFilter,
          showSkeletons: loading,
        }}
        onPaginationChange={setPagination}
        onSortingChange={setSorting}
        onColumnFiltersChange={setColumnFilters}
        onGlobalFilterChange={setGlobalFilter}
        rowCount={totalRecords}
        localization={MRT_Localization_RU}
        renderTopToolbarCustomActions={() => {
          return (
            <>
              <Tooltip title='Очистить текущую выборку' arrow>
                <Box className='reset-history-container'>
                  {
                    <Button
                      variant='text'
                      className='button reset-history'
                      sx={{
                        height: "20px",
                        color: theme.palette.error.main,
                      }}
                      onClick={() => resetFilters(true)}
                      startIcon={<RemoveReserve />}
                    />
                  }
                </Box>
              </Tooltip>
              <Tooltip
                title='Запустить анализ участия товаров в акции'
                arrow
                className={runAnalyzeHandler === null ? "d-none" : ""}
              >
                <Box>
                  {
                    <UserDialogComponent
                      key='run-wb-discount-product-analyze'
                      disabled={false}
                      openDialogText='Проверить товары для участия в акции'
                      openDialogIcon={<AnalyticIcon />}
                      agreeActionFunc={() => {
                        runAnalyzeHandler !== null ? runAnalyzeHandler() : null;
                      }}
                      agreeActionText='Продолжить'
                      openedDialogTitle='Запустить анализ участия товаров в акции'
                      openedDialogMessage='После нажатия кнопки "Продолжить", будет запущен расчет рентабельности участия в акции,продолжить?'
                      containerClassname='run-wb-discount-product-analyze'
                    />
                  }
                </Box>
              </Tooltip>
            </>
          );
        }}
        muiTablePaginationProps={{
          rowsPerPageOptions: [5, 10, 20],
          showFirstButton: false,
          showLastButton: false,
          width: "100%",
          className: "pagination",
          ActionsComponent: () =>
            PaginationComponent({ setPagination, pagination, totalRecords }),
        }}
        filterFns={{
          customFilterFn: (row, id, filterValue) => {
            const html = row.getValue(id);
            const organisation =
              html?.props?.children[0]?.props?.children[0]?.props?.children[1]
                ?.props?.children;
            const number =
              html?.props?.children[1]?.props?.children[0]?.props?.children[1]
                ?.props?.children;
            if (organisation || number) {
              const array = [organisation, number];
              return array.some((e) => e?.includes(filterValue));
            }
            return false;
          },
        }}
      />
    </div>

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/41303862/0d10767e-e4c5-4b8a-9c07-94f9cc9ec113)
![image](https://github.com/KevinVandy/material-react-table/assets/41303862/d5f66630-f837-410b-b9f6-c07098497da8)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Use a `<pre>` tag to render stuff like that in a custom `Cell` render. The browser automatically does that. This has nothing to do with MRT.
