### ISSUE TITLE
Custom Edit component doesn't return correct values on edit

### ISSUE THREAD

**Issue by GustavoContreiras** [KevinVandy/material-react-table#757]
### material-react-table version

^2.0.0-beta.15

### react & react-dom versions

18

### Describe the bug and the steps to reproduce it

When I click to save the row, the `values` field `onEditingRowSave` returns the original value for the columns that have `Edit` component set

### Minimal, Reproducible Example - (Optional, but Recommended)

When I click to save the row, the `values` field `onEditingRowSave` returns the original value for the columns that have `Edit` component set

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is a bit hard to debug without a sandbox. But also, if you have a custom `Edit` component, you have to hook up `onChange` handlers to mutate the `_valuesCache` of the row if you want the internal `onEditingRowSave` functions to work properly. This could admittedly be better documented.

**Comment by GustavoContreiras** [comment]
Thanks for the clarification @KevinVandy 
Thanks for creating this library too. It's incredible. The version 2 is much cleaner.
I achieved my goal by using the `editVariant`, `editSelectOptions` and `muiEditTextFieldProps`. 
I didn't really need a custom edit component. What you've built is really impressive.
