### ISSUE TITLE
Column filtering highlight doesn't appear if it filters for zero value

### ISSUE THREAD

**Issue by paolapog** [KevinVandy/material-react-table#761]
### material-react-table version

2.0.0-beta.15

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Try to filter a text column with a "zero value", it doesn't appear any highlighting.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
() => <MaterialReactTable columns={[{
  header: 'First Name',
  accessorKey: 'firstName'
}, {
  header: 'Last Name',
  accessorKey: 'lastName'
}, {
  header: 'Age',
  accessorKey: 'age'
}, {
  header: 'Gender',
  accessorKey: 'gender',
  filterFn: 'customFn'
}, {
  header: 'Address',
  accessorKey: 'address'
}, {
  header: 'State',
  accessorKey: 'state',
  filterFn: 'customFn'
}]} data={data} initialState={{
  showColumnFilters: true
}} filterFns={{
  customFn: (row, _columnIds, filterValue) => {
    console.info('customFn', row, _columnIds, filterValue);
    return row.getValue<string>('state').toLowerCase().startsWith(filterValue.toLowerCase());
  }
}} />
```
I think it can happen with whatever table with filters

### Screenshots or Videos (Optional)

<img width="1489" alt="Screenshot 2023-10-27 at 16 48 14" src="https://github.com/KevinVandy/material-react-table/assets/44196268/80251e0f-989c-41b7-9415-15833d4cf816">
<img width="1499" alt="Screenshot 2023-10-27 at 16 48 25" src="https://github.com/KevinVandy/material-react-table/assets/44196268/41795e03-d888-4421-9bcc-e45798ceaf12">

### Do you intend to try to help solve this bug with your own PR?

Yes, I am also opening a PR that solves the problem along side this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in 2.0.0
