### ISSUE TITLE
Attempted import error: 'useMaterialReactTable' is not exported from 'material-react-table' 

### ISSUE THREAD

**Issue by mlapenna7** [KevinVandy/material-react-table#770]
### material-react-table version

v2.0

### react & react-dom versions

v18.2

### Describe the bug and the steps to reproduce it

while trying to compile npm run build today, I got this error:
> react-scripts build

Creating an optimized production build...
Failed to compile.

Attempted import error: 'useMaterialReactTable' is not exported from 'material-react-table' (imported as 'useMaterialReactTable').

I was following the example CRUD example, which had this import: 
import {
  MaterialReactTable,
 // createRow,
  useMaterialReactTable,
} from 'material-react-table';

When I changed to this, it worked:
import   useMaterialReactTable, {  MaterialReactTable } from 'material-react-table';

Others are going to run across this as well.  I don't know if it was present in v1.x.  This is the first time I was following the example using const table = UseMaterialReactTable({...
rather than <MaterialReactTable...>

### Minimal, Reproducible Example - (Optional, but Recommended)

I described it above.

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
`useMaterialReactTable` did not exist in V1. It is a new feature. https://www.material-react-table.com/migrating-to-v2

If you are still using MRT V1, you can look at examples on the v1 site: https://v1.material-react-table.com/

But I recommend taking a look at the [migrating guide](https://www.material-react-table.com/migrating-to-v2)  and upgrading to V2. It's not that hard of an upgrade, but you just need to make sure the correct packages are installed.

For the most part V2 is backwards compatible with v1. Just read the migration guide.

Edit: to clarify V2 was only released last Friday, October 27.

**Comment by KevinVandy** [comment]
I'm temporarily adding this banner to the examples in the docs: 

<img width="1296" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/c8fb612e-437d-42cb-827a-e5a191ad3ce1">

But you can also find the V1 docs in the upper left-hand corner too:

<img width="620" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/39aeb15b-0e9c-4754-bb42-163e0def4bd9">

**Comment by mlapenna7** [comment]
Thanks Kevin, I followed the migration guide exactly and I am good now.  Thanks for the note.
