### ISSUE TITLE
pagination.pageIndex resets to initialState.pagination.pageIndex on re-render/update

### ISSUE THREAD

**Issue by kennsorr** [KevinVandy/material-react-table#776]
### material-react-table version

^2.0.0-beta.0

### react & react-dom versions

^18.2.0

### Describe the bug and the steps to reproduce it

I'm using `setInterval` in a `useEffect` hook to fetch recent records every few seconds, then setting the `rows` state, causing the table to re-render. 

The problem is that I would like to stay on the current page even when the rows update. I've tried a few things, but it seems like there is no way to prevent the `pagination.pageIndex` state from changing back to `initialState.pagination.pageIndex` (default is 0). Changing the value of `initialState.pagination.pageIndex` after mount doesn't work either.

I think reseting the `pagination.pageIndex` to `initialState.pagination.pageIndex` makes sense on mount/unmount, but not on every update.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.com/docs/examples/remote#remote-source-code

On this table, wrapping this the fetchData() function on line 83 in a `setInteral` callback.

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by MrAdex77** [comment]
have the same problem +

**Comment by nichita-pasecinic** [comment]
Adding `rowCount` fixed the problem for me on v1, mb it works on v2 as well

**Comment by shakif95** [comment]
Having the exact same issue +

Update: found the solution(v1)
`autoResetPageIndex={false}` should fix the issue

**Comment by shakif95** [comment]
> Adding `rowCount` fixed the problem for me on v1, mb it works on v2 as well

Can you please share a bit more detail? Like do you use it with manual pagination or something? A short example would be nice. Thanks in advance.

**Comment by nichita-pasecinic** [comment]
> Can you please share a bit more detail? Like do you use it with manual pagination or something? A short example would be nice. Thanks in advance.

```tsx
<MaterialReactTable
          state={{ pagination, sorting: sorting }}
          enableMultiSort={false}
          rowCount={rowCount} // all rows in the table
          pageCount={pageCount} // rowCount divided by pageSize
          onPaginationChange={setPagination}
          onSortingChange={setSorting}
          enableSorting
          enablePagination
          manualPagination
          manualSorting
        />
```

**Comment by kennsorr** [comment]
@shakif95 Did that work for you? I was only able to solve this by setting `manualPagination` to `true`, in addition to adding `rowCount` and `pageCount`. Unfortunately, this means I had to add all the pagination logic.

```
   \\ ...
    const [pagination, setPagination] = useState({ pageIndex: 0, pageSize: 10 });
    const startIndex = pagination.pageIndex * pagination.pageSize;
    const endIndex = startIndex + pagination.pageSize;

    const displayedData = rows.slice(startIndex, endIndex);

    const totalPages = Math.ceil(rows.length / pagination.pageSize);

    useEffect(() => {
        if (pagination.pageIndex >= totalPages) {
            setPagination((prev: any) => ({ ...prev, pageIndex: totalPages - 1 < 0 ? 0 : totalPages - 1 }));
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [rows.length, pagination.pageSize, totalPages]);

    const table = useMaterialReactTable({
        onColumnVisibilityChange: setColumnVisibility,
        onPaginationChange: setPagination,
        columns,
        data: displayedData,
        enableColumnOrdering: true,
        enableGlobalFilter: false,
        paginationDisplayMode: 'pages',
        muiPaginationProps: {
            color: 'primary',
            shape: 'rounded',
            showRowsPerPage: true,
            variant: 'outlined',
        },
        // custom pagination
        manualPagination: true,
        pageCount: totalPages,
        rowCount: rows.length,
        initialState: {
            columnVisibility,
            pagination: pagination,
            sorting: [{ id: defaultSortBy, desc: true }],
        },
        state: {
            columnVisibility,
            pagination,
            isLoading,
        },
        layoutMode: 'grid',
        enableTopToolbar: hideToolbar ? false : true,
        enableTableFooter: hidePagination ? false : true,
        enableBottomToolbar: hidePagination ? false : true,
        enableGrouping: false,
        enableRowSelection: false,
        enableColumnDragging: false,
    });

    return <MaterialReactTable table={table} />;
```

**Comment by shakif95** [comment]
> autoResetPageIndex={false}

Hey @kennsorr - I did not use `manualPagination`. Only enabled autoResetPageIndex={false} and that stopped resetting the page index on the first render after I fetched the data again. I'm still on V1 though.

**Comment by kennsorr** [comment]
Resolved by `autoResetPageIndex={false}`

**Comment by kennsorr** [comment]
Resolved by autoResetPageIndex={false}
