### ISSUE TITLE
_b.select is not a function

### ISSUE THREAD

**Issue by ISvirko** [KevinVandy/material-react-table#777]
### material-react-table version

2.0.1

### react & react-dom versions

18.1.0

### Describe the bug and the steps to reproduce it

When setting table columnFilterDisplayMode: "popover" and setting column filterVariant to "multi-select" on clicking the filter icon the following error appears:
Uncaught TypeError: _b.select is not a function at MRT_TableHeadCellFilterLabel.tsx:106:1

Is there a way to use conditional chaining here?
`filterInputRefs.current[`${column.id}-0`]?.focus?.();
  filterInputRefs.current[`${column.id}-0`]?.select?.();`

### Minimal, Reproducible Example - (Optional, but Recommended)

`
const columns = [
{
        accessorKey: 'orderStatus',
        header: "Order Status",
        filterVariant: "multi-select",
      }
]

const data = [{orderStatus: 'New'}]

const table = useMaterialReactTable({
    data,
    columns,
    columnFilterDisplayMode: "popover",
    enableFacetedValues: true,
  });`

### Screenshots or Videos (Optional)

<img width="252" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/60234391/691ec7ec-60d0-405a-8952-9a6298aa4a78">

<img width="230" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/60234391/081d1bb5-f8da-4b5e-8f87-130189518a7e">

### Do you intend to try to help solve this bug with your own PR?

Yes

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Yeah I'll release a patch that does this, but I'm struggling to reproduce this error. Do you want to PR? Otherwise I'll release in a couple hours.
