### ISSUE TITLE
V2 

### ISSUE THREAD

**Issue by jad-grepr** [KevinVandy/material-react-table#785]
### material-react-table version

v2.0.2

### react & react-dom versions

react 11.11.1,  react-dom 2.0.2

### Describe the bug and the steps to reproduce it

I have a table with an array-valued input data, which I'm accessing as string like this: 
```
const tagAccessorFn = (tag: string) => (row: ILogEvent) : string => {
  const tagValue = row?.tags?.[tag] || [];
  return tagValue.join(', ');
}

~~~~

  const tagCols: MRT_ColumnDef<ILogEvent>[] = tagKeys.map((tagKey: string) => ({
    header: `~${tagKey}`,
    id: `~${tagKey}`,
    accessorFn: tagAccessorFn(tagKey),
    filterVariant: 'multi-select',
    enableColumnFilterModes: false,
    size: 240,
  }));
```

When data is loaded, I'm getting this:

```
filterFns.ts:8 Uncaught TypeError: filterValue.toLowerCase is not a function
    at Object.includesString [as filterFn] (filterFns.ts:8:1)
    at memo.key (getFilteredRowModel.ts:97:1)
    at Object._getFilteredRowModel (utils.ts:168:1)
    at table.getFilteredRowModel (Filters.ts:613:1)
    at table.getPreGroupedRowModel (Grouping.ts:344:1)
    at table.getGroupedRowModel (Grouping.ts:351:1)
    at table.getPreSortedRowModel (Sorting.ts:526:1)
    at getSortedRowModel.ts:8:1
    at Object._getSortedRowModel (utils.ts:153:1)
    at table.getSortedRowModel (Sorting.ts:536:1)
```

Seems like there's some typing mismatches on filters, but the system should be able to handle it gracefully. It would be nice to write a docs section on using typed `filterFn`s rather than naming or something like that...

### Minimal, Reproducible Example - (Optional, but Recommended)

Please see bug description.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by jad-grepr** [comment]
Also thank you for this awesome library! It saved me months of development on my own!!

**Comment by KevinVandy** [comment]
was not really able to tell what this issue was describing, but you can define filterFn functions in the column definition or the filterFn table option
