### ISSUE TITLE
Browser becomes unresponsive when using navigation

### ISSUE THREAD

**Issue by MonkeyKiki** [KevinVandy/material-react-table#800]
### material-react-table version

2.0.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Even with a really simple usecase with static data and pagination, when I choose a page size or a page number, my browser become unresponsive

### Minimal, Reproducible Example - (Optional, but Recommended)

```
import { MaterialReactTable, useMaterialReactTable } from "material-react-table";
import { useMemo } from "react";

export default function App() {
    const columns = useMemo(
        () => [
            {header: "Period", accessorKey: 'monthStart'},
            {header: "ID", accessorKey: "id"}
        ],
        []
    );

    const data = [
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
        { monthStart: '2021-01-01',id: 25 },
    ];

    const table = useMaterialReactTable({
        columns,
        data
    });

    return <MaterialReactTable table={table} />;
}

```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You're making the classic mistake of not giving your data a stable reference in either useState or - useMemo or defined outside of the component or other state management. Defining data like how you are will cause an infinite render.

**Comment by MonkeyKiki** [comment]
That was indeed the problem. Thank you for your answer and sorry for the inconvenience
