### ISSUE TITLE
Change text tooltip "Collapse", "Collapse All", "Show/Hide Columns"

### ISSUE THREAD

**Issue by duyhd** [KevinVandy/material-react-table#811]
### material-react-table version

v2.0.4

### react & react-dom versions

v17

### Describe the bug and the steps to reproduce it

[](url)I use material-react-table and have the following problem. I want to change the text of the tooltips of the following images. Can anyone help me?

### Minimal, Reproducible Example - (Optional, but Recommended)

[](url)
![Screenshot 2023-11-13 153414](https://github.com/KevinVandy/material-react-table/assets/49530713/eab94c84-fbfb-4896-ab29-c56b5df0e462)
![Screenshot 2023-11-13 153245](https://github.com/KevinVandy/material-react-table/assets/49530713/cb9e8751-0825-413a-a120-9af85d0be771)
![Screenshot 2023-11-13 153424](https://github.com/KevinVandy/material-react-table/assets/49530713/bc08ca20-4bd1-4db4-b64c-0e99eea42834)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Read the docs https://www.material-react-table.com/docs/guides/localization
