### ISSUE TITLE
Column data does not update?

### ISSUE THREAD

**Issue by ghost** [KevinVandy/material-react-table#815]
### material-react-table version

1.15.1

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I have a select box on the top and a table below, when I change the selection in the select box, I need to do some little calculations on the table data. I am using accessorFn to define column, but I found that arrow function after accessorFn does not execute, any comments will be appreciated? 

### Minimal, Reproducible Example - (Optional, but Recommended)

[
https://stackblitz.com/edit/stackblitz-starters-rkapav?description=A%20create-react-app%20project%20based%20on%20react%20and%20react-dom&file=src%2FApp.js,src%2Fhome-page.jsx&title=React%20Starter](url)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
@qxg200 Found a solution: https://stackblitz.com/edit/stackblitz-starters-mawtxg?file=src%2Fhome-page.jsx

Just need to clear the valueCache for each row if using dynamic accessorFns

```ts
  const handleOptionChange = (event) => {
    setOption(event.target.value);
    table.getRowModel().rows.forEach((row) => {
      row._valuesCache = {};
    });
  };
```

**Comment by KevinVandy** [comment]
I think tanstack table itself might have an improvement around disabling the row value cache in certain situations soon.
