### ISSUE TITLE
Change rotation of icon expan all / collapse all of table

### ISSUE THREAD

**Issue by duyhd** [KevinVandy/material-react-table#817]
### material-react-table version

v2.0.4

### react & react-dom versions

v17

### Describe the bug and the steps to reproduce it

I want to change the rotation of icon of expand all or collapse all of table. Can anyone help me?

### Minimal, Reproducible Example - (Optional, but Recommended)

![Screenshot 2023-11-14 092508](https://github.com/KevinVandy/material-react-table/assets/49530713/d98b0a8f-95aa-4676-ba45-04bc2ec14f0d)
![Screenshot 2023-11-14 092456](https://github.com/KevinVandy/material-react-table/assets/49530713/a94824fd-b6b9-4e9d-a2dd-be542ef92195)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
you can easily do this with `muiExpandAllButtonProps`

```js
muiExpandAllButtonProps: ({ table }) => ({ 
  style: { //or sx
    transform: table.getIsAllRowsExpanded() ? 'rotate(90deg)' : 'rotate(0)' //or whatever values
  }
})
