### ISSUE TITLE
Unable to customize renderRowAction buttons while in editing mode

### ISSUE THREAD

**Issue by wmoore8** [KevinVandy/material-react-table#818]
### material-react-table version

v.2.0.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Recently upgraded to V2, and almost every step of the upgrade has translated nicely from the previous version **except** my old implementation of customizing renderRowAction buttons while in editing mode. 

I am curious, since the documentation doesn't give a clear example, how to change my renderRowActions buttons when I'm actively editing the row (i.e. the Save and Cancel buttons seen here)
<img width="455" alt="Screen Shot 2023-11-13 at 3 52 11 PM" src="https://github.com/KevinVandy/material-react-table/assets/38674278/88c8e1ca-be3f-46b1-b9bb-d0a6ec262c91">

My old implementation of the above was fairly complex, but involved checking the editing mode via comparing id's of the current row
`table.getState().editingRow?.id === currentRow.id`

As far as I can tell, this still works, however, when I click edit, the action items return back the default buttons and styling, and not the custom ones I want to pass in with custom styling.

Is there something that happened in the upgrade that wasn't documented that would affect this behavior? Or, better yet, is there a simpler way of targeting those and styling the Cancel and Save buttons while actively in row editing?

### Minimal, Reproducible Example - (Optional, but Recommended)

`table.getState().editingRow?.id === currentRow.id`

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I know I fixed some bugs around this for v2. You can always just provide a `Cell` render override for the mrt-actions column using the `displayColumnDefOptions` table option.

https://www.material-react-table.com/docs/guides/display-columns
