### ISSUE TITLE
Column DnD and resizing gets very slow when the number of columns/rows increases

### ISSUE THREAD

**Issue by nathsou** [KevinVandy/material-react-table#822]
### material-react-table version

v2.0.4

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Hi,
Thanks for the great work on this library.

In my experiments, the rendering performance of the table gets bad quite quickly as the number of columns or rows increases (even with virtualization enabled) when compared to @mui-x/data-grid-pro.

For instance, loading a page or resizing/reordering columns with a table with over 50 columns and 100 rows (with or without virtualization) takes a much longer time, in particular in development mode compared to a Mui's DataGrid.

**Steps to reproduce:**
1. Create a table with 50 columns and 100 rows (more or less depending on your computer)
2. Try resizing and reordering the columns using DnD
3. Now increase the number of columns or rows
4. Retry resizing and reordering the columns using DnD, the performance should be worse

**Expected behavior:**
I would expect the DnD feature (before dropping a column) and the resizing feature (in `onEnd` mode) to be as performant with 1 row/column as with 1000 as all the rows should not need to be rerendered during the resizing/dragging actions.

Here are examples, both with 100 columns and 100 rows:
[Material React Table](https://codesandbox.io/p/sandbox/confident-aj-68458c?file=%2Fsrc%2FJS.js%3A17%2C26&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp1797210008356ghhgat8o9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp1797210003356gz0iyinfo%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp1797210005356g3z9hor3z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp1797210007356gs18zbftn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp1797210003356gz0iyinfo%2522%253A%257B%2522id%2522%253A%2522clp1797210003356gz0iyinfo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FmakeData.ts%2522%252C%2522id%2522%253A%2522clp179r5d0093356gtwd7a91d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522id%2522%253A%2522clp179vo400b4356glbpi51qk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FTS.tsx%2522%252C%2522id%2522%253A%2522clp17tpod004q356g5rioyu8r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp17tpod004q356g5rioyu8r%2522%257D%252C%2522clp1797210007356gs18zbftn%2522%253A%257B%2522id%2522%253A%2522clp1797210007356gs18zbftn%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clp17kb54024k356gdr3f7e7i%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp17kb54024k356gdr3f7e7i%2522%257D%252C%2522clp1797210005356g3z9hor3z%2522%253A%257B%2522id%2522%253A%2522clp1797210005356g3z9hor3z%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clp17k8jk0219356g7vqgm7uh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp17k8jk0219356g7vqgm7uh%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
[Mui DataGrid](https://codesandbox.io/s/serene-pine-9nx4gw?file=/src/Demo.tsx)

Am I doing something wrong or do you see where these performance issues could be coming from?

Thanks for you help!

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/sandbox/confident-aj-68458c?file=%2Fsrc%2FmakeData.ts%3A2%2C26

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by oliverfrost1** [comment]
Your MRT example only has 5 columns.

**Comment by KevinVandy** [comment]
This example wasn't very good since it only had 5 columns, but the new v2.8.0 release has better performance for column resizing and column dragging.

As with anything, as the number of elements on the pages grow, we should expect performance to drop. Features like virtualization can help, and the stability and compatibility of row and column virtualization with other table features has also improved greatly in the last couple of releases.

So lots of improvements on this front have been shipped. But expect even more significant improvements once MUI ships Material UI v6, as that will get rid of Emotion runtime CSS, which is a significant performance constraint right now, especially with virtualization features. Much more to come on this.
