### ISSUE TITLE
Meta object not recognizing its properties (Typescript error)

### ISSUE THREAD

**Issue by MohammadElokour** [KevinVandy/material-react-table#828]
### material-react-table version

2.0.4

### react & react-dom versions

18.2.0 

### Describe the bug and the steps to reproduce it

When defining properties in the meta object inside the useMaterialReactTable hook.
After calling those properties everything works but I get a typescript error: 

Property "propertyName" does not exist on type "TableMeta\<RowsDataType\>" .ts(2339)

Checking the tanstack documentation: 
https://tanstack.com/table/v8/docs/api/core/table#meta

it mentions a way to extend the type to suite the added methods as follows: 

```
declare module '@tanstack/table-core' {
  interface TableMeta<TData extends RowData> {
    foo: string
  }
}
```

is there a MRT equivalent? 
cant seem to find much in the documentation on the "meta object" other than it being mentioned as a table option:
https://www.material-react-table.com/docs/api/table-options
number 99

### Minimal, Reproducible Example - (Optional, but Recommended)

Definition of meta properties
```
const table = useMaterialReactTable({
    ....
    meta: {
      addRow: () => {
        //logic for adding row
      },
      removeSelectedRows: () => {
        //logic for removing selected rows
      },
    },
  });
```

  
Usage of meta properties 
```
 type Props = {
    table: MRT_TableInstance<TCRowData>;
 };

const CustomToolbar: React.FC<Props> = ({ table }) => {
  const meta = table.options.meta;
  return (
    <Grid
       item
       container
       alignItems="center"
       gap={0.75}
       wrap="nowrap"
       >
        <AddRow
          onClick={() => meta?.addRow()}
          className="cursor-pointer !min-w-[1.5rem] w-6 h-6"
        />
        <TrashIcon
          onClick={() => meta?.removeSelectedRows()}
          className="cursor-pointer !min-w-[1.5rem] w-6 h-6"
        />
    </Grid>
   )
 }
```
 

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/48622340/d0f5132f-50fd-4ae4-b93a-4d6bdf229ca1)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
You would have to do declaration merging with the MRT types from `material-react-table` instead `@tanstack/table-core`

**Comment by thafer30** [comment]
I can't seem to find the type for the meta field in `material-react-table` that I need to override. 

I've tried to follow the types to figure out what the `MRT_*` type is for the meta type but it seems to resolve to the `@tanstack/table-core` type `TableMeta`.

Type `MRT_TableInstance` contains options which is of type `MRT_StatefulTableOptions` which adds onto `MRT_DefinedTableOptions` which adds onto `MRT_TableOptions` which gets the meta type from `TableOptions` from `@tanstack/table-core`.

Was anyone able to get this to work successfully?  Any help would be greatly appreciated. Love the project by the way!

**Comment by ryanmk54** [comment]
I tried declaration merging via material-react-table instead of @tanstack/table-core, but I still get the error that the property doesn't exist.
```
declare module 'material-react-table-2' {
  interface TableMeta<TData> {
    apInvoiceId: number
    updateInvItem: (li: Partial<ApVendorInvoiceLineItem>) => Promise<void>
  }

  interface ColumnMeta<TData, TValue> {
    apLineItemComments: ApLineItemComment[]
    addInvItemToPoItem: ReturnType<typeof useAddNextInvItemToPoItem>
    deleteRow: ReturnType<typeof deleteInvLineItem>
    maxInvLineNo: number
  }
}
...
        table.options.meta.updateInvItem({
...
  const comments = cell.column.columnDef.meta.apLineItemComments.filter(


```
typescript: Property 'updateInvItem' does not exist on type 'TableMeta<CellData>'. [2339]
typescript: Property 'apLineItemComments' does not exist on type 'ColumnMeta<CellData, unknown>'. [2339]

I used material-react-table-2 because it is aliased that way in package.json.
```
    "material-react-table-2": "npm:material-react-table@2",
```

**Comment by johnharringt0n** [comment]
@thafer30 @ryanmk54 Hi all, I'm hitting the same issue using Material React Table 3 where I can't seem to augment the `meta` type either via `material-react-table`, `@tanstack/react-table` or `@tanstck/table-core`. I was wondering if either of you ended up finding a solution?
