### ISSUE TITLE
Pagination Styling

### ISSUE THREAD

**Issue by SvenMollenhauer** [KevinVandy/material-react-table#830]
### material-react-table version

2.0.4

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

First of all: v2 is amazing so far, thank you for the amazing work.

While upgrading to v2 I realized the Pagination no longer has the css class `MuiTablePagination-root`. I did a lot of styling in v1 via css, this makes it a bit more complicated (though i found a temporary workaround for now)

I tried using muiPaginationProps to set this class again via `className' , but this didnt work as well. 

### Minimal, Reproducible Example - (Optional, but Recommended)

Screenshot below is from one of the pagination examples: https://codesandbox.io/p/devbox/material-react-table-example-remote-7n2vhr

I also tried adding `muiPaginationProps: { className: "someClassName" }` as property, but it didnt seem to change anything as well.

### Screenshots or Videos (Optional)

![grafik](https://github.com/KevinVandy/material-react-table/assets/142878078/471f0eff-ba03-44c0-935c-b30de8604b1c)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
yeah the pagination component got rewritten in v2, as the built-in MUI one had a ton of issues I had to constantly override and fix. 

<img width="1271" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/eeca3a9b-2307-46ee-8299-7bef3ec4ff9b">
