### ISSUE TITLE
SortIcon option not working

### ISSUE THREAD

**Issue by emafru90** [KevinVandy/material-react-table#831]
### material-react-table version

2.0.4

### react & react-dom versions

react": "^18.2.0",     "react-dom": "^18.2.0",

### Describe the bug and the steps to reproduce it

If i add pass in icon table parameter:
 SortIcon: (props: StyleIconProps) => (
      <IconSVG icon="cancel" size={18} {...props} />
  )

with my custom icon set, doestn work, because sort icon is default. This approach work with all other icon.

### Minimal, Reproducible Example - (Optional, but Recommended)

 const icons: Partial<MRT_Icons> = {
    KeyboardDoubleArrowDownIcon: () => <IconSVG icon="cancel" size={18} />,
    ArrowDownwardIcon: (props: StyleIconProps) => (
      <IconSVG icon="cancel" size={18} {...props} />
    ),
    ClearAllIcon: () => <IconSVG icon="cancel" size={18} />,
    DensityLargeIcon: () => <IconSVG icon="cancel" size={18} />,
    DensityMediumIcon: () => <IconSVG icon="cancel" size={18} />,
    DensitySmallIcon: () => <IconSVG icon="cancel" size={18} />,
    DragHandleIcon: () => <IconSVG icon="cancel" size={18} />,
    FilterListIcon: (props: StyleIconProps) => (
      <IconSVG icon="cancel" size={18} {...props} />
    ),
    FilterListOffIcon: () => <IconSVG icon="cancel" size={18} />,
    FullscreenExitIcon: () => <IconSVG icon="cancel" size={18} />,
    FullscreenIcon: () => <IconSVG icon="cancel" size={18} />,
    SearchIcon: (props: StyleIconProps) => (
      <IconSVG icon="cancel" size={18} {...props} />
    ),
    SearchOffIcon: () => <IconSVG icon="cancel" size={18} />,
    ViewColumnIcon: () => <IconSVG icon="cancel" size={18} />,
    MoreVertIcon: () => <IconSVG icon="cancel" size={18} />,
    MoreHorizIcon: () => <IconSVG icon="cancel" size={18} />,
    PushPinIcon: (props: StyleIconProps) => (
      <IconSVG icon="cancel" size={18} {...props} />
    ),
    VisibilityOffIcon: () => <IconSVG icon="cancel" size={18} />,
    SortIcon: (props: StyleIconProps) => (
      <IconSVG icon="cancel" size={18} {...props} />
    ),
  };

const table = useMaterialReactTable({
    columns,
    data,
    enableRowSelection: true,
    enableRowActions: true,
    paginationDisplayMode: 'pages',
    icons: icons
})

   <div className="container mx-auto">
      <ThemeProvider theme={createTheme(theme)}>
        <MaterialReactTable table={table} />
        <div className="table-pagination">
          <MRT_TablePagination table={table} />
        </div>
      </ThemeProvider>
    </div>

### Screenshots or Videos (Optional)

![Screenshot 2023-11-21 alle 12 46 11](https://github.com/KevinVandy/material-react-table/assets/146420545/d23610d8-8f01-4a0f-8b59-868acc079f2c)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
replace the `SyncAlt` mui icon to change the unsorted sort icon

**Comment by vivek-kansara060** [comment]
@KevinVandy, What do you mean by replace the SyncAlt mui icon?
how to do that?
