### ISSUE TITLE
Columns order not respected for columns containing other columns

### ISSUE THREAD

**Issue by PeretEtienne** [KevinVandy/material-react-table#84]
### material-react-table version

1.0.4

### Describe the bug and the steps to reproduce it

When there is columns containing other columns they seem to be pushed at the end of the table, not respecting order of the column definitions. 

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

[Columns order not respected for columns containing other columns](https://codesandbox.io/s/ecstatic-carlos-h83915?file=/src/App.js)

### Do you intend to try to help solve this bug with your own PR?

No, because I don't know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Thanks for reporting this. This should be fixed as of `v1.0.5`

https://codesandbox.io/s/confident-orla-rtpp44?file=/src/App.js

**Comment by PeretEtienne** [comment]
So quick. It works fine for me. Thx again
