### ISSUE TITLE
Clicking on the resize icon , causes a re-draw and the focus gets lost

### ISSUE THREAD

**Issue by miladavarni** [KevinVandy/material-react-table#841]
### material-react-table version

1.15.0 and 2.0

### react & react-dom versions

"react-dom": "^17.0.2",  "react": "^17.0.2",

### Describe the bug and the steps to reproduce it

1- Enable virtualisation 
2- enable column resizing
3- Scroll down through the table
4- Click on the resize handle  => The table jumps back up and the scroll position gets lost

### Minimal, Reproducible Example - (Optional, but Recommended)

Both the V2 and V1 version have this issue and can be replicated on the example docs

https://stackblitz.com/github/KevinVandy/material-react-table/tree/v1/apps/material-react-table-docs/examples/enable-row-virtualization/sandbox?file=src%2FTS.tsx

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/129340383/35ccf345-5fdc-46bf-a507-58a876421c4b

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [x] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by Param-Singh** [comment]
hi @KevinVandy 
Can you assign this to me, Having close to 2 years experience in React,
I believe I can fix this .

**Comment by KevinVandy** [comment]
> hi @KevinVandy 
> Can you assign this to me, Having close to 2 years experience in React,
> I believe I can fix this .

No need for assignment, if you have a fix, make the pr

**Comment by KevinVandy** [comment]
I don't really see this as an issue? Isn't that just how the browser works? Unless there is a solution to keeping text highlighted when clicking somewhere else, just going to close this.
