### ISSUE TITLE
Bug combining row-pinning and filters

### ISSUE THREAD

**Issue by kuket15** [KevinVandy/material-react-table#857]
### material-react-table version

v2+

### react & react-dom versions

doesn't matter

### Describe the bug and the steps to reproduce it

I'm not really using v2 yet, but I just found a client side exception directly in the documentation and I feel morally obligated to report it :)

> Open [row-pinning#alternative-selection-row-pinning-ui](https://www.material-react-table.com/docs/guides/row-pinning#alternative-selection-row-pinning-ui)

> Flag (aka pin) a couple of rows

> Filter for something not matching the pinned rows

> Unflag (aka unpin) a row

> Application error: a client-side exception has occurred (see the browser console for more information)

Thanks for such a beautiful library

Luca

### Minimal, Reproducible Example - (Optional, but Recommended)

.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Thanks for reporting. I think I've isolated it to only the select row pinning variants.

**Comment by KevinVandy** [comment]
This has been fixed in v2.1.0
