### ISSUE TITLE
Setting positionActionsColumn="last" not working as expected

### ISSUE THREAD

**Issue by windcheck** [KevinVandy/material-react-table#86]
### material-react-table version

v1.0.5

### Describe the bug and the steps to reproduce it

On `MaterialReactTable` props:

1. Set `editingMode="cell"`
2. Set `positionActionsColumn="last"`
3. Change `editingMode` to `modal`

As we change from `editingMode="cell"` to `editingMode="modal"` the actions column appears on an unexpected position (first column).

### Your Minimal, Reproducible Example - Sandbox (Recommended) or code snippets

https://codesandbox.io/s/strange-andras-440o9j?file=/src/App.js

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in `v1.0.6`
