### ISSUE TITLE
Duplicate Filters When Using Column Groups

### ISSUE THREAD

**Issue by evan-buss** [KevinVandy/material-react-table#861]
### material-react-table version

v2.0.4

### react & react-dom versions

v17

### Describe the bug and the steps to reproduce it

When using column groups there are 2 filter rows for "non-grouped" columns.

![image](https://github.com/KevinVandy/material-react-table/assets/18509589/2f6989f2-1aa2-4b41-9068-97a41b202744)

Is there a way to disable / hide the duplicated filter row?

### Minimal, Reproducible Example - (Optional, but Recommended)

[Forked example from your "Basic Example" documentation page](https://stackblitz.com/edit/github-fwfjdu?file=src%2FTS.tsx). The only change was to put the first / last name columns in a group and show the filter by default.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This usually happens from when you accidentally add an accessor to a group column. Or it can happen if the grouping of nested columns has inconsistent depths. Like the other 3 columns outside of the "Name" column group need to have their own parent.
