### ISSUE TITLE
Columns not showing in toggle hidding 

### ISSUE THREAD

**Issue by NolanAntonn** [KevinVandy/material-react-table#870]
### material-react-table version

2.0.5

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

Hello,

I'm encountering an issue with Material React Table (MRT) in a dynamic environment using MobX and websockets. My setup is designed to update MRT dynamically, responding to data changes via websockets. The objective is to have a table that reflects real-time updates, whether new responses arrive or titles change through API calls. I've effectively managed the state and most functionalities work seamlessly. However, I'm faced with a specific, persistent issue: despite everything functioning beautifully, my columns do not appear in the toggle for hiding/showing columns in MRT.

**Environment:**

- React
- Material React Table
- MobX for state management
- Websockets for real-time data updates

### **Issue Description:**

The specific problem is that the dynamically defined columns do not appear in the toggle list for showing/hiding columns in MRT. This issue persists despite various attempts to resolve it.

### Implementation Details:

**Dynamic Column Definition:**

I define columns dynamically through an API call in a MobX store. The columns are meant to update in response to real-time data changes from the websocket.

Code Snippet for Column and Data Initialization in React Component:

```
<MaterialReactTable
  columns={answersStore.headers}
  data={answersStore.data}
  enableRowSelection={true}
/>
```
Columns are defined as:

```
const columns = useMemo(
  () => answersStore.headers || [],
  [answersStore.headers]
);
```
Data is defined as:

`const data = useMemo(() => answersStore.data || [], [answersStore.data]);`

MobX Store Handling:

In the MobX store, I have a transformHeadersToColumns function that maps API response headers to MRT column format.

```
transformHeadersToColumns(headers) {
  return headers.map((header) => {
    let column = {
      accessorKey: header.idCanvas,
      id: header.idCanvas,
      key: header.idCanvas,
      header: header.label,
      userId: header.idCanvas,
      type: header.type || '',
      enableHiding: true,
      enableClickToCopy: true,
    }

    return column
  });
}

const response = await collectFormAnswersData(this.url_code);
runInAction(() => {
  this.data = response.results.rows;
  this.totalRows = response.count;
  this.headers = this.transformHeadersToColumns(response.results.headers);
});
```
**An Intriguing Observation:**

Interestingly, when I use the following code:

```
<MaterialReactTable
  columns={answersStore.headers}
  data={answersStore.data}
/>
```
instead of the previous one with enableRowSelection={true}, the columns appear correctly in the toggle for hiding/showing columns. This behavior is quite perplexing.

**Reconsidering My Approach:**

There's a chance that I might be missing something or not implementing it correctly. If that's the case, I apologize for raising this issue. I find Material React Table to be a powerful tool and I'm eager to make it work in my scenario. Could there be a solution or a different approach that I haven't considered? Any guidance or suggestions would be greatly appreciated to ensure the best use of MRT in my case.

### Minimal, Reproducible Example - (Optional, but Recommended)

**Sandbox Example for Demonstration:**

To simplify and clearly demonstrate the issue, I've created a sandbox example. This example encapsulates the core of the problem while abstracting away the complexities of the full application.

https://codesandbox.io/p/sandbox/mrt-columns-not-showing-in-toggle-hidding-cghq73

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/153269581/0966c8e5-c3b8-4cc5-b243-43b3ad4e5d26)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
If you are using dynamic columns, you will have to manage the `columnOrder` state yourself. I might need to add official docs for this, since this has been asked a dozen times before.

**Comment by KevinVandy** [comment]
Just added an example to the docs https://www.material-react-table.com/docs/examples/dynamic-columns

**Comment by NolanAntonn** [comment]
Perfect ! Thanks a lot Kevin ! Amazing work !
