### ISSUE TITLE
Can't register changes immediately in "cell" or "table" editing mode

### ISSUE THREAD

**Issue by githorse** [KevinVandy/material-react-table#873]
### material-react-table version

v2.0.5

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

The docs for [table editing mode](https://www.material-react-table.com/docs/examples/editing-crud-inline-table) and [cell editing mode](https://www.material-react-table.com/docs/examples/editing-crud-inline-cell) use the `onBlur` event to trigger a save. This works and kinda makes sense if the user is editing multiple cells, but as you can see in the demo, the "Save" button doesn't light up until the user has clicked somewhere outside of the edited cell. This is non-intuitive; if I've changed the value in a cell, I would expect the "Save" button to become clickable. Using `onBlur`, it's not obvious to my user what to do next after editing a value (namely, click somewhere else on the screen to get the "Save" button to light up).

Regardless, in my application, I want to know immediately if the value in my cell has changed, not just after the `onBlur` event. Problem is, I can't figure out the event(s) to hook into to make that work. For `Select` boxes, seems like I can use `onClick`, something like this:

```
muiEditTextFieldProps: ({row, cell}) => ({
  onClick: () => {
    const value = row._valuesCache[cell.column.id]
    // do something with value
  }
})
// seems these props are applied to Selects as well as text fields
```

But I can't figure out how to make a (real) text field work. `onChange` does not fire. I can use `onKeyDown`, etc., but the `row._valuesCache` is not yet updated when those events fire, so I can't see any way to get the updated value.

In "cell" and "table" editing modes, how can I pick up an editing change immediately, instead of after a blur?  

### Minimal, Reproducible Example - (Optional, but Recommended)

The central issue (`Save` button not appearing until after clicking somewhere else on the screen) is visible in the [demo](https://www.material-react-table.com/docs/examples/editing-crud-inline-cell).

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/8271372/2b883202-f57b-4d30-95a5-ce120e902229

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Why isn't the edit onChange working for you? Works perfectly fine here: https://www.material-react-table.dev/?path=/story/features-editing-examples--editing-cell-manual-on-change

**Comment by KevinVandy** [comment]
Closing this as `muiEditTextFieldProps.onChange` in both table options and column defs seem to be working perfectly fine.

**Comment by githorse** [comment]
You are right -- I had code elsewhere that was overwriting `onChange` in those cells. It works as advertised. All good!

Specifically, I have some column-level code I wrote to apply to all columns that was overwriting the table-level `onChange` handler I was playing with, resulting in a very elusive bug. Maybe it would be helpful to log a warning if both a column and the table try to define `muiEditFieldTextProps`? (That could get annoying -- maybe there could be a `debug` mode or something that would turn on more warnings?)
