### ISSUE TITLE
setting enableGrouping on useMaterialReactTable args makes browser unresponsive but works on <MaterialReactTable>

### ISSUE THREAD

**Issue by andreimatei** [KevinVandy/material-react-table#874]
### material-react-table version

v2.0.5

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

I've got a page on which doing the following:
```
 const table = useMaterialReactTable({
    columns,
    data: frames,
    enableGrouping: false,
});
```
causes the Chrome tab to become completely unresponsive, even if `table` is not used for anything. Setting `enableGrouping: false` makes it work.

Also, passing the exact same data directly to `<MaterialReactTable>` also works.
```
<MaterialReactTable
      columns={columns}
      data={frames}
      enableColumnResizing/>
```

The `data` is not very large -- it consists of 4 rows with a couple of JSON columns.

### Minimal, Reproducible Example - (Optional, but Recommended)

Don't have one.

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Can almost bet you're another victim of this:

<img width="1190" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/a2c54591-a3e5-4410-b667-d3a317a61604">

**Comment by KevinVandy** [comment]
Please read the [usage docs](https://www.material-react-table.com/docs/getting-started/usage) to read about how to define your data with a stable reference.

**Comment by andreimatei** [comment]
That did it, thank you!

Consider calling this out in the migration guide from v1 (perhaps also this could be listed as a reason for not using the hook), or perhaps detecting at runtime and yelling somehow.
