### ISSUE TITLE
Filter variant popover tooltip

### ISSUE THREAD

**Issue by nemanjam1** [KevinVandy/material-react-table#875]
### material-react-table version

v2.0.5

### react & react-dom versions

v18.2

### Describe the bug and the steps to reproduce it

Tooltip that appears after user hovers column filter button on filter mode popover and filter variant is select displays option id instead of option label/text 

### Minimal, Reproducible Example - (Optional, but Recommended)

<img width="230" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/105542386/6dbb17f1-4154-48a4-990a-5a64163fa6fa">
<img width="219" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/105542386/1e8b6e23-8f91-4b4d-95a4-097e6d723e6f">

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
There's not really an easy fix for this

**Comment by ISvirko** [comment]
would be great to be able to set own text for this filter tooltip. I have a custom filter components which saves its state as object, so the stringified version of it looks not user friendly

**Comment by loughlinclaus3** [comment]
Fixed in this PR https://github.com/KevinVandy/material-react-table/pull/997
