### ISSUE TITLE
codesandbox example not working

### ISSUE THREAD

**Issue by s-light** [KevinVandy/material-react-table#879]
### material-react-table version

v2.0.6

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

expecting working example in codesandbox.
but this fails:
```bash
[plugin:vite:import-analysis] Failed to resolve import "@tanstack/react-query" from "src/TS.tsx". Does the file exist?

/workspace/src/TS.tsx:24:7

35 |    useQuery,
36 |    useQueryClient
37 |  } from "@tanstack/react-query";
   |          ^
38 |  import { fakeData, usStates } from "./makeData";
39 |  import DeleteIcon from "@mui/icons-material/Delete";
```

### Minimal, Reproducible Example - (Optional, but Recommended)

- go to one of the examples code section https://www.material-react-table.com/docs/guides/editing#editing-crud-cell-source-code
- open *codesandbox* 
- wait till finished loading.
- shows error..

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/1340319/4146fcfa-d56a-4d6c-b17c-ec50f93eeaca)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
When there are simple issues like this, it helps if you just make a PR when you know what the issue is. Just had something missing from the package.json

**Comment by s-light** [comment]
Sorry 
I really Bad no idea whatthe error was..
And also no experience with code Sandbox..
Next time i try!

**Comment by KevinVandy** [comment]
Ah my bad, I just dealt with too many issues pointing out typos without PRs lately. Bad response from me
