### ISSUE TITLE
single-click to activate editing mode does not work

### ISSUE THREAD

**Issue by s-light** [KevinVandy/material-react-table#880]
### material-react-table version

v2.0.6

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

in the 
[Cell Edit Display Mode](https://www.material-react-table.com/docs/guides/editing#cell-edit-display-mode)
it says
```jsx
    //optionally, use single-click to activate editing mode instead of default double-click
 muiTableBodyCellProps: ({ table, cell }) => ({
      onClick: () => {
        table.setEditingCell(cell);
      },
    }),
```
but for me i need to do two clicks in a row to edit the text:
- first click -  i get the edit line below the cell but the input is not focused
- second click - focus is in input and i can start typing

i also mentioned this in [this forum thread](https://discord.com/channels/937072769831694406/1184127164845658192)

### Minimal, Reproducible Example - (Optional, but Recommended)

based loosely on the [basic edit cell example](https://www.material-react-table.com/docs/guides/editing#cell-edit-display-mode)
→ https://codesandbox.io/p/devbox/mrt2-editing-tests-5s6gg7?file=%2Fsrc%2Fmytable.jsx%3A18%2C25
```jsx
import { useEffect, useMemo, useRef, useState } from "react";
import {
  MaterialReactTable,
  useMaterialReactTable,
} from "material-react-table";

import demoDataPerson from "./demodata.json";
import demoDataColumns from "./demodataColumns";

export default function Example() {
  const data = useMemo(() => demoDataPerson, []);
  const columns = useMemo(() => demoDataColumns, []);

  const table = useMaterialReactTable({
    columns,
    data,
    enableEditing: true,
    editDisplayMode: "cell",
    //optionally, use single-click to activate editing mode instead of default double-click
    muiTableBodyCellProps: ({ table, cell }) => ({
      onClick: () => {
        table.setEditingCell(cell);
      },
    }),
  });

  return <MaterialReactTable table={table} />;
}

```

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/1340319/8739c988-1012-41e4-932a-afc5c98349ce

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging
for this i would need a helping hand..

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by s-light** [comment]
interesting enough: the default behavior does work as it should:
i do a double click and the input is focused and i can start typing

**Comment by KevinVandy** [comment]
I don't see this as a bug in MRT. It's up to the implementor if they want to focus the input. I can update the docs to do what I do internally though.

```ts
  muiTableBodyCellProps: ({ cell, column, table }) => ({
    onClick: () => {
      table.setEditingCell(cell); //set editing cell
      //optionally, focus the text field
      queueMicrotask(() => {
        const textField = table.refs.editInputRefs.current[column.id];
        if (textField) {
          textField.focus();
          textField.select?.();
        }
      });
    },
  }),
```
