### ISSUE TITLE
Support tan-stack column isVisible

### ISSUE THREAD

**Issue by ngouy** [KevinVandy/material-react-table#884]
### material-react-table version

2.0.6

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

https://github.com/TanStack/table/blob/v7/docs/src/pages/docs/api/useTable.md#column-properties

TanStack table have a property on column to show/hidde them on first render directly from the column attributes

It's very practical when you want to hide everything except a few cherry-picked columns, vs doing the opposite of having to cherry-pick all the one you don't want when you want 4 on 40 by default

### Minimal, Reproducible Example - (Optional, but Recommended)

```ts
const columns = [
    {
        accessorKey: "properties.lastName",
        header: "Last Name",
        isVisible: false,
      }
]

export default myComponent = () {
  return  <MaterialReactTable table={{
    columns: columns, // lastName is visible
    data: [],
  }} />
```

### Do you intend to try to help solve this bug with your own PR?

No, because I do not have time to dig into it

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This does not exist on TanStack Table v8, and for good reason. Use `initialState` instead. Just read the [column hiding docs](https://www.material-react-table.com/docs/guides/column-hiding#hide-some-columns-by-default) to see how to do it properly.

**Comment by ngouy** [comment]
my bad 🙇 
For some reason I was persuaded v7 was the last one
