### ISSUE TITLE
createDisplayMode = 'row' not working with enableRowVirtualization = true 

### ISSUE THREAD

**Issue by dangkhoa99** [KevinVandy/material-react-table#886]
### material-react-table version

v2.0.6

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

The table enable rowVirtualization = true and createDisplayMode = 'row'. This row not showing on table.

### Minimal, Reproducible Example - (Optional, but Recommended)

```
const table = useMaterialReactTable({
    columns,
    data: fetchedUsers,
    createDisplayMode: 'row',
    editDisplayMode: 'row',
    enableEditing: true,
    enableRowVirtualization: true,
    getRowId: (row) => row.id
)}
```

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/56160839/990d2b09-56a2-4f53-9c4f-00e6474f6a48)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Yeah this is a current incompatibility. Open to suggestions or fixes

**Comment by dangkhoa99** [comment]
@KevinVandy , I think we can split that component "creatingRow" into a TableBody. I tested it and it works fine. Do you think that's okay?
```
  {creatingRow && createDisplayMode === 'row' && (
        <TableBody
          {...tableBodyProps}
          sx={(theme) => ({
            display: layoutMode?.startsWith('grid') ? 'grid' : undefined,
            ...(parseFromValuesOrFunc(tableBodyProps?.sx, theme) as any),
          })}
        >
          <MRT_TableBodyRow row={creatingRow} rowIndex={-1} table={table} />
        </TableBody>
  )}
```
