### ISSUE TITLE
Warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by dangkhoa99** [KevinVandy/material-react-table#889]
### material-react-table version

v2.1.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

@KevinVandy 
Warning: Encountered two children with the same key. Although, the id is unique.

And I discovered that in the code you are setting ```key={`${row.id}${row.index}`}```. I suggest you change it to ```key={`${row.id}-${row.index}`}```

### Minimal, Reproducible Example - (Optional, but Recommended)

You can see the image below: 

### Screenshots or Videos (Optional)

**Error:**

![image](https://github.com/KevinVandy/material-react-table/assets/56160839/d971eb89-decd-4c76-82e4-9e1d3ab61fec)

**Your code:**
![image](https://github.com/KevinVandy/material-react-table/assets/56160839/3cb4875e-e39c-435d-980e-6102223cfda9)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Feel free to make a PR
