### ISSUE TITLE
Global filter removes sorting

### ISSUE THREAD

**Issue by alexander7161** [KevinVandy/material-react-table#897]
### material-react-table version

2.1.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

When global filter is set to any value, the sorting state is reset to no sorting.

(see video)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.dev/?path=/story/features-sorting-examples--sorting-enabled-default

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/9217537/20c27fe5-b36f-48bd-b650-0ec7b0ffc130

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This is an intended feature. You can disable it with `enableGlobalFilterRankedResults: false`
