### ISSUE TITLE
Warning: React does not recognize the `virtualIndex` prop on a DOM element.

### ISSUE THREAD

**Issue by dangkhoa99** [KevinVandy/material-react-table#899]
### material-react-table version

v2.3.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Warning: React does not recognize the `virtualIndex` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `virtualindex` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Minimal, Reproducible Example - (Optional, but Recommended)

You can see the image below:

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/56160839/d336a71f-10fc-4275-be55-5d692c308cfd)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v2.3.1
