### ISSUE TITLE
Uncaught Error: getRow expected an ID, but got mrt-row-create

### ISSUE THREAD

**Issue by dangkhoa99** [KevinVandy/material-react-table#901]
### material-react-table version

v2.3.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Uncaught Error: getRow expected an ID, but got mrt-row-create.

row selection with createDisplayMode="row" error.

I select checkbox in createRow and crash

### Minimal, Reproducible Example - (Optional, but Recommended)

```
const table = useMaterialReactTable({
    columns,
    data: fetchedUsers,
    createDisplayMode: 'row',
    enableRowSelection: true,
)}
```

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/56160839/e0221d74-07c8-4bab-9478-0eb315020920)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v2.3.1
