### ISSUE TITLE
Error show hiding column

### ISSUE THREAD

**Issue by dangkhoa99** [KevinVandy/material-react-table#913]
### material-react-table version

v2.3.1

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Hello @KevinVandy,

I use columnVisibility state, visibleInShowHideMenu, enableHiding `mrt-row-pin` to completely hide the actions column.

When I click `Hide all` button then click `Show all`. The `mrt-row-pin` still visible.

Note: I want **_test_** completely hide although ```enableRowPinning = true``` with your suggestion: https://github.com/KevinVandy/material-react-table/pull/903#issuecomment-1874267577

### Minimal, Reproducible Example - (Optional, but Recommended)

```
<MaterialReactTable
    columns={columns}
    data={data}
    enablePagination={false}
    enableRowPinning
    enableRowVirtualization
    muiTableContainerProps={{
      sx: { maxHeight: '600px' },
    }}
    initialState={{
      columnVisibility: {
        'mrt-row-pin': false,
      },
    }}
    rowPinningDisplayMode="top"
    displayColumnDefOptions={{
      'mrt-row-pin': {
        enableHiding: true,
        visibleInShowHideMenu: false,
        size: 0,
        maxSize: 0,
        minSize: 0,
      },
    }}
  />
```

### Screenshots or Videos (Optional)

[Screencast from 01-04-2024 11:19:24 PM.webm](https://github.com/KevinVandy/material-react-table/assets/56160839/03a8373f-8e6c-46b2-bb22-b9b5241c9f75)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Try `enableHiding: false` instead?

**Comment by dangkhoa99** [comment]
@KevinVandy, It works well for my case. Thank you very much.
