### ISSUE TITLE
using onIsFullScreenChange will break the fullscreen button

### ISSUE THREAD

**Issue by BennyAlex** [KevinVandy/material-react-table#918]
### material-react-table version

2.4.0

### react & react-dom versions

18

### Describe the bug and the steps to reproduce it

when passing onIsFullScreenChange as a prop, the enter fullscreen button will not work. 
It also does not call the onIsFullScreenChange function at all.

### Minimal, Reproducible Example - (Optional, but Recommended)

onIsFullScreenChange={() => true}

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Event though you didn't share your full code, I can take a guess that you didn't pass the `isFullScreen` state back into the `state` option. This is required to manage any MRT state in your own scope.
Please read the state management docs: https://www.material-react-table.com/docs/guides/state-management

Working example can also be seen here: https://www.material-react-table.dev/?path=/story/features-full-screen-examples--controlled-full-screen

**Comment by BennyAlex** [comment]
> Event though you didn't share your full code, I can take a guess that you didn't pass the `isFullScreen` state back into the `state` option. This is required to manage any MRT state in your own scope. Please read the state management docs: https://www.material-react-table.com/docs/guides/state-management
> 
> Working example can also be seen here: https://www.material-react-table.dev/?path=/story/features-full-screen-examples--controlled-full-screen

Thanks.

Unfortunately there is no description in the docs for that function.

I also thought it is a simple callback function when the full screen state changes, as it's name suggest.
It's not clear that it will be used to change the full screen manually.
