### ISSUE TITLE
Since V2 header groups with column resizing have a different width to the sum of their sub headers

### ISSUE THREAD

**Issue by alexander7161** [KevinVandy/material-react-table#925]
### material-react-table version

2.5.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

See screenshot of storybook V1:
Notice the draggers to resize the columns are aligned.
![image](https://github.com/KevinVandy/material-react-table/assets/9217537/24287cad-a20a-48a7-bf46-61f1385467b1)
Storybook V2:
Draggers for the first row are not in-line with the second row.
![image](https://github.com/KevinVandy/material-react-table/assets/9217537/d18b9760-6771-47f8-af4c-c5bb32f22de6)
https://www.material-react-table.dev/?path=/story/features-header-groups-examples--header-groups-with-colum-resizing

I noticed without column resizing enabled this is not the case:

This is "[Header groups](https://www.material-react-table.dev/?path=/story/features-header-groups-examples--header-groups)" example. I changed the background colour in dev tools

![image](https://github.com/KevinVandy/material-react-table/assets/9217537/c60bd9e9-132a-4180-acc7-95b4e013cc83)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.dev/?path=/story/features-header-groups-examples--header-groups-with-colum-resizing

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
yes, for some reason this does not work perfectly in layoutMode: 'grid', or 'grid-no-grow'. Setting layoutMode to 'semantic' fixes it all the way.
In version 2.6.0, it is slightly better.
