### ISSUE TITLE
Filter variant: range-slider not displaying correctly in popover filter display mode

### ISSUE THREAD

**Issue by Hurtindonkey** [KevinVandy/material-react-table#926]
### material-react-table version

2.4.1

### react & react-dom versions

18.2

### Describe the bug and the steps to reproduce it

Changing the [Filter Variants Example](https://www.material-react-table.com/docs/examples/filter-variants) from the Material React Table V2 documentation to: `columnFilterDisplayMode: 'popover',` is not showing the range slider in its entirety for the Salary Column

### Minimal, Reproducible Example - (Optional, but Recommended)

https://codesandbox.io/p/devbox/stoic-flower-gzzxgf

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/12531099/2733bc9c-03d6-4280-8ba4-55b2a1830998)

### Do you intend to try to help solve this bug with your own PR?

No, because I do not know how

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fixed in v2.5.1

**Comment by KevinVandy** [comment]
also can use `muiFilterSliderProps.sx.width` for a custom width
