### ISSUE TITLE
Tooltip for active filter shows "undefined" when a custom filter function is used

### ISSUE THREAD

**Issue by sebaranowski** [KevinVandy/material-react-table#927]
### material-react-table version

v.2.5.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Tooltip for active filter shows "undefined" when a custom filter function is used.

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.dev/?path=/story/features-filtering-examples--custom-filter-fns

### Screenshots or Videos (Optional)

![image](https://github.com/KevinVandy/material-react-table/assets/26111785/b82f94b9-81f7-431a-8dd1-de91cdcd0fe1)

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by sebaranowski** [comment]
Workaround: omit `{filterType}` in i18n template key `filteringByColumn`. Eg.:

```tsx
<MaterialReactTable
  columns={[
    {
      accessorKey: 'firstName',
      header: 'First Name',
    },
    {
      accessorKey: 'state',
      filterFn: 'customFn',
      header: 'State',
    },
  ]}
  data={data}
  filterFns={{
    customFn: (row, _columnIds, filterValue) => {
      console.info('customFn', row, _columnIds, filterValue);
      return row
        .getValue<string>('state')
        .toLowerCase()
        .startsWith(filterValue.toLowerCase());
    },
  }}
  initialState={{ showColumnFilters: true }}
  localization={{ filteringByColumn: 'Filtering by {column} - {filterValue}' }}
/>
```

**Comment by KevinVandy** [comment]
There's already an example in the docs showing with how to provide the proper localization https://www.material-react-table.com/docs/guides/column-filtering#customize-filter-modes-source-code
