### ISSUE TITLE
Incompatibility with <ThemeProvider/> from '@mui/joy/styles'

### ISSUE THREAD

**Issue by ayshamusthak76** [KevinVandy/material-react-table#931]
### material-react-table version

v2.5.1

### react & react-dom versions

"react": "^18.2.0",  "react-dom": "^18.2.0",

### Describe the bug and the steps to reproduce it

I've recently started a new project using Material React Table (v2) along with Joy UI. However, I'm encountering an issue when attempting to use Joy UI's ThemeProvider alongside Material React Table.

Cannot read properties of undefined (reading '2')
TypeError: Cannot read properties of undefined (reading '2')
    at Paper (http://localhost:3000/static/js/bundle.js:20256:22)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:91592:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:94161:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:96208:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:81188:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:81232:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:81289:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:101153:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:100401:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:100324:9)
    

Steps to Reproduce:

1. Create a new React project with TypeScript.
2. Install Joy UI.
3. In App.tsx, use ThemeProvider from Joy UI.
4. Utilize the simple example provided in the Material React Table documentation.

I appreciate your assistance in resolving this matter. Please let me know if there are any additional details required.

### Minimal, Reproducible Example - (Optional, but Recommended)
`
import React from 'react';
import './App.css';

import { CssVarsProvider, ThemeProvider } from '@mui/joy/styles';
import Sheet from '@mui/joy/Sheet';
import { CssBaseline } from '@mui/joy';
import TestTable from './testTable';

function App() {
  return (
    <ThemeProvider >
      {/* <CssVarsProvider> */}
      <div className="app" >
        <CssBaseline />
        <TestTable />
      </div >
      {/* </CssVarsProvider> */}
    </ThemeProvider>
  );
}

export default App;
`

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
MRT requires the MUI theme provider. I think the joy UI docs has a section about how to use MUI and joy side by side, but it is not ideal.

Would you be interested in a potential joy-react-table project though?

**Comment by rodrigo-gross** [comment]
I would love it, we are using this table in a couple projects but for a new one we switched to mui joy and I really miss it

**Comment by KevinVandy** [comment]
> I would love it, we are using this table in a couple projects but for a new one we switched to mui joy and I really miss it
@rodrigo-gross 

I read in [MUI's 2024 roadmap](https://mui.com/blog/2023-material-ui-v6-and-beyond/) that the are putting JOY UI development on hold for up to 6 months.

I probably won't be developing a dedicated JOY ui library until Material UI v6 and the zero runtime style engine is out.

But... I am continuing to refactor and setup the MRT project to potentially be rewritten with Base UI in mind, so that both Material UI and Joy UI could be simple adapters of a base MRT project. That's the dream anyway.

**Comment by rodrigo-gross** [comment]
Nice, will keep an eye, thanks
