### ISSUE TITLE
Table does not refresh with update pagination state when turn on manual Pagination 

### ISSUE THREAD

**Issue by wwu2008** [KevinVandy/material-react-table#943]
### material-react-table version

2.6.1

### react & react-dom versions

react: 18.2.0 react-dom:18.0.0

### Describe the bug and the steps to reproduce it

In my case I need to use controlled pagination ire manual pagination. Following code using manual pagination and set initial pagination pageIndex:2, pageSize:5 when open the page it display page 1 and display all records on the table, it should display page 3 and only 5 records.  Checked pagination state, it's correct but table wont refresh for initial or update pagination state. This stops me using manual pagination.

### Minimal, Reproducible Example - (Optional, but Recommended)

function PersonSearchResults(props) {     
     ....
           const [personSearchTableData, setPersonSearchTableData] = useState([]);
           const [pagination, setPagination] = useState({
                  pageIndex: 2,
                  pageSize: 5,
              });
          ...
          useEffect(() => {
              loadingData();
          }, [pagination.pageIndex, pagination.pageSize]);
          

         const getSearchResult = () => {
                 // loading data
                ....
                setPersonSearchTableData(rst.personData);
       
          }

          // define table instance
          const table = useMaterialReactTable({
                  columns: tableColumns,
                  data: personSearchTableData,
                  enablePagination: true,
                  manualPagination: true,
                  initialState: {pagination: pagination},
                  paginationDisplayMode: 'pages',
                  muiPaginationProps: {
                      color: 'primary',
                      shape: 'rounded',
                      showRowsPerPage: true,
                      variant: 'outlined',
                  },
          });
          
           return (
                  <div>
                      <MaterialReactTable table={table}/>
                  </div>);
}

### Screenshots or Videos (Optional)

manunlPagination = false:
![image](https://github.com/KevinVandy/material-react-table/assets/5219372/2f8afbe9-8e36-432c-9a6b-78cd621a6015)

manualPagination =true:
![image](https://github.com/KevinVandy/material-react-table/assets/5219372/139c8cee-f110-4dd0-bc49-055b1e51e58e)
![image](https://github.com/KevinVandy/material-react-table/assets/5219372/76799e33-af37-4cc3-8329-ae70cd4bea66)

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Pass your pagination state to `state` instead of `initialState`

**Comment by wwu2008** [comment]
thanks for the response, tried following, but same problem still there ...
.....
const table = useMaterialReactTable({
              columns: tableColumns,
              data: personSearchTableData,
              enablePagination: true,
              manualPagination: true,
               **state: {pagination},**
});

**Comment by wwu2008** [comment]
the problem is when the pagination state is changed but table.options.state.pagination.pageIndex is not updated the result is table is not refreshed with changed state (pagination)

**Comment by KevinVandy** [comment]
Make a sandbox showing the bug and I can look. If this was a true bug in MRT, I would expect this example to be broken, but it seems fine: https://www.material-react-table.com/docs/examples/react-query

**Comment by wwu2008** [comment]
Hi Kevin, thanks for the quick response, I did some local testing with reference on the example you provided unfortunately the problem still not resolved. I created a Pagination test component on code sandbox, It shows all records on the table when set manualPagination = true and I can see the bottom pagination component show page size = 5, but when I switch off manualPagination it shows 5 records as expected.  
https://codesandbox.io/p/sandbox/react-environment-forked-225wm3?file=%2Fsrc%2FPaginationTest.js%3A62%2C26

**Comment by KevinVandy** [comment]
@wwu2008  It is working as designed. You do realize that setting `manualPagination: true` means that all internal pagination logic in MRT is turned off, and assumes that the `data` that you pass to the table is already correctly paginated. It is up to your back-end to apply the correct data size when using manual pagination.

From the docs: 
<img width="1288" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/6fde00eb-7448-4e25-96c2-a8da09620cc3">

In your sandbox, you are hardcoding the data to always be 16 rows, with none of your own pagination logic applied, so it will always just show those 16 rows if manualPagination is true.

If you don't want to do pagination logic in your back-end, just don't turn it off in MRT.

**Comment by wwu2008** [comment]
Hi Kevin, Yes, I got your meaning. Manual pagination is designed ONLY for backend server pagination. In my user case I load whole data from backend (without pagination) so no need to use manual pagination, everything working fine. However some data in my table has link when user click it opens (navigate) another page with state data piped to the new page (table data including pagination index and size). On this new page when user click back button the UI would reload the previous table page data (I use redux useSelector hook) with same data and same pagination (index and size). when reload the page we need to reset the pagination (cashed when load new page with link) we don't want load page with initial pagination instead I need to reset current table pagination (index) to cashed index, (for example, before navigate to new page I was in page3, ie pageIndex=2, and when navigate back I should in page 3, not page1 for the table in pagination) in this case I need use some table pagination (build in not manual) API to reset pagination state and trigger page refresh with new index/size but seems MRT do not provide this feature. In my impression there is only 2 options: Opt 1 use build in pagination ie MRT will auto handle state and etc. or Opt2 use manual pagination handle state by yourself (backend),  Unfortunately it's not fit my needs I need opt 1 but I can change pagination state when required,  Can you give me some suggestions to achieve my goal? BTY I love MRT it's easy use with nice features & functions.

**Comment by wwu2008** [comment]
In summary of my comments, I'm looking for a solution to change MRT build-in pagination (Auto) state without using manual pagination. I did try to achieve this by forcing reloading the page via props (pageIndex) & set initial state pagination but it's still not fully solved my issue. If current MRT don't provide this feature, I'd strongly reaccommodate adding this in next version. It will largely promote usage of MRT.

**Comment by bylly1** [comment]
Why you need that if you can add page number as params to the url to receive actual page payload. The links are useful only when you have an app that use SSR not CSR. 

If you can access page payload like this:
```
http://locahost/api/data?page=1
```
You don't need those links

**Comment by KevinVandy** [comment]
I still don't understand what they're asking for
