### ISSUE TITLE
Scrolling bug - using RowVirtualization

### ISSUE THREAD

**Issue by yuvald-monto** [KevinVandy/material-react-table#953]
### material-react-table version

1.9.3

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

We have Material React Table with `enableRowVirtualization` and `rowVirtualizerInstanceRef` props.
The bug is when the user scrolls, the table scrolls a little bit down and jumps back up - so the user is stuck in the same scroll position.

**Notes**:
- This bug does not happen for every user (so it's hard to catch it).
- It happened in different browsers.
- After our users tried to change the browser's zoom settings it helped to stop the bug.
- We suspect that without using virtualization this bug is not happening (from our tests after removing `rowVirtualizerInstanceRef` from MRT component). 

To reproduce the bug you can try scrolling top and down many times, clicking on rows, and back to the table page (maybe try from different computers).

### Minimal, Reproducible Example - (Optional, but Recommended)

I can't share here our production environment, but here we created an example app with our table.
https://mrt-preview.vercel.app/

**Our table component:**
https://github.com/yuvald-monto/mrt-preview/blob/main/components/TableRMT.tsx

`saveScrollPosition` - we have function that called on scroll, that save in the store the scroll position of the table (using zustand).

We have useEffect that scrolls to the last scroll position after the component mount:
` useEffect(() => {
      rowVirtualizedInstanceRef.current?.scrollBy?.(scrollPosition);
    }, [router.isReady, rowVirtualizedInstanceRef.current, router.pathname]); `

**Usage of table component:**
https://github.com/yuvald-monto/mrt-preview/blob/main/pages/index.tsx

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/118466011/1127d62f-e783-4cc7-905b-a5c9451326e5

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
This was fixed a long time ago. Upgrade to a newer version
