### ISSUE TITLE
Since V2 - group by arrows displayed at the end of the row

### ISSUE THREAD

**Issue by yuvald-monto** [KevinVandy/material-react-table#959]
### material-react-table version

2.8.0

### react & react-dom versions

18.2.0

### Describe the bug and the steps to reproduce it

After group by column, the groups arrows displayed at the end of the row, so the user need to scroll right in order to see there are arrows to click on in order to see all the rows.
In our production env, after refresh - the arrows displayed next to the value title (like before the migration).
In the [demo env](https://mrt-preview.vercel.app/), the arrows still displayed at the end of the row after refresh. 

### Minimal, Reproducible Example - (Optional, but Recommended)

**Link to demo env** - https://mrt-preview.vercel.app/
https://github.com/yuvald-monto/mrt-preview
**Table Component** - https://github.com/yuvald-monto/mrt-preview/blob/main/components/TableRMT.tsx

### Screenshots or Videos (Optional)

https://github.com/KevinVandy/material-react-table/assets/118466011/27b61beb-a704-4202-baa2-0390280bd8b7

We expect the arrows will be next to the grouped column:
<img width="200" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/118466011/1e9f3577-8db5-4a57-965c-959adf19c0a7">

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
If you're managing column order state, you just - need to have the expand column in the correct position

**Comment by KevinVandy** [comment]
I actually went ahead and improved this in v2.10.0 so that you don't have to manage the columnOrder state manually. MRT should now automatically insert the expand column in the correct place, even with both managed grouping and/or columnOrder state in your own scope passed down to MRT.
