### ISSUE TITLE
Using a MUI icon for a column Header results in strange extra space

### ISSUE THREAD

**Issue by imnasnainaec** [KevinVandy/material-react-table#962]
### material-react-table version

v2.9.2

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

I'm using a MUI icon for one of my column headers:
```
[...]
import { LocationOn } from '@mui/icons-material';
[...]
Header: <LocationOn fontSize="small" />,
[...]
```

The icon height is only 20px, but for some reason the containing Mui-TableHeadCell-Content-Wrapper has height 27px, whereas the same component in the default column headers has height 24px.
![Screenshot 2024-01-29 164851](https://github.com/KevinVandy/material-react-table/assets/6411521/777d197c-5651-428d-8ec3-773f593f1981)
![Screenshot 2024-01-29 164906](https://github.com/KevinVandy/material-react-table/assets/6411521/ce63f0b7-de71-4434-af7c-04c2b770395b)
![Screenshot 2024-01-29 164917](https://github.com/KevinVandy/material-react-table/assets/6411521/1b497b6e-159c-4357-89b7-a4cddeb9ec5c)

The result is that the icon is oddly offset and the filter for that column is pushed lower than for other columns.
![Screenshot 2024-01-29 164830](https://github.com/KevinVandy/material-react-table/assets/6411521/a665d318-cf25-4fde-bca0-24c89b06e9ff)

### Minimal, Reproducible Example - (Optional, but Recommended)

The (https://www.material-react-table.com/docs/examples/basic) example minimally modified for this situation: https://codesandbox.io/p/devbox/jolly-jang-jqy92z

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Feel free to style the header elements using the targeted Mui-* classNames however you need for your own use case.

**Comment by imnasnainaec** [comment]
Thank you, @KevinVandy. I tried that with `muiTableHeadCellProps` to no avail, and there is no `muiTableHeadCellContentProps` or `muiTableHeadCellContentWrapperProps` to work with.

**Comment by KevinVandy** [comment]
@imnasnainaec You don't need dedicated props for every div. Just target it's className. Here's an exampele from the docs
https://www.material-react-table.com/docs/guides/column-actions#justify-column-actions-button
<img width="527" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/5c41db92-a97b-4b59-8121-9ad53fe52293">

**Comment by imnasnainaec** [comment]
Ah, thank you!
