### ISSUE TITLE
When enabling row virtualization and setting minSize to 'fit-content' and maxSize to 'auto' in the default column configuration, the column width squeezes to 0, causing overlapping.

### ISSUE THREAD

**Issue by vinit-poojary** [KevinVandy/material-react-table#967]
### material-react-table version

v2.6.1

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

Could you set up a table component?

Add the following configurations:
```
defaultColumn: {
  minSize: 'fit-content',
  maxSize: 'auto',
},
enableRowVirtualization: true,

```
Could you observe the column width behaviour?

### Minimal, Reproducible Example - (Optional, but Recommended)

```
const tableConfig = useMaterialReactTable({
  // Other table configurations...
  enableRowVirtualization: true,
  defaultColumn: {
    minSize: 'fit-content',
    maxSize: 'auto',
  },
})
```

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
Only integers are supported for `size`, `minSize`, and `maxSize` column options. You'll have to use `muiTableHeadCellProps.sx.width`, `muiTableBodyCellProps.sx.width`, etc. if you want to specifiy your own CSS.

**Comment by vinit-poojary** [comment]
Is there a way to set the minimum column width to the width of the header content, while allowing the body to occupy maximum column width?
