### ISSUE TITLE
isMounted ref not correctly used

### ISSUE THREAD

**Issue by ribx** [KevinVandy/material-react-table#968]
### material-react-table version

2.10.0

### react & react-dom versions

not important

### Describe the bug and the steps to reproduce it

While browser the code of the repo I found an incorrect usage of a isMounted ref:

```
const isMounted = useRef(false);
if (isMounted && ...) {...}
```

instead of `isMounted.current`. The ref itself will always evaluate to true. Maybe you also want to setup some linting to catch these errors.

It can be found here: https://github.com/KevinVandy/material-react-table/blob/7cd340b01180cfea01876eed6a86be24af8aabf8/packages/material-react-table/src/hooks/useMRT_Effects.ts#L45

### Do you intend to try to help solve this bug with your own PR?

Yes, I think I know how to fix it and will discuss it in the comments of this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
did you want to make a PR or just point it out? Any bug that this is causing?
