### ISSUE TITLE
Autocomplete filterVariant with [{value, label}] options show value, not label, when selected

### ISSUE THREAD

**Issue by dmitry-simple-it** [KevinVandy/material-react-table#971]
### material-react-table version

v2.8.0

### react & react-dom versions

v18.2.0

### Describe the bug and the steps to reproduce it

This could be tested right in deployed official storybook app: https://www.material-react-table.dev/?path=/story/features-filtering-examples--filter-fn-and-filter-variants-faceted

Issue in First Name column. When we press on filter text field dropdown shows labels of suggested filterSelectOptions:
<img width="480" alt="Screenshot 2024-02-04 at 13 02 21" src="https://github.com/KevinVandy/material-react-table/assets/118734134/842e4aa4-160e-4d12-b915-2100d65e9294">

 but when we select some of it we see "value" of it in the text field, not a "label" as expected:
<img width="536" alt="Screenshot 2024-02-04 at 13 02 56" src="https://github.com/KevinVandy/material-react-table/assets/118734134/1b429572-5939-4a9f-8e3e-80af4986b409">

It is easy to understand in this example as "label" is uppercase of "value" for each element. We can see how this filterSelectOptions generated in the storybook code: 
https://github.com/KevinVandy/material-react-table/blob/fe782f0811792063eac687f477e82657265e4fa9/packages/material-react-table/stories/features/Filtering.stories.tsx#L218-L221

I believe that always showing label, not value is the the proper way how autocomplete filter component should work as in my application value is "id" and I don't want to show id as selected element for user, he will not understand it :)

### Minimal, Reproducible Example - (Optional, but Recommended)

https://www.material-react-table.dev/?path=/story/features-filtering-examples--filter-fn-and-filter-variants-faceted

### Do you intend to try to help solve this bug with your own PR?

Yes, I am also opening a PR that solves the problem along side this issue

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
fix released in v2.11.0
