### ISSUE TITLE
When there is a toptoolbar, grouping doesn't work. 

### ISSUE THREAD

**Issue by CosmeValera** [KevinVandy/material-react-table#981]
### material-react-table version

v2.11.1

### react & react-dom versions

v17.0.2

### Describe the bug and the steps to reproduce it

The grouping appears at the top toolbar like this:
![image](https://github.com/KevinVandy/material-react-table/assets/80126839/54b6b5f2-e70e-4c34-8f70-46916123f734)

However in the advanced example of the documentation, when adding the toptoolbar the grouping is not working anymore. Because both are put in the same place at top of the table:
![image](https://github.com/KevinVandy/material-react-table/assets/80126839/832784bb-3f8f-4aa1-8a29-3c4cfebd453a).

How can I have both functionalities at the same time?

### Minimal, Reproducible Example - (Optional, but Recommended)

Go to the advanced example:
https://www.material-react-table.com/docs/examples/advanced
Open it with Stackblitz or CodeSandbox, and try to group by header.

### Do you intend to try to help solve this bug with your own PR?

None

### Terms

- [X] I understand that if my bug cannot be reliably reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

**Comment by KevinVandy** [comment]
I'm confused by this issue, grouping still works fine in the advanced example. The advanced example is just rendering the MRT_ToolbarAlertBanner component in the bottom toolbar.

<img width="1315" alt="image" src="https://github.com/KevinVandy/material-react-table/assets/28243511/8de52f1f-9a50-4027-a0d4-b8891ce4b61a">

Now if you want, you could just set `positionAlertBanner: 'none'` and then import the `MRT_ToolbarAlertBanner` component and render it anywhere you want. You can see this happening in the [Custom Headless Example](https://www.material-react-table.com/docs/examples/custom-headless)

**Comment by KevinVandy** [comment]
Closing as there are no errors, and this seems to just be a misunderstanding

**Comment by CosmeValera** [comment]
Thanks for answering. Okay, I think I understand now. So grouping there is achieved by using the menu option.

![image](https://github.com/KevinVandy/material-react-table/assets/80126839/a15b478a-1c2a-42fc-bfb1-0369691e47b8)

My bad. I thought that the grouping was always produced by dragging and dropping the move option like in the grouping example, where you drag and drop the header to the drop zone:
https://www.material-react-table.com/docs/examples/column-grouping
